In [1]:
import importlib
import polars as pl
import polars.selectors as cs
from datetime import datetime
import polars_ds as pds
import requests
import json
import duckdb
from pathlib import Path
from time import sleep
import src.utils as utils

importlib.reload(utils)

from src.utils import (
    scrape_eliteserien_results_for_seasons,
    scrape_transfermarkt_goal_contributions,
    scrape_eliteserien_goal_contributions_for_season,
    scrape_eliteserien_lineups_for_season,
    scrape_transfermarkt_lineups,
    scrape_fotmob_eliteserien_results_for_seasons,
    scrape_fotmob_match_report
)

In [2]:
seasons = [
    (2020,2021),
    (2021,2022),
    (2022,2023),
    (2023,2024),
    (2024,2025),
    (2025,2026)
]

db_path = Path("data/brann.duckdb")

# Ingest Eliteserien results

In [10]:
def save_eliteserien_results_for_season(
    season: tuple[int, int | None],
    db_path: Path,
    delay_seconds: float = 0.5,
) -> None:
    """Scrape one Eliteserien season and store it in its own raw_eliteserien_results_<year> table."""
    year = season[1] or season[0]
    table_name = f"raw_eliteserien_results_{year}"

    data = scrape_eliteserien_results_for_seasons([season], delay_seconds=delay_seconds)
    if not data:
        print(f"No records returned for season {season}; skipping.")
        return

    df = pl.DataFrame(data).with_columns(pl.lit(datetime.now()).alias("ingested_at"))

    with duckdb.connect(str(db_path)) as connection:
        connection.register("new_data", df)
        connection.execute(f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM new_data")

    print(f"✓ Saved {len(data)} matches to {table_name}")


# Ingest results season by season so one failing season doesn't block the rest
for season in seasons:
    try:
        save_eliteserien_results_for_season(season, db_path, delay_seconds=0.5)
    except Exception as error:
        print(f"Skipping season {season}: {error}")

✓ Saved 240 matches to raw_eliteserien_results_2021
✓ Saved 240 matches to raw_eliteserien_results_2022
✓ Saved 240 matches to raw_eliteserien_results_2023
✓ Saved 240 matches to raw_eliteserien_results_2024
✓ Saved 240 matches to raw_eliteserien_results_2025
✓ Saved 168 matches to raw_eliteserien_results_2026

# Ingest FotMob match report events

In [4]:
def save_fotmob_events_for_season(
    season: tuple[int, int | None],
    db_path: Path,
    delay_seconds: float = 2.0,
) -> None:
    """Save one row per FotMob report event to raw_fotmob_events_<year>."""
    year = season[1] or season[0]
    table_name = f"raw_fotmob_events_{year}"

    matches = scrape_fotmob_eliteserien_results_for_seasons(
        [season],
        delay_seconds=delay_seconds,
    )
    event_rows = []
    for match in matches:
        for event in match.get("report", []):
            event_time = event.get("time") or {}
            event_rows.append(
                {
                    "season": year,
                    "date": match["date"],
                    "matchday": match["matchday"],
                    "home_team": match["home_team"],
                    "away_team": match["away_team"],
                    "result": match["result"],
                    "match_id": match["match_id"],
                    "report_url": match["report_url"],
                    "event_time": event_time.get("main"),
                    "added_time": event_time.get("added"),
                    "event_type": event.get("type"),
                    "event_title": event.get("title"),
                    "text": event["text"],
                }
            )

    if not event_rows:
        print(f"No FotMob report events returned for season {season}; skipping.")
        return

    df = pl.DataFrame(event_rows).with_columns(
        pl.lit(datetime.now()).alias("ingested_at")
    )

    with duckdb.connect(str(db_path)) as connection:
        connection.register("new_data", df)
        connection.execute(
            f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM new_data"
        )

    print(f"Saved {len(event_rows)} FotMob events to {table_name}")



season_events = [
    #(2020, 2021),
    #(2021, 2022),
    (2022, 2023),
    #(2023, 2024),
    #(2024, 2025),
    #(2025, 2026),
]

for index, season in enumerate(season_events):
    if index:
        sleep(10)
    try:
        save_fotmob_events_for_season(
            season=season,
            db_path=db_path,
            delay_seconds=0,
        )
    except Exception as error:
        print(f"Skipping FotMob season {season}: {error}")

Saved 25162 FotMob events to raw_fotmob_events_2023

# Ingest goal contributions

In [9]:
def save_eliteserien_goal_contributions_for_season(
    season: tuple[int, int],
    db_path: Path,
    delay_seconds: float = 2.0,
    timeout_seconds: int = 30,
) -> None:
    """Scrape one Eliteserien season and save goal contributions to DuckDB."""
    year = season[1] or season[0]
    table_name = f"raw_eliterserien_goal_contributions_{year}"

    print(f"Starting goal-contribution scraping for season {season}...", flush=True)
    data = scrape_eliteserien_goal_contributions_for_season(
        season=season,
        delay_seconds=delay_seconds,
        timeout_seconds=timeout_seconds,
    )

    if not data:
        print(f"No goal-contribution records returned for season {season}; skipping.")
        return

    df = pl.DataFrame(data).with_columns(pl.lit(datetime.now()).alias("ingested_at"))

    with duckdb.connect(str(db_path)) as connection:
        connection.register("new_data", df)
        connection.execute(
            f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM new_data"
        )

    print(f"Saved {len(data)} goal-contribution rows to {table_name}")


season_goal_contributions = [
    (2020, 2021),
    #(2021, 2022),
    #(2022, 2023),
    #(2023, 2024),
    #(2024, 2025),
    #(2025, 2026),
]

for index, season in enumerate(season_goal_contributions):
    if index:
        sleep(10)
    try:
        save_eliteserien_goal_contributions_for_season(
            season=season,
            db_path=db_path,
            delay_seconds=0,
            timeout_seconds=30,
        )
    except Exception as error:
        print(f"Skipping season {season}: {error}")

Starting goal-contribution scraping for season (2020, 2021)...
Scraping FotMob goals 1/240 | Bodø/Glimt vs Tromsø (2021-05-09)
Scraping FotMob goals 2/240 | Molde vs Kristiansund (2021-05-09)
Scraping FotMob goals 3/240 | Viking vs Brann (2021-05-09)
Scraping FotMob goals 4/240 | Vålerenga vs Rosenborg (2021-05-09)
Scraping FotMob goals 5/240 | Kristiansund vs Bodø/Glimt (2021-05-12)
Scraping FotMob goals 6/240 | Brann vs Vålerenga (2021-05-12)
Scraping FotMob goals 7/240 | Tromsø vs Molde (2021-05-13)
Scraping FotMob goals 8/240 | Rosenborg vs Viking (2021-05-13)
Scraping FotMob goals 9/240 | Sarpsborg 08 vs FK Haugesund (2021-05-16)
Scraping FotMob goals 10/240 | Vålerenga vs Kristiansund (2021-05-16)
Scraping FotMob goals 11/240 | Viking vs Tromsø (2021-05-16)
Scraping FotMob goals 12/240 | Bodø/Glimt vs Rosenborg (2021-05-16)
Scraping FotMob goals 13/240 | Sandefjord vs Mjøndalen (2021-05-16)
Scraping FotMob goals 14/240 | Strømsgodset vs Lillestrøm (2021-05-16)
Scraping FotMob goals 15/240 | Molde vs Brann (2021-05-16)
Scraping FotMob goals 16/240 | Stabæk vs Odds Ballklubb (2021-05-19)
Scraping FotMob goals 17/240 | Rosenborg vs Brann (2021-05-20)
Scraping FotMob goals 18/240 | Odds Ballklubb vs Sarpsborg 08 (2021-05-24)
Scraping FotMob goals 19/240 | Brann vs Bodø/Glimt (2021-05-24)
Scraping FotMob goals 20/240 | FK Haugesund vs Stabæk (2021-05-24)
Scraping FotMob goals 21/240 | Kristiansund vs Strømsgodset (2021-05-24)
Scraping FotMob goals 22/240 | Lillestrøm vs Viking (2021-05-24)
Scraping FotMob goals 23/240 | Mjøndalen vs Vålerenga (2021-05-24)
Scraping FotMob goals 24/240 | Tromsø vs Sandefjord (2021-05-24)
Scraping FotMob goals 25/240 | Rosenborg vs Molde (2021-05-24)
Scraping FotMob goals 26/240 | Bodø/Glimt vs FK Haugesund (2021-05-27)
Scraping FotMob goals 27/240 | Lillestrøm vs Odds Ballklubb (2021-05-27)
Scraping FotMob goals 28/240 | Sandefjord vs Rosenborg (2021-05-27)
Scraping FotMob goals 29/240 | Sarpsborg 08 vs Kristiansund (2021-05-27)
Scraping FotMob goals 30/240 | Stabæk vs Brann (2021-05-27)
Scraping FotMob goals 31/240 | Strømsgodset vs Tromsø (2021-05-27)
Scraping FotMob goals 32/240 | Viking vs Mjøndalen (2021-05-27)
Scraping FotMob goals 33/240 | Molde vs Vålerenga (2021-05-27)
Scraping FotMob goals 34/240 | Mjøndalen vs Molde (2021-05-30)
Scraping FotMob goals 35/240 | Brann vs Strømsgodset (2021-05-30)
Scraping FotMob goals 36/240 | Kristiansund vs Lillestrøm (2021-05-30)
Scraping FotMob goals 37/240 | Odds Ballklubb vs Bodø/Glimt (2021-05-30)
Scraping FotMob goals 38/240 | Rosenborg vs Stabæk (2021-05-30)
Scraping FotMob goals 39/240 | Tromsø vs Sarpsborg 08 (2021-05-30)
Scraping FotMob goals 40/240 | Vålerenga vs Sandefjord (2021-05-30)
Scraping FotMob goals 41/240 | FK Haugesund vs Viking (2021-05-30)
Scraping FotMob goals 42/240 | Kristiansund vs Odds Ballklubb (2021-06-12)
Scraping FotMob goals 43/240 | Sandefjord vs Molde (2021-06-12)
Scraping FotMob goals 44/240 | Bodø/Glimt vs Mjøndalen (2021-06-13)
Scraping FotMob goals 45/240 | Lillestrøm vs FK Haugesund (2021-06-13)
Scraping FotMob goals 46/240 | Sarpsborg 08 vs Brann (2021-06-13)
Scraping FotMob goals 47/240 | Strømsgodset vs Rosenborg (2021-06-13)
Scraping FotMob goals 48/240 | Viking vs Vålerenga (2021-06-13)
Scraping FotMob goals 49/240 | Stabæk vs Tromsø (2021-06-14)
Scraping FotMob goals 50/240 | Bodø/Glimt vs Strømsgodset (2021-06-16)
Scraping FotMob goals 51/240 | Molde vs Sarpsborg 08 (2021-06-16)
Scraping FotMob goals 52/240 | Vålerenga vs Odds Ballklubb (2021-06-16)
Scraping FotMob goals 53/240 | Sandefjord vs Viking (2021-06-19)
Scraping FotMob goals 54/240 | Mjøndalen vs Strømsgodset (2021-06-20)
Scraping FotMob goals 55/240 | Brann vs Odds Ballklubb (2021-06-20)
Scraping FotMob goals 56/240 | FK Haugesund vs Kristiansund (2021-06-20)
Scraping FotMob goals 57/240 | Molde vs Stabæk (2021-06-20)
Scraping FotMob goals 58/240 | Rosenborg vs Sarpsborg 08 (2021-06-20)
Scraping FotMob goals 59/240 | Tromsø vs Lillestrøm (2021-06-20)
Scraping FotMob goals 60/240 | Vålerenga vs Bodø/Glimt (2021-06-20)
Scraping FotMob goals 61/240 | Bodø/Glimt vs Molde (2021-06-24)
Scraping FotMob goals 62/240 | FK Haugesund vs Brann (2021-06-24)
Scraping FotMob goals 63/240 | Kristiansund vs Mjøndalen (2021-06-24)
Scraping FotMob goals 64/240 | Odds Ballklubb vs Tromsø (2021-06-24)
Scraping FotMob goals 65/240 | Strømsgodset vs Sandefjord (2021-06-24)
Scraping FotMob goals 66/240 | Stabæk vs Vålerenga (2021-06-24)
Scraping FotMob goals 67/240 | Sarpsborg 08 vs Viking (2021-06-25)
Scraping FotMob goals 68/240 | Lillestrøm vs Rosenborg (2021-06-25)
Scraping FotMob goals 69/240 | Bodø/Glimt vs Stabæk (2021-06-27)
Scraping FotMob goals 70/240 | Molde vs Strømsgodset (2021-06-30)
Scraping FotMob goals 71/240 | Rosenborg vs FK Haugesund (2021-06-30)
Scraping FotMob goals 72/240 | Sandefjord vs Bodø/Glimt (2021-06-30)
Scraping FotMob goals 73/240 | Tromsø vs Kristiansund (2021-06-30)
Scraping FotMob goals 74/240 | Viking vs Stabæk (2021-06-30)
Scraping FotMob goals 75/240 | Brann vs Lillestrøm (2021-06-30)
Scraping FotMob goals 76/240 | Mjøndalen vs Odds Ballklubb (2021-07-01)
Scraping FotMob goals 77/240 | Vålerenga vs Sarpsborg 08 (2021-07-01)
Scraping FotMob goals 78/240 | Bodø/Glimt vs Viking (2021-07-03)
Scraping FotMob goals 79/240 | Stabæk vs Sandefjord (2021-07-04)
Scraping FotMob goals 80/240 | FK Haugesund vs Tromsø (2021-07-04)
Scraping FotMob goals 81/240 | Lillestrøm vs Mjøndalen (2021-07-04)
Scraping FotMob goals 82/240 | Odds Ballklubb vs Rosenborg (2021-07-04)
Scraping FotMob goals 83/240 | Sarpsborg 08 vs Molde (2021-07-04)
Scraping FotMob goals 84/240 | Strømsgodset vs Vålerenga (2021-07-04)
Scraping FotMob goals 85/240 | Kristiansund vs Brann (2021-07-05)
Scraping FotMob goals 86/240 | Mjøndalen vs FK Haugesund (2021-07-10)
Scraping FotMob goals 87/240 | Rosenborg vs Kristiansund (2021-07-10)
Scraping FotMob goals 88/240 | Sandefjord vs Sarpsborg 08 (2021-07-10)
Scraping FotMob goals 89/240 | Viking vs Strømsgodset (2021-07-10)
Scraping FotMob goals 90/240 | Brann vs Tromsø (2021-07-10)
Scraping FotMob goals 91/240 | Vålerenga vs Lillestrøm (2021-07-11)
Scraping FotMob goals 92/240 | Molde vs Odds Ballklubb (2021-07-11)
Scraping FotMob goals 93/240 | Odds Ballklubb vs Viking (2021-07-17)
Scraping FotMob goals 94/240 | Sarpsborg 08 vs Bodø/Glimt (2021-07-17)
Scraping FotMob goals 95/240 | Brann vs Mjøndalen (2021-07-18)
Scraping FotMob goals 96/240 | FK Haugesund vs Vålerenga (2021-07-18)
Scraping FotMob goals 97/240 | Kristiansund vs Sandefjord (2021-07-18)
Scraping FotMob goals 98/240 | Lillestrøm vs Molde (2021-07-18)
Scraping FotMob goals 99/240 | Tromsø vs Rosenborg (2021-07-18)
Scraping FotMob goals 100/240 | Strømsgodset vs Stabæk (2021-07-18)
Scraping FotMob goals 101/240 | Sandefjord vs FK Haugesund (2021-07-21)
Scraping FotMob goals 102/240 | Sarpsborg 08 vs Mjøndalen (2021-07-21)
Scraping FotMob goals 103/240 | Stabæk vs Lillestrøm (2021-07-21)
Scraping FotMob goals 104/240 | Strømsgodset vs Odds Ballklubb (2021-07-21)
Scraping FotMob goals 105/240 | FK Haugesund vs Strømsgodset (2021-07-28)
Scraping FotMob goals 106/240 | Lillestrøm vs Sarpsborg 08 (2021-07-28)
Scraping FotMob goals 107/240 | Mjøndalen vs Stabæk (2021-07-28)
Scraping FotMob goals 108/240 | Odds Ballklubb vs Sandefjord (2021-07-28)
Scraping FotMob goals 109/240 | Mjøndalen vs Tromsø (2021-08-08)
Scraping FotMob goals 110/240 | Molde vs FK Haugesund (2021-08-08)
Scraping FotMob goals 111/240 | Sandefjord vs Lillestrøm (2021-08-08)
Scraping FotMob goals 112/240 | Viking vs Kristiansund (2021-08-08)
Scraping FotMob goals 113/240 | Stabæk vs Sarpsborg 08 (2021-08-08)
Scraping FotMob goals 114/240 | Kristiansund vs Stabæk (2021-08-14)
Scraping FotMob goals 115/240 | Sarpsborg 08 vs Strømsgodset (2021-08-14)
Scraping FotMob goals 116/240 | Lillestrøm vs Bodø/Glimt (2021-08-15)
Scraping FotMob goals 117/240 | Mjøndalen vs Rosenborg (2021-08-15)
Scraping FotMob goals 118/240 | Odds Ballklubb vs FK Haugesund (2021-08-15)
Scraping FotMob goals 119/240 | Tromsø vs Vålerenga (2021-08-15)
Scraping FotMob goals 120/240 | Viking vs Molde (2021-08-15)
Scraping FotMob goals 121/240 | Brann vs Sandefjord (2021-08-15)
Scraping FotMob goals 122/240 | Stabæk vs Mjøndalen (2021-08-21)
Scraping FotMob goals 123/240 | Strømsgodset vs Brann (2021-08-21)
Scraping FotMob goals 124/240 | Bodø/Glimt vs Kristiansund (2021-08-22)
Scraping FotMob goals 125/240 | FK Haugesund vs Lillestrøm (2021-08-22)
Scraping FotMob goals 126/240 | Sandefjord vs Tromsø (2021-08-22)
Scraping FotMob goals 127/240 | Vålerenga vs Viking (2021-08-22)
Scraping FotMob goals 128/240 | Rosenborg vs Odds Ballklubb (2021-08-22)
Scraping FotMob goals 129/240 | Mjøndalen vs Lillestrøm (2021-08-28)
Scraping FotMob goals 130/240 | Brann vs FK Haugesund (2021-08-28)
Scraping FotMob goals 131/240 | Kristiansund vs Molde (2021-08-29)
Scraping FotMob goals 132/240 | Odds Ballklubb vs Strømsgodset (2021-08-29)
Scraping FotMob goals 133/240 | Sarpsborg 08 vs Sandefjord (2021-08-29)
Scraping FotMob goals 134/240 | Tromsø vs Bodø/Glimt (2021-08-29)
Scraping FotMob goals 135/240 | Viking vs Rosenborg (2021-08-29)
Scraping FotMob goals 136/240 | Vålerenga vs Stabæk (2021-08-29)
Scraping FotMob goals 137/240 | Lillestrøm vs Brann (2021-09-11)
Scraping FotMob goals 138/240 | Stabæk vs Viking (2021-09-11)
Scraping FotMob goals 139/240 | Bodø/Glimt vs Odds Ballklubb (2021-09-12)
Scraping FotMob goals 140/240 | FK Haugesund vs Sarpsborg 08 (2021-09-12)
Scraping FotMob goals 141/240 | Molde vs Mjøndalen (2021-09-12)
Scraping FotMob goals 142/240 | Sandefjord vs Vålerenga (2021-09-12)
Scraping FotMob goals 143/240 | Strømsgodset vs Kristiansund (2021-09-12)
Scraping FotMob goals 144/240 | Rosenborg vs Tromsø (2021-09-12)
Scraping FotMob goals 145/240 | Kristiansund vs FK Haugesund (2021-09-18)
Scraping FotMob goals 146/240 | Odds Ballklubb vs Lillestrøm (2021-09-18)
Scraping FotMob goals 147/240 | Mjøndalen vs Sandefjord (2021-09-19)
Scraping FotMob goals 148/240 | Sarpsborg 08 vs Rosenborg (2021-09-19)
Scraping FotMob goals 149/240 | Vålerenga vs Molde (2021-09-19)
Scraping FotMob goals 150/240 | Viking vs Bodø/Glimt (2021-09-19)
Scraping FotMob goals 151/240 | Tromsø vs Brann (2021-09-19)
Scraping FotMob goals 152/240 | Lillestrøm vs Tromsø (2021-09-25)
Scraping FotMob goals 153/240 | Strømsgodset vs Sarpsborg 08 (2021-09-25)
Scraping FotMob goals 154/240 | Brann vs Kristiansund (2021-09-26)
Scraping FotMob goals 155/240 | FK Haugesund vs Odds Ballklubb (2021-09-26)
Scraping FotMob goals 156/240 | Molde vs Viking (2021-09-26)
Scraping FotMob goals 157/240 | Rosenborg vs Mjøndalen (2021-09-26)
Scraping FotMob goals 158/240 | Sandefjord vs Stabæk (2021-09-26)
Scraping FotMob goals 159/240 | Bodø/Glimt vs Vålerenga (2021-09-26)
Scraping FotMob goals 160/240 | Stabæk vs Strømsgodset (2021-09-29)
Scraping FotMob goals 161/240 | Sarpsborg 08 vs Lillestrøm (2021-10-02)
Scraping FotMob goals 162/240 | Viking vs Sandefjord (2021-10-02)
Scraping FotMob goals 163/240 | Mjøndalen vs Brann (2021-10-03)
Scraping FotMob goals 164/240 | Odds Ballklubb vs Molde (2021-10-03)
Scraping FotMob goals 165/240 | Stabæk vs Bodø/Glimt (2021-10-03)
Scraping FotMob goals 166/240 | Tromsø vs FK Haugesund (2021-10-03)
Scraping FotMob goals 167/240 | Vålerenga vs Strømsgodset (2021-10-03)
Scraping FotMob goals 168/240 | Kristiansund vs Rosenborg (2021-10-03)
Scraping FotMob goals 169/240 | Lillestrøm vs Kristiansund (2021-10-16)
Scraping FotMob goals 170/240 | Molde vs Tromsø (2021-10-16)
Scraping FotMob goals 171/240 | Bodø/Glimt vs Sarpsborg 08 (2021-10-17)
Scraping FotMob goals 172/240 | Brann vs Stabæk (2021-10-17)
Scraping FotMob goals 173/240 | FK Haugesund vs Mjøndalen (2021-10-17)
Scraping FotMob goals 174/240 | Sandefjord vs Odds Ballklubb (2021-10-17)
Scraping FotMob goals 175/240 | Strømsgodset vs Viking (2021-10-17)
Scraping FotMob goals 176/240 | Rosenborg vs Vålerenga (2021-10-17)
Scraping FotMob goals 177/240 | Viking vs Lillestrøm (2021-10-23)
Scraping FotMob goals 178/240 | Stabæk vs Molde (2021-10-23)
Scraping FotMob goals 179/240 | Kristiansund vs Sarpsborg 08 (2021-10-24)
Scraping FotMob goals 180/240 | Rosenborg vs Sandefjord (2021-10-24)
Scraping FotMob goals 181/240 | Strømsgodset vs Bodø/Glimt (2021-10-24)
Scraping FotMob goals 182/240 | Tromsø vs Mjøndalen (2021-10-24)
Scraping FotMob goals 183/240 | Vålerenga vs FK Haugesund (2021-10-24)
Scraping FotMob goals 184/240 | Odds Ballklubb vs Brann (2021-10-24)
Scraping FotMob goals 185/240 | FK Haugesund vs Rosenborg (2021-10-27)
Scraping FotMob goals 186/240 | Lillestrøm vs Stabæk (2021-10-27)
Scraping FotMob goals 187/240 | Mjøndalen vs Kristiansund (2021-10-27)
Scraping FotMob goals 188/240 | Sandefjord vs Strømsgodset (2021-10-27)
Scraping FotMob goals 189/240 | Tromsø vs Odds Ballklubb (2021-10-27)
Scraping FotMob goals 190/240 | Molde vs Bodø/Glimt (2021-10-27)
Scraping FotMob goals 191/240 | Brann vs Viking (2021-10-28)
Scraping FotMob goals 192/240 | Sarpsborg 08 vs Vålerenga (2021-10-28)
Scraping FotMob goals 193/240 | Kristiansund vs Tromsø (2021-10-30)
Scraping FotMob goals 194/240 | Rosenborg vs Lillestrøm (2021-10-30)
Scraping FotMob goals 195/240 | Bodø/Glimt vs Sandefjord (2021-10-31)
Scraping FotMob goals 196/240 | Odds Ballklubb vs Mjøndalen (2021-10-31)
Scraping FotMob goals 197/240 | Stabæk vs FK Haugesund (2021-10-31)
Scraping FotMob goals 198/240 | Strømsgodset vs Molde (2021-10-31)
Scraping FotMob goals 199/240 | Viking vs Sarpsborg 08 (2021-10-31)
Scraping FotMob goals 200/240 | Vålerenga vs Brann (2021-10-31)
Scraping FotMob goals 201/240 | Brann vs Rosenborg (2021-11-06)
Scraping FotMob goals 202/240 | Sarpsborg 08 vs Stabæk (2021-11-06)
Scraping FotMob goals 203/240 | FK Haugesund vs Bodø/Glimt (2021-11-07)
Scraping FotMob goals 204/240 | Mjøndalen vs Viking (2021-11-07)
Scraping FotMob goals 205/240 | Molde vs Sandefjord (2021-11-07)
Scraping FotMob goals 206/240 | Odds Ballklubb vs Kristiansund (2021-11-07)
Scraping FotMob goals 207/240 | Tromsø vs Strømsgodset (2021-11-07)
Scraping FotMob goals 208/240 | Lillestrøm vs Vålerenga (2021-11-07)
Scraping FotMob goals 209/240 | Strømsgodset vs Mjøndalen (2021-11-20)
Scraping FotMob goals 210/240 | Viking vs FK Haugesund (2021-11-20)
Scraping FotMob goals 211/240 | Bodø/Glimt vs Lillestrøm (2021-11-21)
Scraping FotMob goals 212/240 | Sandefjord vs Brann (2021-11-21)
Scraping FotMob goals 213/240 | Sarpsborg 08 vs Odds Ballklubb (2021-11-21)
Scraping FotMob goals 214/240 | Stabæk vs Kristiansund (2021-11-21)
Scraping FotMob goals 215/240 | Vålerenga vs Tromsø (2021-11-21)
Scraping FotMob goals 216/240 | Molde vs Rosenborg (2021-11-21)
Scraping FotMob goals 217/240 | Lillestrøm vs Strømsgodset (2021-11-27)
Scraping FotMob goals 218/240 | Odds Ballklubb vs Vålerenga (2021-11-27)
Scraping FotMob goals 219/240 | FK Haugesund vs Sandefjord (2021-11-28)
Scraping FotMob goals 220/240 | Kristiansund vs Viking (2021-11-28)
Scraping FotMob goals 221/240 | Mjøndalen vs Sarpsborg 08 (2021-11-28)
Scraping FotMob goals 222/240 | Rosenborg vs Bodø/Glimt (2021-11-28)
Scraping FotMob goals 223/240 | Tromsø vs Stabæk (2021-11-28)
Scraping FotMob goals 224/240 | Brann vs Molde (2021-11-28)
Scraping FotMob goals 225/240 | Bodø/Glimt vs Brann (2021-12-05)
Scraping FotMob goals 226/240 | Molde vs Lillestrøm (2021-12-05)
Scraping FotMob goals 227/240 | Sandefjord vs Kristiansund (2021-12-05)
Scraping FotMob goals 228/240 | Sarpsborg 08 vs Tromsø (2021-12-05)
Scraping FotMob goals 229/240 | Stabæk vs Rosenborg (2021-12-05)
Scraping FotMob goals 230/240 | Strømsgodset vs FK Haugesund (2021-12-05)
Scraping FotMob goals 231/240 | Vålerenga vs Mjøndalen (2021-12-05)
Scraping FotMob goals 232/240 | Viking vs Odds Ballklubb (2021-12-05)
Scraping FotMob goals 233/240 | FK Haugesund vs Molde (2021-12-12)
Scraping FotMob goals 234/240 | Kristiansund vs Vålerenga (2021-12-12)
Scraping FotMob goals 235/240 | Lillestrøm vs Sandefjord (2021-12-12)
Scraping FotMob goals 236/240 | Mjøndalen vs Bodø/Glimt (2021-12-12)
Scraping FotMob goals 237/240 | Odds Ballklubb vs Stabæk (2021-12-12)
Scraping FotMob goals 238/240 | Rosenborg vs Strømsgodset (2021-12-12)
Scraping FotMob goals 239/240 | Tromsø vs Viking (2021-12-12)
Scraping FotMob goals 240/240 | Brann vs Sarpsborg 08 (2021-12-12)
Saved 732 goal-contribution rows to raw_eliterserien_goal_contributions_2021

# Ingest lineups

In [9]:
def save_eliteserien_lineups_for_season(
    season: tuple[int, int],
    db_path: Path,
    delay_seconds: float = 2.0,
    timeout_seconds: int = 30,
) -> None:
    """Scrape one Eliteserien season and save lineups to DuckDB."""
    year = season[1] or season[0]
    table_name = f"raw_eliterserien_lineups_{year}"

    print(f"Starting lineup scraping for season {season}...", flush=True)
    data = scrape_eliteserien_lineups_for_season(
        season=season,
        delay_seconds=delay_seconds,
        timeout_seconds=timeout_seconds,
    )

    if not data:
        print(f"No lineup records returned for season {season}; skipping.")
        return

    df = pl.DataFrame(data).with_columns(pl.lit(datetime.now()).alias("ingested_at"))

    with duckdb.connect(str(db_path)) as connection:
        connection.register("new_data", df)
        connection.execute(
            f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM new_data"
        )

    print(f"Saved {len(data)} lineup rows to {table_name}")


season_goal_contributions = [
    (2020, 2021),
    (2021, 2022),
    #(2022, 2023),
    #(2023, 2024),
    #(2024, 2025),
    #(2025, 2026),
]

for index, season in enumerate(season_goal_contributions):
    if index:
        sleep(10)
    try:
        save_eliteserien_lineups_for_season(
            season=season,
            db_path=db_path,
            delay_seconds=0,
            timeout_seconds=30,
        )
    except Exception as error:
        print(f"Skipping season {season}: {error}", flush=True)

Starting lineup scraping for season (2020, 2021)...
Scraping FotMob lineups 1/240 | Bodø/Glimt vs Tromsø (2021-05-09)
Done 1/240 | players=40
Scraping FotMob lineups 2/240 | Molde vs Kristiansund (2021-05-09)
Done 2/240 | players=40
Scraping FotMob lineups 3/240 | Viking vs Brann (2021-05-09)
Done 3/240 | players=38
Scraping FotMob lineups 4/240 | Vålerenga vs Rosenborg (2021-05-09)
Done 4/240 | players=36
Scraping FotMob lineups 5/240 | Kristiansund vs Bodø/Glimt (2021-05-12)
Done 5/240 | players=39
Scraping FotMob lineups 6/240 | Brann vs Vålerenga (2021-05-12)
Done 6/240 | players=36
Scraping FotMob lineups 7/240 | Tromsø vs Molde (2021-05-13)
Done 7/240 | players=39
Scraping FotMob lineups 8/240 | Rosenborg vs Viking (2021-05-13)
Done 8/240 | players=39
Scraping FotMob lineups 9/240 | Sarpsborg 08 vs FK Haugesund (2021-05-16)
Done 9/240 | players=39
Scraping FotMob lineups 10/240 | Vålerenga vs Kristiansund (2021-05-16)
Done 10/240 | players=38
Scraping FotMob lineups 11/240 | Viking vs Tromsø (2021-05-16)
Done 11/240 | players=39
Scraping FotMob lineups 12/240 | Bodø/Glimt vs Rosenborg (2021-05-16)
Done 12/240 | players=36
Scraping FotMob lineups 13/240 | Sandefjord vs Mjøndalen (2021-05-16)
Done 13/240 | players=40
Scraping FotMob lineups 14/240 | Strømsgodset vs Lillestrøm (2021-05-16)
Done 14/240 | players=39
Scraping FotMob lineups 15/240 | Molde vs Brann (2021-05-16)
Done 15/240 | players=38
Scraping FotMob lineups 16/240 | Stabæk vs Odds Ballklubb (2021-05-19)
Done 16/240 | players=39
Scraping FotMob lineups 17/240 | Rosenborg vs Brann (2021-05-20)
Done 17/240 | players=36
Scraping FotMob lineups 18/240 | Odds Ballklubb vs Sarpsborg 08 (2021-05-24)
Done 18/240 | players=38
Scraping FotMob lineups 19/240 | Brann vs Bodø/Glimt (2021-05-24)
Done 19/240 | players=38
Scraping FotMob lineups 20/240 | FK Haugesund vs Stabæk (2021-05-24)
Done 20/240 | players=39
Scraping FotMob lineups 21/240 | Kristiansund vs Strømsgodset (2021-05-24)
Done 21/240 | players=39
Scraping FotMob lineups 22/240 | Lillestrøm vs Viking (2021-05-24)
Done 22/240 | players=38
Scraping FotMob lineups 23/240 | Mjøndalen vs Vålerenga (2021-05-24)
Done 23/240 | players=38
Scraping FotMob lineups 24/240 | Tromsø vs Sandefjord (2021-05-24)
Done 24/240 | players=40
Scraping FotMob lineups 25/240 | Rosenborg vs Molde (2021-05-24)
Done 25/240 | players=38
Scraping FotMob lineups 26/240 | Bodø/Glimt vs FK Haugesund (2021-05-27)
Done 26/240 | players=39
Scraping FotMob lineups 27/240 | Lillestrøm vs Odds Ballklubb (2021-05-27)
Done 27/240 | players=38
Scraping FotMob lineups 28/240 | Sandefjord vs Rosenborg (2021-05-27)
Done 28/240 | players=39
Scraping FotMob lineups 29/240 | Sarpsborg 08 vs Kristiansund (2021-05-27)
Done 29/240 | players=40
Scraping FotMob lineups 30/240 | Stabæk vs Brann (2021-05-27)
Done 30/240 | players=39
Scraping FotMob lineups 31/240 | Strømsgodset vs Tromsø (2021-05-27)
Done 31/240 | players=38
Scraping FotMob lineups 32/240 | Viking vs Mjøndalen (2021-05-27)
Done 32/240 | players=39
Scraping FotMob lineups 33/240 | Molde vs Vålerenga (2021-05-27)
Done 33/240 | players=39
Scraping FotMob lineups 34/240 | Mjøndalen vs Molde (2021-05-30)
Done 34/240 | players=38
Scraping FotMob lineups 35/240 | Brann vs Strømsgodset (2021-05-30)
Done 35/240 | players=39
Scraping FotMob lineups 36/240 | Kristiansund vs Lillestrøm (2021-05-30)
Done 36/240 | players=40
Scraping FotMob lineups 37/240 | Odds Ballklubb vs Bodø/Glimt (2021-05-30)
Done 37/240 | players=38
Scraping FotMob lineups 38/240 | Rosenborg vs Stabæk (2021-05-30)
Done 38/240 | players=36
Scraping FotMob lineups 39/240 | Tromsø vs Sarpsborg 08 (2021-05-30)
Done 39/240 | players=40
Scraping FotMob lineups 40/240 | Vålerenga vs Sandefjord (2021-05-30)
Done 40/240 | players=39
Scraping FotMob lineups 41/240 | FK Haugesund vs Viking (2021-05-30)
Done 41/240 | players=37
Scraping FotMob lineups 42/240 | Kristiansund vs Odds Ballklubb (2021-06-12)
Done 42/240 | players=39
Scraping FotMob lineups 43/240 | Sandefjord vs Molde (2021-06-12)
Done 43/240 | players=39
Scraping FotMob lineups 44/240 | Bodø/Glimt vs Mjøndalen (2021-06-13)
Done 44/240 | players=37
Scraping FotMob lineups 45/240 | Lillestrøm vs FK Haugesund (2021-06-13)
Done 45/240 | players=37
Scraping FotMob lineups 46/240 | Sarpsborg 08 vs Brann (2021-06-13)
Done 46/240 | players=37
Scraping FotMob lineups 47/240 | Strømsgodset vs Rosenborg (2021-06-13)
Done 47/240 | players=37
Scraping FotMob lineups 48/240 | Viking vs Vålerenga (2021-06-13)
Done 48/240 | players=38
Scraping FotMob lineups 49/240 | Stabæk vs Tromsø (2021-06-14)
Done 49/240 | players=38
Scraping FotMob lineups 50/240 | Bodø/Glimt vs Strømsgodset (2021-06-16)
Done 50/240 | players=37
Scraping FotMob lineups 51/240 | Molde vs Sarpsborg 08 (2021-06-16)
Done 51/240 | players=38
Scraping FotMob lineups 52/240 | Vålerenga vs Odds Ballklubb (2021-06-16)
Done 52/240 | players=40
Scraping FotMob lineups 53/240 | Sandefjord vs Viking (2021-06-19)
Done 53/240 | players=37
Scraping FotMob lineups 54/240 | Mjøndalen vs Strømsgodset (2021-06-20)
Done 54/240 | players=39
Scraping FotMob lineups 55/240 | Brann vs Odds Ballklubb (2021-06-20)
Done 55/240 | players=37
Scraping FotMob lineups 56/240 | FK Haugesund vs Kristiansund (2021-06-20)
Done 56/240 | players=38
Scraping FotMob lineups 57/240 | Molde vs Stabæk (2021-06-20)
Done 57/240 | players=36
Scraping FotMob lineups 58/240 | Rosenborg vs Sarpsborg 08 (2021-06-20)
Done 58/240 | players=40
Scraping FotMob lineups 59/240 | Tromsø vs Lillestrøm (2021-06-20)
Done 59/240 | players=38
Scraping FotMob lineups 60/240 | Vålerenga vs Bodø/Glimt (2021-06-20)
Done 60/240 | players=39
Scraping FotMob lineups 61/240 | Bodø/Glimt vs Molde (2021-06-24)
Done 61/240 | players=38
Scraping FotMob lineups 62/240 | FK Haugesund vs Brann (2021-06-24)
Done 62/240 | players=36
Scraping FotMob lineups 63/240 | Kristiansund vs Mjøndalen (2021-06-24)
Done 63/240 | players=38
Scraping FotMob lineups 64/240 | Odds Ballklubb vs Tromsø (2021-06-24)
Done 64/240 | players=38
Scraping FotMob lineups 65/240 | Strømsgodset vs Sandefjord (2021-06-24)
Done 65/240 | players=40
Scraping FotMob lineups 66/240 | Stabæk vs Vålerenga (2021-06-24)
Done 66/240 | players=38
Scraping FotMob lineups 67/240 | Sarpsborg 08 vs Viking (2021-06-25)
Done 67/240 | players=37
Scraping FotMob lineups 68/240 | Lillestrøm vs Rosenborg (2021-06-25)
Done 68/240 | players=39
Scraping FotMob lineups 69/240 | Bodø/Glimt vs Stabæk (2021-06-27)
Done 69/240 | players=38
Scraping FotMob lineups 70/240 | Molde vs Strømsgodset (2021-06-30)
Done 70/240 | players=36
Scraping FotMob lineups 71/240 | Rosenborg vs FK Haugesund (2021-06-30)
Done 71/240 | players=37
Scraping FotMob lineups 72/240 | Sandefjord vs Bodø/Glimt (2021-06-30)
Done 72/240 | players=38
Scraping FotMob lineups 73/240 | Tromsø vs Kristiansund (2021-06-30)
Done 73/240 | players=38
Scraping FotMob lineups 74/240 | Viking vs Stabæk (2021-06-30)
Done 74/240 | players=39
Scraping FotMob lineups 75/240 | Brann vs Lillestrøm (2021-06-30)
Done 75/240 | players=39
Scraping FotMob lineups 76/240 | Mjøndalen vs Odds Ballklubb (2021-07-01)
Done 76/240 | players=40
Scraping FotMob lineups 77/240 | Vålerenga vs Sarpsborg 08 (2021-07-01)
Done 77/240 | players=38
Scraping FotMob lineups 78/240 | Bodø/Glimt vs Viking (2021-07-03)
Done 78/240 | players=39
Scraping FotMob lineups 79/240 | Stabæk vs Sandefjord (2021-07-04)
Done 79/240 | players=39
Scraping FotMob lineups 80/240 | FK Haugesund vs Tromsø (2021-07-04)
Done 80/240 | players=33
Scraping FotMob lineups 81/240 | Lillestrøm vs Mjøndalen (2021-07-04)
Done 81/240 | players=40
Scraping FotMob lineups 82/240 | Odds Ballklubb vs Rosenborg (2021-07-04)
Done 82/240 | players=37
Scraping FotMob lineups 83/240 | Sarpsborg 08 vs Molde (2021-07-04)
Done 83/240 | players=38
Scraping FotMob lineups 84/240 | Strømsgodset vs Vålerenga (2021-07-04)
Done 84/240 | players=39
Scraping FotMob lineups 85/240 | Kristiansund vs Brann (2021-07-05)
Done 85/240 | players=38
Scraping FotMob lineups 86/240 | Mjøndalen vs FK Haugesund (2021-07-10)
Done 86/240 | players=38
Scraping FotMob lineups 87/240 | Rosenborg vs Kristiansund (2021-07-10)
Done 87/240 | players=38
Scraping FotMob lineups 88/240 | Sandefjord vs Sarpsborg 08 (2021-07-10)
Done 88/240 | players=40
Scraping FotMob lineups 89/240 | Viking vs Strømsgodset (2021-07-10)
Done 89/240 | players=37
Scraping FotMob lineups 90/240 | Brann vs Tromsø (2021-07-10)
Done 90/240 | players=37
Scraping FotMob lineups 91/240 | Vålerenga vs Lillestrøm (2021-07-11)
Done 91/240 | players=40
Scraping FotMob lineups 92/240 | Molde vs Odds Ballklubb (2021-07-11)
Done 92/240 | players=35
Scraping FotMob lineups 93/240 | Odds Ballklubb vs Viking (2021-07-17)
Done 93/240 | players=38
Scraping FotMob lineups 94/240 | Sarpsborg 08 vs Bodø/Glimt (2021-07-17)
Done 94/240 | players=40
Scraping FotMob lineups 95/240 | Brann vs Mjøndalen (2021-07-18)
Done 95/240 | players=36
Scraping FotMob lineups 96/240 | FK Haugesund vs Vålerenga (2021-07-18)
Done 96/240 | players=38
Scraping FotMob lineups 97/240 | Kristiansund vs Sandefjord (2021-07-18)
Done 97/240 | players=38
Scraping FotMob lineups 98/240 | Lillestrøm vs Molde (2021-07-18)
Done 98/240 | players=37
Scraping FotMob lineups 99/240 | Tromsø vs Rosenborg (2021-07-18)
Done 99/240 | players=37
Scraping FotMob lineups 100/240 | Strømsgodset vs Stabæk (2021-07-18)
Done 100/240 | players=40
Scraping FotMob lineups 101/240 | Sandefjord vs FK Haugesund (2021-07-21)
Done 101/240 | players=36
Scraping FotMob lineups 102/240 | Sarpsborg 08 vs Mjøndalen (2021-07-21)
Done 102/240 | players=40
Scraping FotMob lineups 103/240 | Stabæk vs Lillestrøm (2021-07-21)
Done 103/240 | players=40
Scraping FotMob lineups 104/240 | Strømsgodset vs Odds Ballklubb (2021-07-21)
Done 104/240 | players=38
Scraping FotMob lineups 105/240 | FK Haugesund vs Strømsgodset (2021-07-28)
Done 105/240 | players=36
Scraping FotMob lineups 106/240 | Lillestrøm vs Sarpsborg 08 (2021-07-28)
Done 106/240 | players=40
Scraping FotMob lineups 107/240 | Mjøndalen vs Stabæk (2021-07-28)
Done 107/240 | players=40
Scraping FotMob lineups 108/240 | Odds Ballklubb vs Sandefjord (2021-07-28)
Done 108/240 | players=40
Scraping FotMob lineups 109/240 | Mjøndalen vs Tromsø (2021-08-08)
Done 109/240 | players=39
Scraping FotMob lineups 110/240 | Molde vs FK Haugesund (2021-08-08)
Done 110/240 | players=36
Scraping FotMob lineups 111/240 | Sandefjord vs Lillestrøm (2021-08-08)
Done 111/240 | players=40
Scraping FotMob lineups 112/240 | Viking vs Kristiansund (2021-08-08)
Done 112/240 | players=37
Scraping FotMob lineups 113/240 | Stabæk vs Sarpsborg 08 (2021-08-08)
Done 113/240 | players=40
Scraping FotMob lineups 114/240 | Kristiansund vs Stabæk (2021-08-14)
Done 114/240 | players=38
Scraping FotMob lineups 115/240 | Sarpsborg 08 vs Strømsgodset (2021-08-14)
Done 115/240 | players=38
Scraping FotMob lineups 116/240 | Lillestrøm vs Bodø/Glimt (2021-08-15)
Done 116/240 | players=40
Scraping FotMob lineups 117/240 | Mjøndalen vs Rosenborg (2021-08-15)
Done 117/240 | players=38
Scraping FotMob lineups 118/240 | Odds Ballklubb vs FK Haugesund (2021-08-15)
Done 118/240 | players=37
Scraping FotMob lineups 119/240 | Tromsø vs Vålerenga (2021-08-15)
Done 119/240 | players=39
Scraping FotMob lineups 120/240 | Viking vs Molde (2021-08-15)
Done 120/240 | players=37
Scraping FotMob lineups 121/240 | Brann vs Sandefjord (2021-08-15)
Done 121/240 | players=38
Scraping FotMob lineups 122/240 | Stabæk vs Mjøndalen (2021-08-21)
Done 122/240 | players=40
Scraping FotMob lineups 123/240 | Strømsgodset vs Brann (2021-08-21)
Done 123/240 | players=38
Scraping FotMob lineups 124/240 | Bodø/Glimt vs Kristiansund (2021-08-22)
Done 124/240 | players=38
Scraping FotMob lineups 125/240 | FK Haugesund vs Lillestrøm (2021-08-22)
Done 125/240 | players=38
Scraping FotMob lineups 126/240 | Sandefjord vs Tromsø (2021-08-22)
Done 126/240 | players=37
Scraping FotMob lineups 127/240 | Vålerenga vs Viking (2021-08-22)
Done 127/240 | players=38
Scraping FotMob lineups 128/240 | Rosenborg vs Odds Ballklubb (2021-08-22)
Done 128/240 | players=38
Scraping FotMob lineups 129/240 | Mjøndalen vs Lillestrøm (2021-08-28)
Done 129/240 | players=40
Scraping FotMob lineups 130/240 | Brann vs FK Haugesund (2021-08-28)
Done 130/240 | players=37
Scraping FotMob lineups 131/240 | Kristiansund vs Molde (2021-08-29)
Done 131/240 | players=39
Scraping FotMob lineups 132/240 | Odds Ballklubb vs Strømsgodset (2021-08-29)
Done 132/240 | players=38
Scraping FotMob lineups 133/240 | Sarpsborg 08 vs Sandefjord (2021-08-29)
Done 133/240 | players=38
Scraping FotMob lineups 134/240 | Tromsø vs Bodø/Glimt (2021-08-29)
Done 134/240 | players=40
Scraping FotMob lineups 135/240 | Viking vs Rosenborg (2021-08-29)
Done 135/240 | players=38
Scraping FotMob lineups 136/240 | Vålerenga vs Stabæk (2021-08-29)
Done 136/240 | players=38
Scraping FotMob lineups 137/240 | Lillestrøm vs Brann (2021-09-11)
Done 137/240 | players=38
Scraping FotMob lineups 138/240 | Stabæk vs Viking (2021-09-11)
Done 138/240 | players=38
Scraping FotMob lineups 139/240 | Bodø/Glimt vs Odds Ballklubb (2021-09-12)
Done 139/240 | players=39
Scraping FotMob lineups 140/240 | FK Haugesund vs Sarpsborg 08 (2021-09-12)
Done 140/240 | players=38
Scraping FotMob lineups 141/240 | Molde vs Mjøndalen (2021-09-12)
Done 141/240 | players=37
Scraping FotMob lineups 142/240 | Sandefjord vs Vålerenga (2021-09-12)
Done 142/240 | players=38
Scraping FotMob lineups 143/240 | Strømsgodset vs Kristiansund (2021-09-12)
Done 143/240 | players=38
Scraping FotMob lineups 144/240 | Rosenborg vs Tromsø (2021-09-12)
Done 144/240 | players=37
Scraping FotMob lineups 145/240 | Kristiansund vs FK Haugesund (2021-09-18)
Done 145/240 | players=37
Scraping FotMob lineups 146/240 | Odds Ballklubb vs Lillestrøm (2021-09-18)
Done 146/240 | players=39
Scraping FotMob lineups 147/240 | Mjøndalen vs Sandefjord (2021-09-19)
Done 147/240 | players=39
Scraping FotMob lineups 148/240 | Sarpsborg 08 vs Rosenborg (2021-09-19)
Done 148/240 | players=37
Scraping FotMob lineups 149/240 | Vålerenga vs Molde (2021-09-19)
Done 149/240 | players=38
Scraping FotMob lineups 150/240 | Viking vs Bodø/Glimt (2021-09-19)
Done 150/240 | players=40
Scraping FotMob lineups 151/240 | Tromsø vs Brann (2021-09-19)
Done 151/240 | players=36
Scraping FotMob lineups 152/240 | Lillestrøm vs Tromsø (2021-09-25)
Done 152/240 | players=38
Scraping FotMob lineups 153/240 | Strømsgodset vs Sarpsborg 08 (2021-09-25)
Done 153/240 | players=39
Scraping FotMob lineups 154/240 | Brann vs Kristiansund (2021-09-26)
Done 154/240 | players=40
Scraping FotMob lineups 155/240 | FK Haugesund vs Odds Ballklubb (2021-09-26)
Done 155/240 | players=34
Scraping FotMob lineups 156/240 | Molde vs Viking (2021-09-26)
Done 156/240 | players=36
Scraping FotMob lineups 157/240 | Rosenborg vs Mjøndalen (2021-09-26)
Done 157/240 | players=40
Scraping FotMob lineups 158/240 | Sandefjord vs Stabæk (2021-09-26)
Done 158/240 | players=40
Scraping FotMob lineups 159/240 | Bodø/Glimt vs Vålerenga (2021-09-26)
Done 159/240 | players=39
Scraping FotMob lineups 160/240 | Stabæk vs Strømsgodset (2021-09-29)
Done 160/240 | players=40
Scraping FotMob lineups 161/240 | Sarpsborg 08 vs Lillestrøm (2021-10-02)
Done 161/240 | players=39
Scraping FotMob lineups 162/240 | Viking vs Sandefjord (2021-10-02)
Done 162/240 | players=40
Scraping FotMob lineups 163/240 | Mjøndalen vs Brann (2021-10-03)
Done 163/240 | players=38
Scraping FotMob lineups 164/240 | Odds Ballklubb vs Molde (2021-10-03)
Done 164/240 | players=37
Scraping FotMob lineups 165/240 | Stabæk vs Bodø/Glimt (2021-10-03)
Done 165/240 | players=39
Scraping FotMob lineups 166/240 | Tromsø vs FK Haugesund (2021-10-03)
Done 166/240 | players=35
Scraping FotMob lineups 167/240 | Vålerenga vs Strømsgodset (2021-10-03)
Done 167/240 | players=40
Scraping FotMob lineups 168/240 | Kristiansund vs Rosenborg (2021-10-03)
Done 168/240 | players=37
Scraping FotMob lineups 169/240 | Lillestrøm vs Kristiansund (2021-10-16)
Done 169/240 | players=38
Scraping FotMob lineups 170/240 | Molde vs Tromsø (2021-10-16)
Done 170/240 | players=37
Scraping FotMob lineups 171/240 | Bodø/Glimt vs Sarpsborg 08 (2021-10-17)
Done 171/240 | players=39
Scraping FotMob lineups 172/240 | Brann vs Stabæk (2021-10-17)
Done 172/240 | players=38
Scraping FotMob lineups 173/240 | FK Haugesund vs Mjøndalen (2021-10-17)
Done 173/240 | players=36
Scraping FotMob lineups 174/240 | Sandefjord vs Odds Ballklubb (2021-10-17)
Done 174/240 | players=40
Scraping FotMob lineups 175/240 | Strømsgodset vs Viking (2021-10-17)
Done 175/240 | players=38
Scraping FotMob lineups 176/240 | Rosenborg vs Vålerenga (2021-10-17)
Done 176/240 | players=38
Scraping FotMob lineups 177/240 | Viking vs Lillestrøm (2021-10-23)
Done 177/240 | players=39
Scraping FotMob lineups 178/240 | Stabæk vs Molde (2021-10-23)
Done 178/240 | players=38
Scraping FotMob lineups 179/240 | Kristiansund vs Sarpsborg 08 (2021-10-24)
Done 179/240 | players=38
Scraping FotMob lineups 180/240 | Rosenborg vs Sandefjord (2021-10-24)
Done 180/240 | players=38
Scraping FotMob lineups 181/240 | Strømsgodset vs Bodø/Glimt (2021-10-24)
Done 181/240 | players=40
Scraping FotMob lineups 182/240 | Tromsø vs Mjøndalen (2021-10-24)
Done 182/240 | players=38
Scraping FotMob lineups 183/240 | Vålerenga vs FK Haugesund (2021-10-24)
Done 183/240 | players=37
Scraping FotMob lineups 184/240 | Odds Ballklubb vs Brann (2021-10-24)
Done 184/240 | players=36
Scraping FotMob lineups 185/240 | FK Haugesund vs Rosenborg (2021-10-27)
Done 185/240 | players=37
Scraping FotMob lineups 186/240 | Lillestrøm vs Stabæk (2021-10-27)
Done 186/240 | players=40
Scraping FotMob lineups 187/240 | Mjøndalen vs Kristiansund (2021-10-27)
Done 187/240 | players=40
Scraping FotMob lineups 188/240 | Sandefjord vs Strømsgodset (2021-10-27)
Done 188/240 | players=40
Scraping FotMob lineups 189/240 | Tromsø vs Odds Ballklubb (2021-10-27)
Done 189/240 | players=40
Scraping FotMob lineups 190/240 | Molde vs Bodø/Glimt (2021-10-27)
Done 190/240 | players=37
Scraping FotMob lineups 191/240 | Brann vs Viking (2021-10-28)
Done 191/240 | players=38
Scraping FotMob lineups 192/240 | Sarpsborg 08 vs Vålerenga (2021-10-28)
Done 192/240 | players=38
Scraping FotMob lineups 193/240 | Kristiansund vs Tromsø (2021-10-30)
Done 193/240 | players=39
Scraping FotMob lineups 194/240 | Rosenborg vs Lillestrøm (2021-10-30)
Done 194/240 | players=40
Scraping FotMob lineups 195/240 | Bodø/Glimt vs Sandefjord (2021-10-31)
Done 195/240 | players=40
Scraping FotMob lineups 196/240 | Odds Ballklubb vs Mjøndalen (2021-10-31)
Done 196/240 | players=40
Scraping FotMob lineups 197/240 | Stabæk vs FK Haugesund (2021-10-31)
Done 197/240 | players=37
Scraping FotMob lineups 198/240 | Strømsgodset vs Molde (2021-10-31)
Done 198/240 | players=38
Scraping FotMob lineups 199/240 | Viking vs Sarpsborg 08 (2021-10-31)
Done 199/240 | players=38
Scraping FotMob lineups 200/240 | Vålerenga vs Brann (2021-10-31)
Done 200/240 | players=39
Scraping FotMob lineups 201/240 | Brann vs Rosenborg (2021-11-06)
Done 201/240 | players=37
Scraping FotMob lineups 202/240 | Sarpsborg 08 vs Stabæk (2021-11-06)
Done 202/240 | players=38
Scraping FotMob lineups 203/240 | FK Haugesund vs Bodø/Glimt (2021-11-07)
Done 203/240 | players=37
Scraping FotMob lineups 204/240 | Mjøndalen vs Viking (2021-11-07)
Done 204/240 | players=39
Scraping FotMob lineups 205/240 | Molde vs Sandefjord (2021-11-07)
Done 205/240 | players=37
Scraping FotMob lineups 206/240 | Odds Ballklubb vs Kristiansund (2021-11-07)
Done 206/240 | players=39
Scraping FotMob lineups 207/240 | Tromsø vs Strømsgodset (2021-11-07)
Done 207/240 | players=37
Scraping FotMob lineups 208/240 | Lillestrøm vs Vålerenga (2021-11-07)
Done 208/240 | players=39
Scraping FotMob lineups 209/240 | Strømsgodset vs Mjøndalen (2021-11-20)
Done 209/240 | players=40

In [12]:
# List all table names
db_path = Path("data/brann.duckdb")
con = duckdb.connect(str(db_path))
table_names = con.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'main'").fetchall()
print("Available tables:")
for table in table_names:
    print(f"  - {table[0]}")
con.close()

Available tables:
  - dim_teams
  - fct_goal_contributions
  - fct_league_standings
  - fct_lineups
  - fct_matches
  - raw_eliterserien_goal_contributions_2021
  - raw_eliterserien_goal_contributions_2022
  - raw_eliterserien_goal_contributions_2023
  - raw_eliterserien_goal_contributions_2024
  - raw_eliterserien_goal_contributions_2025
  - raw_eliterserien_goal_contributions_2026
  - raw_eliterserien_lineups_2021
  - raw_eliterserien_lineups_2022
  - raw_eliterserien_lineups_2023
  - raw_eliterserien_lineups_2024
  - raw_eliterserien_lineups_2025
  - raw_eliterserien_lineups_2026
  - raw_eliteserien_results_2021
  - raw_eliteserien_results_2022
  - raw_eliteserien_results_2023
  - raw_eliteserien_results_2024
  - raw_eliteserien_results_2025
  - raw_eliteserien_results_2026
  - raw_fotmob_events_2023
  - raw_fotmob_events_2024
  - raw_fotmob_events_2025
  - raw_fotmob_events_2026
  - raw_match_statistics_2021
  - raw_match_statistics_2022
  - raw_match_statistics_2023
  - raw_match_statistics_2024
  - raw_match_statistics_2025
  - raw_match_statistics_2026

In [13]:
con = duckdb.connect(str(Path(db_path)))
(
pl
.from_arrow(con.execute("""select * from raw_eliterserien_goal_contributions_2026
union all 
select * from raw_eliterserien_goal_contributions_2025
union all 
select * from raw_eliterserien_goal_contributions_2024
union all 
select * from raw_eliterserien_goal_contributions_2023
union all 
select * from raw_eliterserien_goal_contributions_2022
union all 
select * from raw_eliterserien_goal_contributions_2021

""")
.arrow()
)
        


)

shape: (4_238, 17)
┌────────┬────────────┬──────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ season ┆ date       ┆ matchday ┆ home_team  ┆ … ┆ is_own_goa ┆ report_ur ┆ snapshot_ ┆ ingested_ │
│ ---    ┆ ---        ┆ ---      ┆ ---        ┆   ┆ l          ┆ l         ┆ at        ┆ at        │
│ i64    ┆ date       ┆ i64      ┆ str        ┆   ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│        ┆            ┆          ┆            ┆   ┆ bool       ┆ str       ┆ datetime[ ┆ datetime[ │
│        ┆            ┆          ┆            ┆   ┆            ┆           ┆ μs, Europ ┆ μs]       │
│        ┆            ┆          ┆            ┆   ┆            ┆           ┆ e/Oslo]   ┆           │
╞════════╪════════════╪══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 2026   ┆ 2026-03-14 ┆ 1        ┆ Hamarkamer ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆ atene      ┆   ┆            ┆ ww.fotmob ┆ 8 13:22:4 ┆ 8 13:23:1 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 2.004320  ┆ 9.118911  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2026   ┆ 2026-03-14 ┆ 1        ┆ Hamarkamer ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆ atene      ┆   ┆            ┆ ww.fotmob ┆ 8 13:22:4 ┆ 8 13:23:1 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 2.004320  ┆ 9.118911  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2026   ┆ 2026-03-14 ┆ 1        ┆ Hamarkamer ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆ atene      ┆   ┆            ┆ ww.fotmob ┆ 8 13:22:4 ┆ 8 13:23:1 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 2.004320  ┆ 9.118911  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2026   ┆ 2026-03-14 ┆ 1        ┆ Molde      ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆            ┆   ┆            ┆ ww.fotmob ┆ 8 13:22:4 ┆ 8 13:23:1 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 2.004320  ┆ 9.118911  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2026   ┆ 2026-03-14 ┆ 1        ┆ Molde      ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆            ┆   ┆            ┆ ww.fotmob ┆ 8 13:22:4 ┆ 8 13:23:1 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 2.004320  ┆ 9.118911  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ …      ┆ …          ┆ …        ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 2021   ┆ 2021-12-12 ┆ 30       ┆ Tromsø     ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆            ┆   ┆            ┆ ww.fotmob ┆ 8 13:29:4 ┆ 8 13:30:4 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 8.623911  ┆ 7.702251  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2021   ┆ 2021-12-12 ┆ 30       ┆ Tromsø     ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆            ┆   ┆            ┆ ww.fotmob ┆ 8 13:29:4 ┆ 8 13:30:4 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 8.623911  ┆ 7.702251  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2021   ┆ 2021-12-12 ┆ 30       ┆ Brann      ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆            ┆   ┆            ┆ ww.fotmob ┆ 8 13:29:4 ┆ 8 13:30:4 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 8.623911  ┆ 7.702251  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2021   ┆ 2021-12-12 ┆ 30       ┆ Brann      ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆            ┆   ┆            ┆ ww.fotmob ┆ 8 13:29:4 ┆ 8 13:30:4 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 8.623911  ┆ 7.702251  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
│ 2021   ┆ 2021-12-12 ┆ 30       ┆ Brann      ┆ … ┆ false      ┆ https://w ┆ 2026-10-0 ┆ 2026-10-0 │
│        ┆            ┆          ┆            ┆   ┆            ┆ ww.fotmob ┆ 8 13:29:4 ┆ 8 13:30:4 │
│        ┆            ┆          ┆            ┆   ┆            ┆ .com/matc ┆ 8.623911  ┆ 7.702251  │
│        ┆            ┆          ┆            ┆   ┆            ┆ hes…      ┆ CES…      ┆           │
└────────┴────────────┴──────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [14]:
con = duckdb.connect(str(Path(db_path)))
(
pl
.from_arrow(con.execute("""select * from raw_eliterserien_lineups_2026
union all 
select * from raw_eliterserien_lineups_2025
union all 
select * from raw_eliterserien_lineups_2024
union all 
select * from raw_eliterserien_lineups_2023
union all 
select * from raw_eliterserien_lineups_2022
union all 
select * from raw_eliterserien_lineups_2021

""")
.arrow()
)
        


)

shape: (53_231, 25)
┌────────┬────────────┬──────────┬─────────────┬───┬────────────┬────────┬────────────┬────────────┐
│ season ┆ date       ┆ matchday ┆ home_team   ┆ … ┆ substituti ┆ result ┆ snapshot_a ┆ ingested_a │
│ ---    ┆ ---        ┆ ---      ┆ ---         ┆   ┆ on_partner ┆ ---    ┆ t          ┆ t          │
│ i64    ┆ date       ┆ i64      ┆ str         ┆   ┆ _id        ┆ str    ┆ ---        ┆ ---        │
│        ┆            ┆          ┆             ┆   ┆ ---        ┆        ┆ datetime[μ ┆ datetime[μ │
│        ┆            ┆          ┆             ┆   ┆ i64        ┆        ┆ s, Europe/ ┆ s]         │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ Oslo]      ┆            │
╞════════╪════════════╪══════════╪═════════════╪═══╪════════════╪════════╪════════════╪════════════╡
│ 2026   ┆ 2026-03-14 ┆ 1        ┆ Hamarkamera ┆ … ┆ null       ┆ 2 - 1  ┆ 2026-10-06 ┆ 2026-10-06 │
│        ┆            ┆          ┆ tene        ┆   ┆            ┆        ┆ 11:07:52.7 ┆ 11:08:00.9 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 58386 CES… ┆ 52127      │
│ 2026   ┆ 2026-03-14 ┆ 1        ┆ Hamarkamera ┆ … ┆ null       ┆ 2 - 1  ┆ 2026-10-06 ┆ 2026-10-06 │
│        ┆            ┆          ┆ tene        ┆   ┆            ┆        ┆ 11:07:52.7 ┆ 11:08:00.9 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 58386 CES… ┆ 52127      │
│ 2026   ┆ 2026-03-14 ┆ 1        ┆ Hamarkamera ┆ … ┆ null       ┆ 2 - 1  ┆ 2026-10-06 ┆ 2026-10-06 │
│        ┆            ┆          ┆ tene        ┆   ┆            ┆        ┆ 11:07:52.7 ┆ 11:08:00.9 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 58386 CES… ┆ 52127      │
│ 2026   ┆ 2026-03-14 ┆ 1        ┆ Hamarkamera ┆ … ┆ 662946     ┆ 2 - 1  ┆ 2026-10-06 ┆ 2026-10-06 │
│        ┆            ┆          ┆ tene        ┆   ┆            ┆        ┆ 11:07:52.7 ┆ 11:08:00.9 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 58386 CES… ┆ 52127      │
│ 2026   ┆ 2026-03-14 ┆ 1        ┆ Hamarkamera ┆ … ┆ 536981     ┆ 2 - 1  ┆ 2026-10-06 ┆ 2026-10-06 │
│        ┆            ┆          ┆ tene        ┆   ┆            ┆        ┆ 11:07:52.7 ┆ 11:08:00.9 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 58386 CES… ┆ 52127      │
│ …      ┆ …          ┆ …        ┆ …           ┆ … ┆ …          ┆ …      ┆ …          ┆ …          │
│ 2021   ┆ 2021-12-12 ┆ 30       ┆ Brann       ┆ … ┆ 519786     ┆ 2 - 1  ┆ 2026-10-06 ┆ 2026-10-06 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 11:15:18.4 ┆ 11:16:14.5 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 63858 CES… ┆ 46242      │
│ 2021   ┆ 2021-12-12 ┆ 30       ┆ Brann       ┆ … ┆ 41041      ┆ 2 - 1  ┆ 2026-10-06 ┆ 2026-10-06 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 11:15:18.4 ┆ 11:16:14.5 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 63858 CES… ┆ 46242      │
│ 2021   ┆ 2021-12-12 ┆ 30       ┆ Brann       ┆ … ┆ null       ┆ 2 - 1  ┆ 2026-10-06 ┆ 2026-10-06 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 11:15:18.4 ┆ 11:16:14.5 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 63858 CES… ┆ 46242      │
│ 2021   ┆ 2021-12-12 ┆ 30       ┆ Brann       ┆ … ┆ null       ┆ 2 - 1  ┆ 2026-10-06 ┆ 2026-10-06 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 11:15:18.4 ┆ 11:16:14.5 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 63858 CES… ┆ 46242      │
│ 2021   ┆ 2021-12-12 ┆ 30       ┆ Brann       ┆ … ┆ null       ┆ 2 - 1  ┆ 2026-10-06 ┆ 2026-10-06 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 11:15:18.4 ┆ 11:16:14.5 │
│        ┆            ┆          ┆             ┆   ┆            ┆        ┆ 63858 CES… ┆ 46242      │
└────────┴────────────┴──────────┴─────────────┴───┴────────────┴────────┴────────────┴────────────┘

In [ ]:
con = duckdb.connect(str(Path(db_path)))
(
pl
.from_arrow(con.execute("""select * from raw_fotmob_events_2026

""")
.arrow()
)
.filter(pl.col('home_team').str.contains("Rosenborg"),
        pl.col('away_team').str.contains("Tromsø")
        )
.unnest('event_title')
.filter(pl.col('text').str.contains("Selnæs"))

)

shape: (21, 15)
┌────────┬────────────┬──────────┬───────────┬───┬────────────┬───────────┬────────────┬───────────┐
│ season ┆ date       ┆ matchday ┆ home_team ┆ … ┆ key        ┆ value     ┆ text       ┆ ingested_ │
│ ---    ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---        ┆ ---       ┆ ---        ┆ at        │
│ i64    ┆ date       ┆ i64      ┆ str       ┆   ┆ str        ┆ str       ┆ str        ┆ ---       │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆            ┆ datetime[ │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆            ┆ μs]       │
╞════════╪════════════╪══════════╪═══════════╪═══╪════════════╪═══════════╪════════════╪═══════════╡
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Rosenborg  ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ vinner 5-3 ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ over       ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Tromsø     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ etter en   ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ fantastisk ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ fotballkam ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ p!         ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Rosenborg  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ dominerte  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ alt som    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ var i …    ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Flere sign ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ alinvolver ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ inger fra  ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ hjemmelage ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ t nå.      ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Mortensen, ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Selnæs og  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Soboczynsk ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ i trøkker  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ til i      ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ duellen…   ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Frispark   ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ til        ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Rosenborg, ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ tas av Ole ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Selnæs.    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Heine Åsen ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Larsen     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ vinner     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ duellen på ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ bakerste,  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ men mister ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ …          ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Frispark   ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ til        ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Tromsø,    ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ tas av     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Ruben      ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Yttergård  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Jenssen.   ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Frispark   ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ like over  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ midtbanen. ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Tromsø     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ sender     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ opp…       ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Frispark   ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ til        ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Tromsø,    ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ tas av     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Isak       ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Dahlqvist. ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Selnæs     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ header     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ unna.      ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Dahlqvist  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ skyter så  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ fra 20     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ meter. Re… ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Frispark   ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ til        ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Rosenborg, ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ tas av Ole ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Selnæs.    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Innlegget  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ heades umi ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ ddelbart   ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ ut igjen,  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ og det     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ blir en    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ kje…       ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ owngoal    ┆ Own Goal! ┆ Strålende  ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ forarbeid  ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ av Troy    ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Nyhammer,  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ som drar   ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ seg        ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ nedover    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ venstresid ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ en og      ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ etter      ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ hvert      ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ kommer seg ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ fo…        ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Frispark   ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ til        ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Rosenborg, ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ tas av Ole ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Selnæs.    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Tar        ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ frisparket ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ kort.      ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Rosenborg  ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ herjer på  ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Lerkendal, ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ og leder   ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ fullt      ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ fortjent   ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ 4-0 til    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ pause over ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Tromsø!    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Forrige    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ serierunde ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ …          ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Frispark   ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ til        ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Tromsø,    ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ tas av     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Ruben      ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Yttergård  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Jenssen.   ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Selnæs     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ redder på  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ strek!     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Frisparket ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ slås inn i ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ f…         ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ assist_sin ┆ Assist    ┆ Ole Selnæs ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆ gular      ┆           ┆ med målgiv ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ ende.      ┆ 4.041680  │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ goal       ┆ Goal!     ┆ Witry      ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ banker inn ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ 4-0 fra    ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ bakre      ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ stolpe!    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Selnæs     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ slår       ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ frisparket ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ kort og    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ får ballen ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ umiddelbar ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ t tilbake… ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Frispark   ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ til        ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Rosenborg, ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ tas av Ole ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Selnæs.    ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Heine Åsen ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Larsen     ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ spurter i  ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ press og   ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ jager      ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Selnæs og  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Rosenborg  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ 30-40      ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ meter      ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ hjemover,  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ før        ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Rosenborg  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ r…         ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Frispark   ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ til        ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Rosenborg, ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ tas av Ole ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Selnæs.    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Slår       ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ frisparket ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ kort til   ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Nemcík.    ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Frispark   ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ til        ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Rosenborg, ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ tas av     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Adrian     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Pereira.   ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Tar        ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ frisparket ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ på         ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ midtbanen  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ kort, og   ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Selnæs     ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ klinker b… ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Frispark   ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ til        ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Rosenborg, ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ tas av Ole ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Selnæs.    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Witry      ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ starter    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ inn bak,   ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ og Selnæs  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ leverer en ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ strålende  ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ pas…       ┆           │
│ 2026   ┆ 2026-09-12 ┆ 21       ┆ Rosenborg ┆ … ┆ null       ┆ null      ┆ Frispark   ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ til        ┆ 9 09:54:1 │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ Rosenborg, ┆ 4.041680  │
│        ┆            ┆          ┆           ┆   ┆            ┆           ┆ tas av Ole ┆           │