In [21]:
import importlib
import polars as pl
import polars.selectors as cs
from datetime import datetime
import polars_ds as pds
import requests
import json
import duckdb
from pathlib import Path
from time import sleep
import src.utils as utils

importlib.reload(utils)

from src.utils import (
    scrape_eliteserien_all_xg_for_seasons,
    scrape_eliteserien_results_for_seasons,
    scrape_transfermarkt_goal_contributions,
    scrape_eliteserien_goal_contributions_for_season,
    scrape_eliteserien_lineups_for_season,
    scrape_transfermarkt_lineups,
    scrape_fotmob_eliteserien_results_for_seasons,
    scrape_fotmob_match_report
)

In [7]:
from src.utils import scrape_fotmob_eliteserien_results_for_seasons

matches = scrape_fotmob_eliteserien_results_for_seasons(
    [(2025, 2026)],
    delay_seconds=0,
)

In [9]:
pl.DataFrame(matches)

shape: (168, 11)
┌────────────┬──────────┬────────────┬────────────┬───┬──────────┬────────────┬────────┬───────────┐
│ date       ┆ matchday ┆ home_team  ┆ away_team  ┆ … ┆ match_id ┆ report_url ┆ season ┆ report    │
│ ---        ┆ ---      ┆ ---        ┆ ---        ┆   ┆ ---      ┆ ---        ┆ ---    ┆ ---       │
│ date       ┆ i64      ┆ str        ┆ str        ┆   ┆ str      ┆ str        ┆ i64    ┆ list[stru │
│            ┆          ┆            ┆            ┆   ┆          ┆            ┆        ┆ ct[4]]    │
╞════════════╪══════════╪════════════╪════════════╪═══╪══════════╪════════════╪════════╪═══════════╡
│ 2026-03-14 ┆ 1        ┆ Hamarkamer ┆ Viking     ┆ … ┆ 5104842  ┆ https://ww ┆ 2026   ┆ [{null,"p │
│            ┆          ┆ atene      ┆            ┆   ┆          ┆ w.fotmob.c ┆        ┆ ost_match │
│            ┆          ┆            ┆            ┆   ┆          ┆ om/matches ┆        ┆ summary", │
│            ┆          ┆            ┆            ┆   ┆          ┆ …          ┆        ┆ nu…       │
│ 2026-03-14 ┆ 1        ┆ Molde      ┆ Rosenborg  ┆ … ┆ 5104843  ┆ https://ww ┆ 2026   ┆ [{null,"p │
│            ┆          ┆            ┆            ┆   ┆          ┆ w.fotmob.c ┆        ┆ ost_match │
│            ┆          ┆            ┆            ┆   ┆          ┆ om/matches ┆        ┆ summary", │
│            ┆          ┆            ┆            ┆   ┆          ┆ …          ┆        ┆ nu…       │
│ 2026-03-15 ┆ 1        ┆ Kristiansu ┆ Brann      ┆ … ┆ 5104844  ┆ https://ww ┆ 2026   ┆ [{null,"p │
│            ┆          ┆ nd         ┆            ┆   ┆          ┆ w.fotmob.c ┆        ┆ ost_match │
│            ┆          ┆            ┆            ┆   ┆          ┆ om/matches ┆        ┆ summary", │
│            ┆          ┆            ┆            ┆   ┆          ┆ …          ┆        ┆ nu…       │
│ 2026-03-15 ┆ 1        ┆ Aalesund   ┆ Lillestrøm ┆ … ┆ 5104848  ┆ https://ww ┆ 2026   ┆ [{null,"p │
│            ┆          ┆            ┆            ┆   ┆          ┆ w.fotmob.c ┆        ┆ ost_match │
│            ┆          ┆            ┆            ┆   ┆          ┆ om/matches ┆        ┆ summary", │
│            ┆          ┆            ┆            ┆   ┆          ┆ …          ┆        ┆ nu…       │
│ 2026-03-15 ┆ 1        ┆ KFUM       ┆ Start      ┆ … ┆ 5104845  ┆ https://ww ┆ 2026   ┆ [{null,"p │
│            ┆          ┆            ┆            ┆   ┆          ┆ w.fotmob.c ┆        ┆ ost_match │
│            ┆          ┆            ┆            ┆   ┆          ┆ om/matches ┆        ┆ summary", │
│            ┆          ┆            ┆            ┆   ┆          ┆ …          ┆        ┆ nu…       │
│ …          ┆ …        ┆ …          ┆ …          ┆ … ┆ …        ┆ …          ┆ …      ┆ …         │
│ 2026-09-20 ┆ 22       ┆ Vålerenga  ┆ Fredriksta ┆ … ┆ 5105010  ┆ https://ww ┆ 2026   ┆ [{{"90‎’‎", │
│            ┆          ┆            ┆ d          ┆   ┆          ┆ w.fotmob.c ┆        ┆ "+8"},"co │
│            ┆          ┆            ┆            ┆   ┆          ┆ om/matches ┆        ┆ mment",nu │
│            ┆          ┆            ┆            ┆   ┆          ┆ …          ┆        ┆ l…        │
│ 2026-09-20 ┆ 22       ┆ Sandefjord ┆ Start      ┆ … ┆ 5105014  ┆ https://ww ┆ 2026   ┆ [{null,"p │
│            ┆          ┆            ┆            ┆   ┆          ┆ w.fotmob.c ┆        ┆ ost_match │
│            ┆          ┆            ┆            ┆   ┆          ┆ om/matches ┆        ┆ summary", │
│            ┆          ┆            ┆            ┆   ┆          ┆ …          ┆        ┆ nu…       │
│ 2026-09-20 ┆ 22       ┆ Tromsø     ┆ Hamarkamer ┆ … ┆ 5105012  ┆ https://ww ┆ 2026   ┆ [{null,"p │
│            ┆          ┆            ┆ atene      ┆   ┆          ┆ w.fotmob.c ┆        ┆ ost_match │
│            ┆          ┆            ┆            ┆   ┆          ┆ om/matches ┆        ┆ summary", │
│            ┆          ┆            ┆            ┆   ┆          ┆ …          ┆        ┆ nu…       │
│ 2026-09-20 ┆ 22       ┆ Viking     ┆ Lillestrøm ┆ … ┆ 5105015  ┆ https://ww ┆ 2026   ┆ [{null,"p │
│            ┆          ┆            ┆            ┆   ┆          ┆ w.fotmob.c ┆        ┆ ost_match │
│            ┆          ┆            ┆            ┆   ┆          ┆ om/matches ┆        ┆ summary", │
│            ┆          ┆            ┆            ┆   ┆          ┆ …          ┆        ┆ nu…       │
│ 2026-09-20 ┆ 22       ┆ Brann      ┆ Bodø/Glimt ┆ … ┆ 5105011  ┆ https://ww ┆ 2026   ┆ [{null,"p │
│            ┆          ┆            ┆            ┆   ┆          ┆ w.fotmob.c ┆        ┆ ost_match │
│            ┆          ┆            ┆            ┆   ┆          ┆ om/matches ┆        ┆ summary", │
│            ┆          ┆            ┆            ┆   ┆          ┆ …          ┆        ┆ nu…       │
└────────────┴──────────┴────────────┴────────────┴───┴──────────┴────────────┴────────┴───────────┘

In [11]:
seasons = [
    (2020,2021),
    (2021,2022),
    (2022,2023),
    (2023,2024),
    (2024,2025),
    (2025,2026)
]

db_path = Path("data/brann.duckdb")

# Ingest Eliteserien results

In [10]:
def save_eliteserien_results_for_season(
    season: tuple[int, int | None],
    db_path: Path,
    delay_seconds: float = 0.5,
) -> None:
    """Scrape one Eliteserien season and store it in its own raw_eliteserien_results_<year> table."""
    year = season[1] or season[0]
    table_name = f"raw_eliteserien_results_{year}"

    data = scrape_eliteserien_results_for_seasons([season], delay_seconds=delay_seconds)
    if not data:
        print(f"No records returned for season {season}; skipping.")
        return

    df = pl.DataFrame(data).with_columns(pl.lit(datetime.now()).alias("ingested_at"))

    with duckdb.connect(str(db_path)) as connection:
        connection.register("new_data", df)
        connection.execute(f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM new_data")

    print(f"✓ Saved {len(data)} matches to {table_name}")


# Ingest results season by season so one failing season doesn't block the rest
for season in seasons:
    try:
        save_eliteserien_results_for_season(season, db_path, delay_seconds=0.5)
    except Exception as error:
        print(f"Skipping season {season}: {error}")

✓ Saved 240 matches to raw_eliteserien_results_2021
✓ Saved 240 matches to raw_eliteserien_results_2022
✓ Saved 240 matches to raw_eliteserien_results_2023
✓ Saved 240 matches to raw_eliteserien_results_2024
✓ Saved 240 matches to raw_eliteserien_results_2025
✓ Saved 168 matches to raw_eliteserien_results_2026

# Ingest FotMob match report events

In [14]:
def save_fotmob_events_for_season(
    season: tuple[int, int | None],
    db_path: Path,
    delay_seconds: float = 2.0,
) -> None:
    """Save one row per FotMob report event to raw_fotmob_events_<year>."""
    year = season[1] or season[0]
    table_name = f"raw_fotmob_events_{year}"

    matches = scrape_fotmob_eliteserien_results_for_seasons(
        [season],
        delay_seconds=delay_seconds,
    )
    event_rows = []
    for match in matches:
        for event in match.get("report", []):
            event_time = event.get("time") or {}
            event_rows.append(
                {
                    "season": year,
                    "date": match["date"],
                    "matchday": match["matchday"],
                    "home_team": match["home_team"],
                    "away_team": match["away_team"],
                    "result": match["result"],
                    "match_id": match["match_id"],
                    "report_url": match["report_url"],
                    "event_time": event_time.get("main"),
                    "added_time": event_time.get("added"),
                    "event_type": event.get("type"),
                    "event_title": event.get("title"),
                    "text": event["text"],
                }
            )

    if not event_rows:
        print(f"No FotMob report events returned for season {season}; skipping.")
        return

    df = pl.DataFrame(event_rows).with_columns(
        pl.lit(datetime.now()).alias("ingested_at")
    )

    with duckdb.connect(str(db_path)) as connection:
        connection.register("new_data", df)
        connection.execute(
            f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM new_data"
        )

    print(f"Saved {len(event_rows)} FotMob events to {table_name}")



season_events = [
    #(2020, 2021),
    #(2021, 2022),
    #(2022, 2023),
    (2023, 2024),
    #(2024, 2025),
    #(2025, 2026),
]

for index, season in enumerate(season_events):
    if index:
        sleep(10)
    try:
        save_fotmob_events_for_season(
            season=season,
            db_path=db_path,
            delay_seconds=0,
        )
    except Exception as error:
        print(f"Skipping FotMob season {season}: {error}")

Saved 25771 FotMob events to raw_fotmob_events_2024

# Ingest Eliteserien match statistics

In [20]:
def save_eliteserien_xg_for_season(
    season: tuple[int, int | None],
    db_path: Path,
    delay_seconds: float = 0.01,
    season_delay_seconds: float = 0.1,
    timeout_seconds: int = 30,
) -> None:
    """Scrape one Eliteserien season's xG/stats and store it in its own raw_match_statistics_<year> table."""
    year = season[1] or season[0]
    table_name = f"raw_match_statistics_{year}"

    data = scrape_eliteserien_all_xg_for_seasons(
        [season],
        delay_seconds=delay_seconds,
        season_delay_seconds=season_delay_seconds,
        timeout_seconds=timeout_seconds,
    )
    if not data:
        print(f"No records returned for season {season}; skipping.")
        return

    df = pl.DataFrame(data).with_columns(pl.lit(datetime.now()).alias("ingested_at"))

    with duckdb.connect(str(db_path)) as connection:
        connection.register("new_data", df)
        connection.execute(f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM new_data")

    print(f"✓ Saved {len(data)} matches to {table_name}")


# Ingest xG/stats season by season, waiting 10s between seasons so one failing season doesn't block the rest
for index, season in enumerate(seasons):
    if index:
        sleep(10)
    try:
        save_eliteserien_xg_for_season(season, db_path)
    except Exception as error:
        print(f"Skipping season {season}: {error}")

Fetching xG for season 2021 (ID: 2020)...
✓ Saved 240 matches to raw_match_statistics_2021
Fetching xG for season 2022 (ID: 2021)...
✓ Saved 240 matches to raw_match_statistics_2022
Fetching xG for season 2023 (ID: 2022)...
✓ Saved 240 matches to raw_match_statistics_2023
Fetching xG for season 2024 (ID: 2023)...
✓ Saved 240 matches to raw_match_statistics_2024
Fetching xG for season 2025 (ID: 2024)...
✓ Saved 240 matches to raw_match_statistics_2025
Fetching xG for season 2026 (ID: 2025)...
✓ Saved 168 matches to raw_match_statistics_2026

# Ingest goal contributions

In [4]:
def save_eliteserien_goal_contributions_for_season(
    season: tuple[int, int],
    db_path: Path,
    delay_seconds: float = 2.0,
    timeout_seconds: int = 30,
) -> None:
    """Scrape one Eliteserien season and save goal contributions to DuckDB."""
    year = season[1] or season[0]
    table_name = f"raw_eliterserien_goal_contributions_{year}"

    print(f"Starting goal-contribution scraping for season {season}...", flush=True)
    data = scrape_eliteserien_goal_contributions_for_season(
        season=season,
        delay_seconds=delay_seconds,
        timeout_seconds=timeout_seconds,
    )

    if not data:
        print(f"No goal-contribution records returned for season {season}; skipping.")
        return

    df = pl.DataFrame(data).with_columns(pl.lit(datetime.now()).alias("ingested_at"))

    with duckdb.connect(str(db_path)) as connection:
        connection.register("new_data", df)
        connection.execute(
            f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM new_data"
        )

    print(f"Saved {len(data)} goal-contribution rows to {table_name}")


season_goal_contributions = [
    #(2020, 2021),
    #(2021, 2022),
    #(2022, 2023),
    (2023, 2024),
    #(2024, 2025),
    #(2025, 2026),
]

for index, season in enumerate(season_goal_contributions):
    if index:
        sleep(10)
    try:
        save_eliteserien_goal_contributions_for_season(
            season=season,
            db_path=db_path,
            delay_seconds=0,
            timeout_seconds=30,
        )
    except Exception as error:
        print(f"Skipping season {season}: {error}")

Starting goal-contribution scraping for season (2023, 2024)...
Scraping goals 1/240 | Odd vs Haugesund (2024-03-31)
Scraping goals 2/240 | Fredrikstad FK vs Bodø/Glimt (2024-04-01)
Scraping goals 3/240 | Lillestrøm vs Kristiansund BK (2024-04-01)
Scraping goals 4/240 | Molde FK vs Strømsgodset (2024-04-01)
Scraping goals 5/240 | Rosenborg BK vs Sandefjord (2024-04-01)
Scraping goals 6/240 | Tromsø IL vs SK Brann (2024-04-01)
Scraping goals 7/240 | Viking FK vs Sarpsborg 08 (2024-04-01)
Scraping goals 8/240 | KFUM Oslo vs HamKam (2024-04-02)
Scraping goals 9/240 | Bodø/Glimt vs Viking FK (2024-04-06)
Scraping goals 10/240 | Kristiansund BK vs KFUM Oslo (2024-04-07)
Scraping goals 11/240 | HamKam vs Molde FK (2024-04-07)
Scraping goals 12/240 | Sarpsborg 08 vs Odd (2024-04-07)
Scraping goals 13/240 | Strømsgodset vs Rosenborg BK (2024-04-07)
Scraping goals 14/240 | Haugesund vs Lillestrøm (2024-04-07)
Scraping goals 15/240 | SK Brann vs Fredrikstad FK (2024-04-07)
Scraping goals 16/240 | Fredrikstad FK vs Sarpsborg 08 (2024-04-13)
Scraping goals 17/240 | Viking FK vs SK Brann (2024-04-14)
Scraping goals 18/240 | Tromsø IL vs Haugesund (2024-04-14)
Scraping goals 19/240 | Molde FK vs Kristiansund BK (2024-04-14)
Scraping goals 20/240 | Odd vs Sandefjord (2024-04-14)
Scraping goals 21/240 | Rosenborg BK vs HamKam (2024-04-14)
Scraping goals 22/240 | Lillestrøm vs Bodø/Glimt (2024-04-14)
Scraping goals 23/240 | KFUM Oslo vs Strømsgodset (2024-04-16)
Scraping goals 24/240 | SK Brann vs HamKam (2024-04-17)
Scraping goals 25/240 | Molde FK vs Odd (2024-04-17)
Scraping goals 26/240 | HamKam vs Strømsgodset (2024-04-21)
Scraping goals 27/240 | Sandefjord vs Lillestrøm (2024-04-21)
Scraping goals 28/240 | Sarpsborg 08 vs KFUM Oslo (2024-04-21)
Scraping goals 29/240 | SK Brann vs Odd (2024-04-21)
Scraping goals 30/240 | Viking FK vs Fredrikstad FK (2024-04-21)
Scraping goals 31/240 | Haugesund vs Rosenborg BK (2024-04-21)
Scraping goals 32/240 | Kristiansund BK vs Tromsø IL (2024-04-21)
Scraping goals 33/240 | Bodø/Glimt vs Molde FK (2024-04-21)
Scraping goals 34/240 | Rosenborg BK vs Bodø/Glimt (2024-04-27)
Scraping goals 35/240 | Fredrikstad FK vs Sandefjord (2024-04-28)
Scraping goals 36/240 | Tromsø IL vs Sarpsborg 08 (2024-04-28)
Scraping goals 37/240 | KFUM Oslo vs SK Brann (2024-04-28)
Scraping goals 38/240 | Lillestrøm vs HamKam (2024-04-28)
Scraping goals 39/240 | Molde FK vs Haugesund (2024-04-28)
Scraping goals 40/240 | Strømsgodset vs Kristiansund BK (2024-04-28)
Scraping goals 41/240 | Odd vs Viking FK (2024-04-28)
Scraping goals 42/240 | SK Brann vs Rosenborg BK (2024-05-04)
Scraping goals 43/240 | Haugesund vs KFUM Oslo (2024-05-05)
Scraping goals 44/240 | Kristiansund BK vs HamKam (2024-05-05)
Scraping goals 45/240 | Sarpsborg 08 vs Lillestrøm (2024-05-05)
Scraping goals 46/240 | Odd vs Fredrikstad FK (2024-05-05)
Scraping goals 47/240 | Bodø/Glimt vs Strømsgodset (2024-05-05)
Scraping goals 48/240 | Sandefjord vs Molde FK (2024-05-05)
Scraping goals 49/240 | Viking FK vs Tromsø IL (2024-05-05)
Scraping goals 50/240 | Molde FK vs Rosenborg BK (2024-05-11)
Scraping goals 51/240 | Kristiansund BK vs Bodø/Glimt (2024-05-12)
Scraping goals 52/240 | Strømsgodset vs Viking FK (2024-05-12)
Scraping goals 53/240 | KFUM Oslo vs Fredrikstad FK (2024-05-12)
Scraping goals 54/240 | HamKam vs Haugesund (2024-05-12)
Scraping goals 55/240 | Sandefjord vs Sarpsborg 08 (2024-05-12)
Scraping goals 56/240 | Tromsø IL vs Odd (2024-05-12)
Scraping goals 57/240 | Lillestrøm vs SK Brann (2024-05-12)
Scraping goals 58/240 | SK Brann vs Sandefjord (2024-05-16)
Scraping goals 59/240 | Haugesund vs Kristiansund BK (2024-05-16)
Scraping goals 60/240 | Sarpsborg 08 vs HamKam (2024-05-16)
Scraping goals 61/240 | Viking FK vs Lillestrøm (2024-05-16)
Scraping goals 62/240 | Bodø/Glimt vs Tromsø IL (2024-05-16)
Scraping goals 63/240 | Fredrikstad FK vs Strømsgodset (2024-05-16)
Scraping goals 64/240 | Odd vs Molde FK (2024-05-16)
Scraping goals 65/240 | Rosenborg BK vs KFUM Oslo (2024-05-16)
Scraping goals 66/240 | Kristiansund BK vs SK Brann (2024-05-20)
Scraping goals 67/240 | Sandefjord vs Viking FK (2024-05-20)
Scraping goals 68/240 | Strømsgodset vs Haugesund (2024-05-20)
Scraping goals 69/240 | HamKam vs Bodø/Glimt (2024-05-20)
Scraping goals 70/240 | KFUM Oslo vs Odd (2024-05-20)
Scraping goals 71/240 | Lillestrøm vs Fredrikstad FK (2024-05-20)
Scraping goals 72/240 | Molde FK vs Sarpsborg 08 (2024-05-20)
Scraping goals 73/240 | Tromsø IL vs Rosenborg BK (2024-05-20)
Scraping goals 74/240 | Bodø/Glimt vs KFUM Oslo (2024-05-24)
Scraping goals 75/240 | Fredrikstad FK vs Tromsø IL (2024-05-25)
Scraping goals 76/240 | Odd vs Lillestrøm (2024-05-26)
Scraping goals 77/240 | Sarpsborg 08 vs Strømsgodset (2024-05-26)
Scraping goals 78/240 | Viking FK vs HamKam (2024-05-26)
Scraping goals 79/240 | Haugesund vs Sandefjord (2024-05-26)
Scraping goals 80/240 | Rosenborg BK vs Kristiansund BK (2024-05-26)
Scraping goals 81/240 | SK Brann vs Molde FK (2024-05-26)
Scraping goals 82/240 | Tromsø IL vs Fredrikstad FK (2024-05-29)
Scraping goals 83/240 | SK Brann vs Kristiansund BK (2024-05-29)
Scraping goals 84/240 | Bodø/Glimt vs Sandefjord (2024-05-29)
Scraping goals 85/240 | HamKam vs SK Brann (2024-06-01)
Scraping goals 86/240 | Molde FK vs Viking FK (2024-06-02)
Scraping goals 87/240 | Strømsgodset vs Odd (2024-06-02)
Scraping goals 88/240 | Haugesund vs Bodø/Glimt (2024-06-02)
Scraping goals 89/240 | KFUM Oslo vs Sandefjord (2024-06-02)
Scraping goals 90/240 | Kristiansund BK vs Sarpsborg 08 (2024-06-02)
Scraping goals 91/240 | Tromsø IL vs Lillestrøm (2024-06-02)
Scraping goals 92/240 | Rosenborg BK vs Fredrikstad FK (2024-06-02)
Scraping goals 93/240 | Sandefjord vs HamKam (2024-06-27)
Scraping goals 94/240 | Lillestrøm vs KFUM Oslo (2024-06-27)
Scraping goals 95/240 | SK Brann vs Strømsgodset (2024-06-28)
Scraping goals 96/240 | Sarpsborg 08 vs Bodø/Glimt (2024-06-28)
Scraping goals 97/240 | Odd vs Kristiansund BK (2024-06-28)
Scraping goals 98/240 | Tromsø IL vs Molde FK (2024-06-28)
Scraping goals 99/240 | Viking FK vs Rosenborg BK (2024-06-30)
Scraping goals 100/240 | Sandefjord vs Tromsø IL (2024-07-03)
Scraping goals 101/240 | Bodø/Glimt vs SK Brann (2024-07-07)
Scraping goals 102/240 | KFUM Oslo vs Viking FK (2024-07-07)
Scraping goals 103/240 | HamKam vs Tromsø IL (2024-07-07)
Scraping goals 104/240 | Molde FK vs Lillestrøm (2024-07-07)
Scraping goals 105/240 | Haugesund vs Sarpsborg 08 (2024-07-07)
Scraping goals 106/240 | Rosenborg BK vs Odd (2024-07-07)
Scraping goals 107/240 | Kristiansund BK vs Fredrikstad FK (2024-07-08)
Scraping goals 108/240 | Strømsgodset vs Sandefjord (2024-07-08)
Scraping goals 109/240 | Sarpsborg 08 vs Rosenborg BK (2024-07-12)
Scraping goals 110/240 | Fredrikstad FK vs Molde FK (2024-07-13)
Scraping goals 111/240 | Odd vs HamKam (2024-07-13)
Scraping goals 112/240 | Lillestrøm vs Strømsgodset (2024-07-13)
Scraping goals 113/240 | Sandefjord vs Bodø/Glimt (2024-07-13)
Scraping goals 114/240 | Viking FK vs Kristiansund BK (2024-07-13)
Scraping goals 115/240 | SK Brann vs Haugesund (2024-07-13)
Scraping goals 116/240 | Tromsø IL vs KFUM Oslo (2024-07-13)
Scraping goals 117/240 | Bodø/Glimt vs Odd (2024-07-19)
Scraping goals 118/240 | Sarpsborg 08 vs SK Brann (2024-07-20)
Scraping goals 119/240 | Molde FK vs KFUM Oslo (2024-07-20)
Scraping goals 120/240 | Strømsgodset vs Tromsø IL (2024-07-21)
Scraping goals 121/240 | HamKam vs Fredrikstad FK (2024-07-21)
Scraping goals 122/240 | Haugesund vs Viking FK (2024-07-21)
Scraping goals 123/240 | KFUM Oslo vs Bodø/Glimt (2024-07-27)
Scraping goals 124/240 | Fredrikstad FK vs Rosenborg BK (2024-07-27)
Scraping goals 125/240 | Lillestrøm vs Sarpsborg 08 (2024-07-28)
Scraping goals 126/240 | Odd vs Strømsgodset (2024-07-28)
Scraping goals 127/240 | Sandefjord vs Haugesund (2024-07-28)
Scraping goals 128/240 | Tromsø IL vs Kristiansund BK (2024-07-28)
Scraping goals 129/240 | Viking FK vs Molde FK (2024-07-28)
Scraping goals 130/240 | Bodø/Glimt vs Haugesund (2024-08-03)
Scraping goals 131/240 | HamKam vs Viking FK (2024-08-04)
Scraping goals 132/240 | Sarpsborg 08 vs Sandefjord (2024-08-04)
Scraping goals 133/240 | Strømsgodset vs SK Brann (2024-08-04)
Scraping goals 134/240 | Kristiansund BK vs Lillestrøm (2024-08-04)
Scraping goals 135/240 | Fredrikstad FK vs KFUM Oslo (2024-08-04)
Scraping goals 136/240 | Rosenborg BK vs Tromsø IL (2024-08-04)
Scraping goals 137/240 | Sandefjord vs Strømsgodset (2024-08-09)
Scraping goals 138/240 | Haugesund vs HamKam (2024-08-10)
Scraping goals 139/240 | Viking FK vs Bodø/Glimt (2024-08-10)
Scraping goals 140/240 | KFUM Oslo vs Rosenborg BK (2024-08-11)
Scraping goals 141/240 | Odd vs Sarpsborg 08 (2024-08-11)
Scraping goals 142/240 | Lillestrøm vs Molde FK (2024-08-11)
Scraping goals 143/240 | Fredrikstad FK vs Haugesund (2024-08-14)
Scraping goals 144/240 | Strømsgodset vs Lillestrøm (2024-08-17)
Scraping goals 145/240 | Fredrikstad FK vs SK Brann (2024-08-18)
Scraping goals 146/240 | HamKam vs Odd (2024-08-18)
Scraping goals 147/240 | KFUM Oslo vs Tromsø IL (2024-08-18)
Scraping goals 148/240 | Sarpsborg 08 vs Haugesund (2024-08-18)
Scraping goals 149/240 | Rosenborg BK vs Viking FK (2024-08-18)
Scraping goals 150/240 | Rosenborg BK vs Lillestrøm (2024-08-21)
Scraping goals 151/240 | Bodø/Glimt vs Sarpsborg 08 (2024-08-24)
Scraping goals 152/240 | Lillestrøm vs Tromsø IL (2024-08-25)
Scraping goals 153/240 | Molde FK vs HamKam (2024-08-25)
Scraping goals 154/240 | Sandefjord vs Kristiansund BK (2024-08-25)
Scraping goals 155/240 | Viking FK vs Strømsgodset (2024-08-25)
Scraping goals 156/240 | Haugesund vs Fredrikstad FK (2024-08-25)
Scraping goals 157/240 | Odd vs Rosenborg BK (2024-08-25)
Scraping goals 158/240 | KFUM Oslo vs Lillestrøm (2024-08-30)
Scraping goals 159/240 | Fredrikstad FK vs Odd (2024-08-31)
Scraping goals 160/240 | HamKam vs Sandefjord (2024-09-01)
Scraping goals 161/240 | Rosenborg BK vs Molde FK (2024-09-01)
Scraping goals 162/240 | Tromsø IL vs Viking FK (2024-09-01)
Scraping goals 163/240 | Kristiansund BK vs Haugesund (2024-09-01)
Scraping goals 164/240 | Strømsgodset vs Bodø/Glimt (2024-09-01)
Scraping goals 165/240 | SK Brann vs Sarpsborg 08 (2024-09-01)
Scraping goals 166/240 | Bodø/Glimt vs HamKam (2024-09-13)
Scraping goals 167/240 | Viking FK vs KFUM Oslo (2024-09-14)
Scraping goals 168/240 | Molde FK vs Fredrikstad FK (2024-09-14)
Scraping goals 169/240 | Odd vs Tromsø IL (2024-09-15)
Scraping goals 170/240 | Sarpsborg 08 vs Kristiansund BK (2024-09-15)
Scraping goals 171/240 | Sandefjord vs SK Brann (2024-09-15)
Scraping goals 172/240 | Haugesund vs Strømsgodset (2024-09-15)
Scraping goals 173/240 | Lillestrøm vs Rosenborg BK (2024-09-15)
Scraping goals 174/240 | Kristiansund BK vs Molde FK (2024-09-18)
Scraping goals 175/240 | SK Brann vs KFUM Oslo (2024-09-18)
Scraping goals 176/240 | Strømsgodset vs Sarpsborg 08 (2024-09-21)
Scraping goals 177/240 | HamKam vs Lillestrøm (2024-09-21)
Scraping goals 178/240 | SK Brann vs Bodø/Glimt (2024-09-22)
Scraping goals 179/240 | Rosenborg BK vs Haugesund (2024-09-22)
Scraping goals 180/240 | Tromsø IL vs Sandefjord (2024-09-22)
Scraping goals 181/240 | Kristiansund BK vs Odd (2024-09-22)
Scraping goals 182/240 | Fredrikstad FK vs Viking FK (2024-09-22)
Scraping goals 183/240 | KFUM Oslo vs Molde FK (2024-09-23)
Scraping goals 184/240 | Molde FK vs Tromsø IL (2024-09-28)
Scraping goals 185/240 | Haugesund vs SK Brann (2024-09-28)
Scraping goals 186/240 | Sarpsborg 08 vs Fredrikstad FK (2024-09-28)
Scraping goals 187/240 | Strømsgodset vs HamKam (2024-09-29)
Scraping goals 188/240 | Bodø/Glimt vs Kristiansund BK (2024-09-29)
Scraping goals 189/240 | Lillestrøm vs Viking FK (2024-09-29)
Scraping goals 190/240 | Odd vs KFUM Oslo (2024-09-29)
Scraping goals 191/240 | Sandefjord vs Rosenborg BK (2024-09-29)
Scraping goals 192/240 | Kristiansund BK vs Sandefjord (2024-10-05)
Scraping goals 193/240 | Molde FK vs Sandefjord (2024-10-19)
Scraping goals 194/240 | Tromsø IL vs Bodø/Glimt (2024-10-19)
Scraping goals 195/240 | Rosenborg BK vs SK Brann (2024-10-20)
Scraping goals 196/240 | HamKam vs Sarpsborg 08 (2024-10-20)
Scraping goals 197/240 | KFUM Oslo vs Haugesund (2024-10-20)
Scraping goals 198/240 | Kristiansund BK vs Strømsgodset (2024-10-20)
Scraping goals 199/240 | Viking FK vs Odd (2024-10-20)
Scraping goals 200/240 | Fredrikstad FK vs Lillestrøm (2024-10-20)
Scraping goals 201/240 | Strømsgodset vs Fredrikstad FK (2024-10-26)
Scraping goals 202/240 | HamKam vs Kristiansund BK (2024-10-27)
Scraping goals 203/240 | Lillestrøm vs Odd (2024-10-27)
Scraping goals 204/240 | Sandefjord vs KFUM Oslo (2024-10-27)
Scraping goals 205/240 | Sarpsborg 08 vs Viking FK (2024-10-27)
Scraping goals 206/240 | Haugesund vs Molde FK (2024-10-27)
Scraping goals 207/240 | SK Brann vs Tromsø IL (2024-10-27)
Scraping goals 208/240 | Bodø/Glimt vs Rosenborg BK (2024-10-28)
Scraping goals 209/240 | Viking FK vs Sandefjord (2024-11-02)
Scraping goals 210/240 | KFUM Oslo vs Sarpsborg 08 (2024-11-03)
Scraping goals 211/240 | Tromsø IL vs HamKam (2024-11-03)
Scraping goals 212/240 | Lillestrøm vs Haugesund (2024-11-03)
Scraping goals 213/240 | Molde FK vs Bodø/Glimt (2024-11-03)
Scraping goals 214/240 | Odd vs SK Brann (2024-11-03)
Scraping goals 215/240 | Fredrikstad FK vs Kristiansund BK (2024-11-03)
Scraping goals 216/240 | Rosenborg BK vs Strømsgodset (2024-11-03)
Scraping goals 217/240 | SK Brann vs Lillestrøm (2024-11-09)
Scraping goals 218/240 | Kristiansund BK vs Viking FK (2024-11-10)
Scraping goals 219/240 | Sandefjord vs Odd (2024-11-10)
Scraping goals 220/240 | Strømsgodset vs KFUM Oslo (2024-11-10)
Scraping goals 221/240 | Haugesund vs Tromsø IL (2024-11-10)
Scraping goals 222/240 | HamKam vs Rosenborg BK (2024-11-10)
Scraping goals 223/240 | Sarpsborg 08 vs Molde FK (2024-11-10)
Scraping goals 224/240 | Bodø/Glimt vs Fredrikstad FK (2024-11-10)
Scraping goals 225/240 | Fredrikstad FK vs HamKam (2024-11-23)
Scraping goals 226/240 | Molde FK vs SK Brann (2024-11-23)
Scraping goals 227/240 | Odd vs Bodø/Glimt (2024-11-23)
Scraping goals 228/240 | Rosenborg BK vs Sarpsborg 08 (2024-11-23)
Scraping goals 229/240 | KFUM Oslo vs Kristiansund BK (2024-11-23)
Scraping goals 230/240 | Lillestrøm vs Sandefjord (2024-11-23)
Scraping goals 231/240 | Tromsø IL vs Strømsgodset (2024-11-23)
Scraping goals 232/240 | Viking FK vs Haugesund (2024-11-23)
Scraping goals 233/240 | HamKam vs KFUM Oslo (2024-12-01)
Scraping goals 234/240 | SK Brann vs Viking FK (2024-12-01)
Scraping goals 235/240 | Kristiansund BK vs Rosenborg BK (2024-12-01)
Scraping goals 236/240 | Strømsgodset vs Molde FK (2024-12-01)
Scraping goals 237/240 | Sandefjord vs Fredrikstad FK (2024-12-01)
Scraping goals 238/240 | Haugesund vs Odd (2024-12-01)
Scraping goals 239/240 | Sarpsborg 08 vs Tromsø IL (2024-12-01)
Scraping goals 240/240 | Bodø/Glimt vs Lillestrøm (2024-12-01)
Saved 681 goal-contribution rows to raw_eliterserien_goal_contributions_2024

# Ingest lineups

In [22]:
def save_eliteserien_lineups_for_season(
    season: tuple[int, int],
    db_path: Path,
    delay_seconds: float = 2.0,
    timeout_seconds: int = 30,
) -> None:
    """Scrape one Eliteserien season and save lineups to DuckDB."""
    year = season[1] or season[0]
    table_name = f"raw_eliterserien_lineups_{year}"

    print(f"Starting lineup scraping for season {season}...", flush=True)
    data = scrape_eliteserien_lineups_for_season(
        season=season,
        delay_seconds=delay_seconds,
        timeout_seconds=timeout_seconds,
    )

    if not data:
        print(f"No lineup records returned for season {season}; skipping.")
        return

    df = pl.DataFrame(data).with_columns(pl.lit(datetime.now()).alias("ingested_at"))

    with duckdb.connect(str(db_path)) as connection:
        connection.register("new_data", df)
        connection.execute(
            f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM new_data"
        )

    print(f"Saved {len(data)} lineup rows to {table_name}")


season_goal_contributions = [
    #(2020, 2021),
    #(2021, 2022),
    #(2022, 2023),
    (2023, 2024),
    #(2024, 2025),
    #(2025, 2026),
]

for index, season in enumerate(season_goal_contributions):
    if index:
        sleep(10)
    try:
        save_eliteserien_lineups_for_season(
            season=season,
            db_path=db_path,
            delay_seconds=1.0,
            timeout_seconds=30,
        )
    except Exception as error:
        print(f"Skipping season {season}: {error}", flush=True)

Starting lineup scraping for season (2023, 2024)...
Scraping lineups 1/240 | Odd vs Haugesund (2024-03-31)
Done 1/240 | players=40
Scraping lineups 2/240 | Fredrikstad FK vs Bodø/Glimt (2024-04-01)
Done 2/240 | players=38
Scraping lineups 3/240 | Lillestrøm vs Kristiansund BK (2024-04-01)
Done 3/240 | players=38
Scraping lineups 4/240 | Molde FK vs Strømsgodset (2024-04-01)
Done 4/240 | players=38
Scraping lineups 5/240 | Rosenborg BK vs Sandefjord (2024-04-01)
Done 5/240 | players=39
Scraping lineups 6/240 | Tromsø IL vs SK Brann (2024-04-01)
Done 6/240 | players=38
Scraping lineups 7/240 | Viking FK vs Sarpsborg 08 (2024-04-01)

KeyboardInterrupt:

In [ ]:
matches = scrape_fotmob_eliteserien_results_for_seasons(
    [(2025, 2026)],
    delay_seconds=0,
)

In [15]:
# List all table names
db_path = Path("data/brann.duckdb")
con = duckdb.connect(str(db_path))
table_names = con.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'main'").fetchall()
print("Available tables:")
for table in table_names:
    print(f"  - {table[0]}")
con.close()

Available tables:
  - dim_teams
  - fct_league_standings
  - fct_matches
  - raw_eliterserien_goal_contributions_2024
  - raw_eliterserien_goal_contributions_2025
  - raw_eliterserien_goal_contributions_2026
  - raw_eliterserien_lineups_2025
  - raw_eliterserien_lineups_2026
  - raw_eliteserien_results_2021
  - raw_eliteserien_results_2022
  - raw_eliteserien_results_2023
  - raw_eliteserien_results_2024
  - raw_eliteserien_results_2025
  - raw_eliteserien_results_2026
  - raw_fotmob_events_2024
  - raw_fotmob_events_2025
  - raw_fotmob_events_2026
  - raw_match_statistics_2021
  - raw_match_statistics_2022
  - raw_match_statistics_2023
  - raw_match_statistics_2024
  - raw_match_statistics_2025
  - raw_match_statistics_2026

In [19]:
con = duckdb.connect(str(Path(db_path)))
pl.from_arrow(con.execute("select * FROM raw_fotmob_events_2025").arrow()).filter(pl.col('home_team').str.contains('Brann'),pl.col('away_team').str.contains('Troms'))

shape: (96, 14)
┌────────┬────────────┬──────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ season ┆ date       ┆ matchday ┆ home_team ┆ … ┆ event_type ┆ event_titl ┆ text      ┆ ingested_ │
│ ---    ┆ ---        ┆ ---      ┆ ---       ┆   ┆ ---        ┆ e          ┆ ---       ┆ at        │
│ i64    ┆ date       ┆ i64      ┆ str       ┆   ┆ str        ┆ ---        ┆ str       ┆ ---       │
│        ┆            ┆          ┆           ┆   ┆            ┆ struct[2]  ┆           ┆ datetime[ │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆           ┆ μs]       │
╞════════╪════════════╪══════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 2025   ┆ 2025-04-06 ┆ 2        ┆ Brann     ┆ … ┆ post_match ┆ null       ┆ Brann     ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆ summary    ┆            ┆ lander på ┆ 9 09:55:0 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ beina     ┆ 3.213549  │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ etter ly… ┆           │
│ 2025   ┆ 2025-04-06 ┆ 2        ┆ Brann     ┆ … ┆            ┆ null       ┆ Brann-fri ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ spark i   ┆ 9 09:55:0 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ egen      ┆ 3.213549  │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ boks. La… ┆           │
│ 2025   ┆ 2025-04-06 ┆ 2        ┆ Brann     ┆ … ┆ comment    ┆ null       ┆ Kristians ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ en hylles ┆ 9 09:55:0 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ nå av     ┆ 3.213549  │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ samtl…    ┆           │
│ 2025   ┆ 2025-04-06 ┆ 2        ┆ Brann     ┆ … ┆            ┆ null       ┆ TIL-frisp ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ ark dypt  ┆ 9 09:55:0 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ på egen   ┆ 3.213549  │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ halv…     ┆           │
│ 2025   ┆ 2025-04-06 ┆ 2        ┆ Brann     ┆ … ┆ SI         ┆ {"player_s ┆ Bytte,    ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆ ubstitutio ┆ Brann.    ┆ 9 09:55:0 │
│        ┆            ┆          ┆           ┆   ┆            ┆ n","Substi ┆ Lars      ┆ 3.213549  │
│        ┆            ┆          ┆           ┆   ┆            ┆ …          ┆ Remmem    ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ erst…     ┆           │
│ …      ┆ …          ┆ …        ┆ …         ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 2025   ┆ 2025-04-06 ┆ 2        ┆ Brann     ┆ … ┆ comment    ┆ null       ┆ Dagens    ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ hoveddomm ┆ 9 09:55:0 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ er er Ola ┆ 3.213549  │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ Hobb…     ┆           │
│ 2025   ┆ 2025-04-06 ┆ 2        ┆ Brann     ┆ … ┆ comment    ┆ null       ┆ Brann tok ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ i fjor    ┆ 9 09:55:0 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ seks av   ┆ 3.213549  │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ seks …    ┆           │
│ 2025   ┆ 2025-04-06 ┆ 2        ┆ Brann     ┆ … ┆ comment    ┆ null       ┆ Tromsø    ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ innledet  ┆ 9 09:55:0 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ sesongen  ┆ 3.213549  │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ med 1…    ┆           │
│ 2025   ┆ 2025-04-06 ┆ 2        ┆ Brann     ┆ … ┆ comment    ┆ null       ┆ Suksesstr ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ ener      ┆ 9 09:55:0 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ Eirik     ┆ 3.213549  │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ Horneland ┆           │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ …         ┆           │
│ 2025   ┆ 2025-04-06 ┆ 2        ┆ Brann     ┆ … ┆ comment    ┆ null       ┆ Velkommen ┆ 2026-09-2 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ til lived ┆ 9 09:55:0 │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ ekningen  ┆ 3.213549  │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ av…       ┆           │
└────────┴────────────┴──────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [3]:
def hent_tabell_som_polars(table_name: str, db_path: str | Path = "data/brann.duckdb") -> pl.DataFrame:
    """
    Henter en tabell fra en DuckDB-database og returnerer den som en Polars DataFrame.

    Args:
        table_name: Navnet på tabellen som skal hentes.
        db_path: Sti til DuckDB-databasen (default: "data/brann.duckdb").

    Returns:
        Polars DataFrame med innholdet fra tabellen.
    """
    con = duckdb.connect(str(Path(db_path)))
    try:
        arrow_table = con.execute(f"SELECT * FROM {table_name}").arrow()
        df = pl.from_arrow(arrow_table)
    finally:
        con.close()
    return df

In [12]:
col_2023 = hent_tabell_som_polars("raw_match_statistics_2024").columns
col_2024 = hent_tabell_som_polars("raw_match_statistics_2025").columns

In [8]:
con = duckdb.connect(str(Path(db_path)))
con.execute("SELECT * FROM raw_match_statistics_2024 union all by name select * FROM raw_match_statistics_2025")