In [3]:
import importlib
import polars as pl
import polars.selectors as cs
from datetime import datetime
import polars_ds as pds
import requests
import json
import duckdb
from pathlib import Path
from time import sleep
import src.utils as utils

importlib.reload(utils)

from src.utils import (
    scrape_eliteserien_all_xg_for_seasons,
    scrape_eliteserien_results_for_seasons,
    scrape_transfermarkt_goal_contributions,
    scrape_eliteserien_goal_contributions_for_season,
    scrape_transfermarkt_lineups,
    scrape_fotmob_eliteserien_results_for_seasons,
    scrape_fotmob_match_report
)

In [4]:
from src.utils import scrape_fotmob_eliteserien_results_for_seasons

matches = scrape_fotmob_eliteserien_results_for_seasons(
    [(2025, 2026)],
    delay_seconds=0,
)

shape: (105, 6)
┌──────┬───────┬─────────┬─────────────────────┬──────────────┬─────────────────────────────────┐
│ main ┆ added ┆ type    ┆ key                 ┆ value        ┆ text                            │
│ ---  ┆ ---   ┆ ---     ┆ ---                 ┆ ---          ┆ ---                             │
│ str  ┆ str   ┆ str     ┆ str                 ┆ str          ┆ str                             │
╞══════╪═══════╪═════════╪═════════════════════╪══════════════╪═════════════════════════════════╡
│ 90‎’‎  ┆ +5    ┆ comment ┆ null                ┆ null         ┆ Glimt har nesten et "hvordan b… │
│ 90‎’‎  ┆ +4    ┆ comment ┆ null                ┆ null         ┆ Nilsen snur seg mot den ene ko… │
│ 90‎’‎  ┆ +3    ┆ comment ┆ null                ┆ null         ┆ Torsvik på et eventyr som leng… │
│ 90‎’‎  ┆ +2    ┆ SI      ┆ player_substitution ┆ Substitution ┆ Bytte, Brann. Kjartan Már Kjar… │
│ 90‎’‎  ┆ +2    ┆ comment ┆ null                ┆ null         ┆ Saltnes på et innlegg fra vens… │
│ …    ┆ …     ┆ …       ┆ …                   ┆ …            ┆ …                               │
│ 3‎’‎   ┆ null  ┆ FK      ┆ null                ┆ null         ┆ Frispark til Bodø/Glimt, tas a… │
│ 2‎’‎   ┆ null  ┆ OFFSIDE ┆ null                ┆ null         ┆ Offside, Bodø/Glimt, Ole Didri… │
│ 2‎’‎   ┆ null  ┆ comment ┆ null                ┆ null         ┆ Kasanwirjo stopper sammen med … │
│ 1‎’‎   ┆ null  ┆ comment ┆ null                ┆ null         ┆ Rikelig med tilreisende fra Bo… │
│ 1‎’‎   ┆ null  ┆ comment ┆ null                ┆ null         ┆ Glimt innleder oppgjøret.       │
└──────┴───────┴─────────┴─────────────────────┴──────────────┴─────────────────────────────────┘

In [7]:
lineups = scrape_eliteserien_lineups_for_season(
    season=(2025, 2026),
    delay_seconds=2.0,
)
pl.DataFrame(lineups)

Scraping lineups 1/168 | HamKam vs Viking FK (2026-03-14)
Done 1/168 | players=40
Scraping lineups 2/168 | Molde FK vs Rosenborg BK (2026-03-14)
Done 2/168 | players=39
Scraping lineups 3/168 | Kristiansund BK vs SK Brann (2026-03-15)
Done 3/168 | players=39

KeyboardInterrupt:

In [2]:
seasons = [
    (2020,2021),
    (2021,2022),
    (2022,2023),
    (2023,2024),
    (2024,2025),
    (2025,2026)
]

db_path = Path("data/brann.duckdb")

# Ingest Eliteserien results

In [10]:
def save_eliteserien_results_for_season(
    season: tuple[int, int | None],
    db_path: Path,
    delay_seconds: float = 0.5,
) -> None:
    """Scrape one Eliteserien season and store it in its own raw_eliteserien_results_<year> table."""
    year = season[1] or season[0]
    table_name = f"raw_eliteserien_results_{year}"

    data = scrape_eliteserien_results_for_seasons([season], delay_seconds=delay_seconds)
    if not data:
        print(f"No records returned for season {season}; skipping.")
        return

    df = pl.DataFrame(data).with_columns(pl.lit(datetime.now()).alias("ingested_at"))

    with duckdb.connect(str(db_path)) as connection:
        connection.register("new_data", df)
        connection.execute(f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM new_data")

    print(f"✓ Saved {len(data)} matches to {table_name}")


# Ingest results season by season so one failing season doesn't block the rest
for season in seasons:
    try:
        save_eliteserien_results_for_season(season, db_path, delay_seconds=0.5)
    except Exception as error:
        print(f"Skipping season {season}: {error}")

✓ Saved 240 matches to raw_eliteserien_results_2021
✓ Saved 240 matches to raw_eliteserien_results_2022
✓ Saved 240 matches to raw_eliteserien_results_2023
✓ Saved 240 matches to raw_eliteserien_results_2024
✓ Saved 240 matches to raw_eliteserien_results_2025
✓ Saved 168 matches to raw_eliteserien_results_2026

# Ingest Eliteserien match statistics

In [20]:
def save_eliteserien_xg_for_season(
    season: tuple[int, int | None],
    db_path: Path,
    delay_seconds: float = 0.01,
    season_delay_seconds: float = 0.1,
    timeout_seconds: int = 30,
) -> None:
    """Scrape one Eliteserien season's xG/stats and store it in its own raw_match_statistics_<year> table."""
    year = season[1] or season[0]
    table_name = f"raw_match_statistics_{year}"

    data = scrape_eliteserien_all_xg_for_seasons(
        [season],
        delay_seconds=delay_seconds,
        season_delay_seconds=season_delay_seconds,
        timeout_seconds=timeout_seconds,
    )
    if not data:
        print(f"No records returned for season {season}; skipping.")
        return

    df = pl.DataFrame(data).with_columns(pl.lit(datetime.now()).alias("ingested_at"))

    with duckdb.connect(str(db_path)) as connection:
        connection.register("new_data", df)
        connection.execute(f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM new_data")

    print(f"✓ Saved {len(data)} matches to {table_name}")


# Ingest xG/stats season by season, waiting 10s between seasons so one failing season doesn't block the rest
for index, season in enumerate(seasons):
    if index:
        sleep(10)
    try:
        save_eliteserien_xg_for_season(season, db_path)
    except Exception as error:
        print(f"Skipping season {season}: {error}")

Fetching xG for season 2021 (ID: 2020)...
✓ Saved 240 matches to raw_match_statistics_2021
Fetching xG for season 2022 (ID: 2021)...
✓ Saved 240 matches to raw_match_statistics_2022
Fetching xG for season 2023 (ID: 2022)...
✓ Saved 240 matches to raw_match_statistics_2023
Fetching xG for season 2024 (ID: 2023)...
✓ Saved 240 matches to raw_match_statistics_2024
Fetching xG for season 2025 (ID: 2024)...
✓ Saved 240 matches to raw_match_statistics_2025
Fetching xG for season 2026 (ID: 2025)...
✓ Saved 168 matches to raw_match_statistics_2026

# Ingest goal contributions

In [4]:
def save_eliteserien_goal_contributions_for_season(
    season: tuple[int, int],
    db_path: Path,
    delay_seconds: float = 2.0,
    timeout_seconds: int = 30,
) -> None:
    """Scrape one Eliteserien season and save goal contributions to DuckDB."""
    year = season[1] or season[0]
    table_name = f"raw_eliterserien_goal_contributions_{year}"

    print(f"Starting goal-contribution scraping for season {season}...", flush=True)
    data = scrape_eliteserien_goal_contributions_for_season(
        season=season,
        delay_seconds=delay_seconds,
        timeout_seconds=timeout_seconds,
    )

    if not data:
        print(f"No goal-contribution records returned for season {season}; skipping.")
        return

    df = pl.DataFrame(data).with_columns(pl.lit(datetime.now()).alias("ingested_at"))

    with duckdb.connect(str(db_path)) as connection:
        connection.register("new_data", df)
        connection.execute(
            f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM new_data"
        )

    print(f"Saved {len(data)} goal-contribution rows to {table_name}")


season_goal_contributions = [
    #(2020, 2021),
    #(2021, 2022),
    #(2022, 2023),
    (2023, 2024),
    #(2024, 2025),
    #(2025, 2026),
]

for index, season in enumerate(season_goal_contributions):
    if index:
        sleep(10)
    try:
        save_eliteserien_goal_contributions_for_season(
            season=season,
            db_path=db_path,
            delay_seconds=0,
            timeout_seconds=30,
        )
    except Exception as error:
        print(f"Skipping season {season}: {error}")

Starting goal-contribution scraping for season (2023, 2024)...
Scraping goals 1/240 | Odd vs Haugesund (2024-03-31)
Scraping goals 2/240 | Fredrikstad FK vs Bodø/Glimt (2024-04-01)
Scraping goals 3/240 | Lillestrøm vs Kristiansund BK (2024-04-01)
Scraping goals 4/240 | Molde FK vs Strømsgodset (2024-04-01)
Scraping goals 5/240 | Rosenborg BK vs Sandefjord (2024-04-01)
Scraping goals 6/240 | Tromsø IL vs SK Brann (2024-04-01)
Scraping goals 7/240 | Viking FK vs Sarpsborg 08 (2024-04-01)
Scraping goals 8/240 | KFUM Oslo vs HamKam (2024-04-02)
Scraping goals 9/240 | Bodø/Glimt vs Viking FK (2024-04-06)
Scraping goals 10/240 | Kristiansund BK vs KFUM Oslo (2024-04-07)
Scraping goals 11/240 | HamKam vs Molde FK (2024-04-07)
Scraping goals 12/240 | Sarpsborg 08 vs Odd (2024-04-07)
Scraping goals 13/240 | Strømsgodset vs Rosenborg BK (2024-04-07)
Scraping goals 14/240 | Haugesund vs Lillestrøm (2024-04-07)
Scraping goals 15/240 | SK Brann vs Fredrikstad FK (2024-04-07)
Scraping goals 16/240 | Fredrikstad FK vs Sarpsborg 08 (2024-04-13)
Scraping goals 17/240 | Viking FK vs SK Brann (2024-04-14)
Scraping goals 18/240 | Tromsø IL vs Haugesund (2024-04-14)
Scraping goals 19/240 | Molde FK vs Kristiansund BK (2024-04-14)
Scraping goals 20/240 | Odd vs Sandefjord (2024-04-14)
Scraping goals 21/240 | Rosenborg BK vs HamKam (2024-04-14)
Scraping goals 22/240 | Lillestrøm vs Bodø/Glimt (2024-04-14)
Scraping goals 23/240 | KFUM Oslo vs Strømsgodset (2024-04-16)
Scraping goals 24/240 | SK Brann vs HamKam (2024-04-17)
Scraping goals 25/240 | Molde FK vs Odd (2024-04-17)
Scraping goals 26/240 | HamKam vs Strømsgodset (2024-04-21)
Scraping goals 27/240 | Sandefjord vs Lillestrøm (2024-04-21)
Scraping goals 28/240 | Sarpsborg 08 vs KFUM Oslo (2024-04-21)
Scraping goals 29/240 | SK Brann vs Odd (2024-04-21)
Scraping goals 30/240 | Viking FK vs Fredrikstad FK (2024-04-21)
Scraping goals 31/240 | Haugesund vs Rosenborg BK (2024-04-21)
Scraping goals 32/240 | Kristiansund BK vs Tromsø IL (2024-04-21)
Scraping goals 33/240 | Bodø/Glimt vs Molde FK (2024-04-21)
Scraping goals 34/240 | Rosenborg BK vs Bodø/Glimt (2024-04-27)
Scraping goals 35/240 | Fredrikstad FK vs Sandefjord (2024-04-28)
Scraping goals 36/240 | Tromsø IL vs Sarpsborg 08 (2024-04-28)
Scraping goals 37/240 | KFUM Oslo vs SK Brann (2024-04-28)
Scraping goals 38/240 | Lillestrøm vs HamKam (2024-04-28)
Scraping goals 39/240 | Molde FK vs Haugesund (2024-04-28)
Scraping goals 40/240 | Strømsgodset vs Kristiansund BK (2024-04-28)
Scraping goals 41/240 | Odd vs Viking FK (2024-04-28)
Scraping goals 42/240 | SK Brann vs Rosenborg BK (2024-05-04)
Scraping goals 43/240 | Haugesund vs KFUM Oslo (2024-05-05)
Scraping goals 44/240 | Kristiansund BK vs HamKam (2024-05-05)
Scraping goals 45/240 | Sarpsborg 08 vs Lillestrøm (2024-05-05)
Scraping goals 46/240 | Odd vs Fredrikstad FK (2024-05-05)
Scraping goals 47/240 | Bodø/Glimt vs Strømsgodset (2024-05-05)
Scraping goals 48/240 | Sandefjord vs Molde FK (2024-05-05)
Scraping goals 49/240 | Viking FK vs Tromsø IL (2024-05-05)
Scraping goals 50/240 | Molde FK vs Rosenborg BK (2024-05-11)
Scraping goals 51/240 | Kristiansund BK vs Bodø/Glimt (2024-05-12)
Scraping goals 52/240 | Strømsgodset vs Viking FK (2024-05-12)
Scraping goals 53/240 | KFUM Oslo vs Fredrikstad FK (2024-05-12)
Scraping goals 54/240 | HamKam vs Haugesund (2024-05-12)
Scraping goals 55/240 | Sandefjord vs Sarpsborg 08 (2024-05-12)
Scraping goals 56/240 | Tromsø IL vs Odd (2024-05-12)
Scraping goals 57/240 | Lillestrøm vs SK Brann (2024-05-12)
Scraping goals 58/240 | SK Brann vs Sandefjord (2024-05-16)
Scraping goals 59/240 | Haugesund vs Kristiansund BK (2024-05-16)
Scraping goals 60/240 | Sarpsborg 08 vs HamKam (2024-05-16)
Scraping goals 61/240 | Viking FK vs Lillestrøm (2024-05-16)
Scraping goals 62/240 | Bodø/Glimt vs Tromsø IL (2024-05-16)
Scraping goals 63/240 | Fredrikstad FK vs Strømsgodset (2024-05-16)
Scraping goals 64/240 | Odd vs Molde FK (2024-05-16)
Scraping goals 65/240 | Rosenborg BK vs KFUM Oslo (2024-05-16)
Scraping goals 66/240 | Kristiansund BK vs SK Brann (2024-05-20)
Scraping goals 67/240 | Sandefjord vs Viking FK (2024-05-20)
Scraping goals 68/240 | Strømsgodset vs Haugesund (2024-05-20)
Scraping goals 69/240 | HamKam vs Bodø/Glimt (2024-05-20)
Scraping goals 70/240 | KFUM Oslo vs Odd (2024-05-20)
Scraping goals 71/240 | Lillestrøm vs Fredrikstad FK (2024-05-20)
Scraping goals 72/240 | Molde FK vs Sarpsborg 08 (2024-05-20)
Scraping goals 73/240 | Tromsø IL vs Rosenborg BK (2024-05-20)
Scraping goals 74/240 | Bodø/Glimt vs KFUM Oslo (2024-05-24)
Scraping goals 75/240 | Fredrikstad FK vs Tromsø IL (2024-05-25)
Scraping goals 76/240 | Odd vs Lillestrøm (2024-05-26)
Scraping goals 77/240 | Sarpsborg 08 vs Strømsgodset (2024-05-26)
Scraping goals 78/240 | Viking FK vs HamKam (2024-05-26)
Scraping goals 79/240 | Haugesund vs Sandefjord (2024-05-26)
Scraping goals 80/240 | Rosenborg BK vs Kristiansund BK (2024-05-26)
Scraping goals 81/240 | SK Brann vs Molde FK (2024-05-26)
Scraping goals 82/240 | Tromsø IL vs Fredrikstad FK (2024-05-29)
Scraping goals 83/240 | SK Brann vs Kristiansund BK (2024-05-29)
Scraping goals 84/240 | Bodø/Glimt vs Sandefjord (2024-05-29)
Scraping goals 85/240 | HamKam vs SK Brann (2024-06-01)
Scraping goals 86/240 | Molde FK vs Viking FK (2024-06-02)
Scraping goals 87/240 | Strømsgodset vs Odd (2024-06-02)
Scraping goals 88/240 | Haugesund vs Bodø/Glimt (2024-06-02)
Scraping goals 89/240 | KFUM Oslo vs Sandefjord (2024-06-02)
Scraping goals 90/240 | Kristiansund BK vs Sarpsborg 08 (2024-06-02)
Scraping goals 91/240 | Tromsø IL vs Lillestrøm (2024-06-02)
Scraping goals 92/240 | Rosenborg BK vs Fredrikstad FK (2024-06-02)
Scraping goals 93/240 | Sandefjord vs HamKam (2024-06-27)
Scraping goals 94/240 | Lillestrøm vs KFUM Oslo (2024-06-27)
Scraping goals 95/240 | SK Brann vs Strømsgodset (2024-06-28)
Scraping goals 96/240 | Sarpsborg 08 vs Bodø/Glimt (2024-06-28)
Scraping goals 97/240 | Odd vs Kristiansund BK (2024-06-28)
Scraping goals 98/240 | Tromsø IL vs Molde FK (2024-06-28)
Scraping goals 99/240 | Viking FK vs Rosenborg BK (2024-06-30)
Scraping goals 100/240 | Sandefjord vs Tromsø IL (2024-07-03)
Scraping goals 101/240 | Bodø/Glimt vs SK Brann (2024-07-07)
Scraping goals 102/240 | KFUM Oslo vs Viking FK (2024-07-07)
Scraping goals 103/240 | HamKam vs Tromsø IL (2024-07-07)
Scraping goals 104/240 | Molde FK vs Lillestrøm (2024-07-07)
Scraping goals 105/240 | Haugesund vs Sarpsborg 08 (2024-07-07)
Scraping goals 106/240 | Rosenborg BK vs Odd (2024-07-07)
Scraping goals 107/240 | Kristiansund BK vs Fredrikstad FK (2024-07-08)
Scraping goals 108/240 | Strømsgodset vs Sandefjord (2024-07-08)
Scraping goals 109/240 | Sarpsborg 08 vs Rosenborg BK (2024-07-12)
Scraping goals 110/240 | Fredrikstad FK vs Molde FK (2024-07-13)
Scraping goals 111/240 | Odd vs HamKam (2024-07-13)
Scraping goals 112/240 | Lillestrøm vs Strømsgodset (2024-07-13)
Scraping goals 113/240 | Sandefjord vs Bodø/Glimt (2024-07-13)
Scraping goals 114/240 | Viking FK vs Kristiansund BK (2024-07-13)
Scraping goals 115/240 | SK Brann vs Haugesund (2024-07-13)
Scraping goals 116/240 | Tromsø IL vs KFUM Oslo (2024-07-13)
Scraping goals 117/240 | Bodø/Glimt vs Odd (2024-07-19)
Scraping goals 118/240 | Sarpsborg 08 vs SK Brann (2024-07-20)
Scraping goals 119/240 | Molde FK vs KFUM Oslo (2024-07-20)
Scraping goals 120/240 | Strømsgodset vs Tromsø IL (2024-07-21)
Scraping goals 121/240 | HamKam vs Fredrikstad FK (2024-07-21)
Scraping goals 122/240 | Haugesund vs Viking FK (2024-07-21)
Scraping goals 123/240 | KFUM Oslo vs Bodø/Glimt (2024-07-27)
Scraping goals 124/240 | Fredrikstad FK vs Rosenborg BK (2024-07-27)
Scraping goals 125/240 | Lillestrøm vs Sarpsborg 08 (2024-07-28)
Scraping goals 126/240 | Odd vs Strømsgodset (2024-07-28)
Scraping goals 127/240 | Sandefjord vs Haugesund (2024-07-28)
Scraping goals 128/240 | Tromsø IL vs Kristiansund BK (2024-07-28)
Scraping goals 129/240 | Viking FK vs Molde FK (2024-07-28)
Scraping goals 130/240 | Bodø/Glimt vs Haugesund (2024-08-03)
Scraping goals 131/240 | HamKam vs Viking FK (2024-08-04)
Scraping goals 132/240 | Sarpsborg 08 vs Sandefjord (2024-08-04)
Scraping goals 133/240 | Strømsgodset vs SK Brann (2024-08-04)
Scraping goals 134/240 | Kristiansund BK vs Lillestrøm (2024-08-04)
Scraping goals 135/240 | Fredrikstad FK vs KFUM Oslo (2024-08-04)
Scraping goals 136/240 | Rosenborg BK vs Tromsø IL (2024-08-04)
Scraping goals 137/240 | Sandefjord vs Strømsgodset (2024-08-09)
Scraping goals 138/240 | Haugesund vs HamKam (2024-08-10)
Scraping goals 139/240 | Viking FK vs Bodø/Glimt (2024-08-10)
Scraping goals 140/240 | KFUM Oslo vs Rosenborg BK (2024-08-11)
Scraping goals 141/240 | Odd vs Sarpsborg 08 (2024-08-11)
Scraping goals 142/240 | Lillestrøm vs Molde FK (2024-08-11)
Scraping goals 143/240 | Fredrikstad FK vs Haugesund (2024-08-14)
Scraping goals 144/240 | Strømsgodset vs Lillestrøm (2024-08-17)
Scraping goals 145/240 | Fredrikstad FK vs SK Brann (2024-08-18)
Scraping goals 146/240 | HamKam vs Odd (2024-08-18)
Scraping goals 147/240 | KFUM Oslo vs Tromsø IL (2024-08-18)
Scraping goals 148/240 | Sarpsborg 08 vs Haugesund (2024-08-18)
Scraping goals 149/240 | Rosenborg BK vs Viking FK (2024-08-18)
Scraping goals 150/240 | Rosenborg BK vs Lillestrøm (2024-08-21)
Scraping goals 151/240 | Bodø/Glimt vs Sarpsborg 08 (2024-08-24)
Scraping goals 152/240 | Lillestrøm vs Tromsø IL (2024-08-25)
Scraping goals 153/240 | Molde FK vs HamKam (2024-08-25)
Scraping goals 154/240 | Sandefjord vs Kristiansund BK (2024-08-25)
Scraping goals 155/240 | Viking FK vs Strømsgodset (2024-08-25)
Scraping goals 156/240 | Haugesund vs Fredrikstad FK (2024-08-25)
Scraping goals 157/240 | Odd vs Rosenborg BK (2024-08-25)
Scraping goals 158/240 | KFUM Oslo vs Lillestrøm (2024-08-30)
Scraping goals 159/240 | Fredrikstad FK vs Odd (2024-08-31)
Scraping goals 160/240 | HamKam vs Sandefjord (2024-09-01)
Scraping goals 161/240 | Rosenborg BK vs Molde FK (2024-09-01)
Scraping goals 162/240 | Tromsø IL vs Viking FK (2024-09-01)
Scraping goals 163/240 | Kristiansund BK vs Haugesund (2024-09-01)
Scraping goals 164/240 | Strømsgodset vs Bodø/Glimt (2024-09-01)
Scraping goals 165/240 | SK Brann vs Sarpsborg 08 (2024-09-01)
Scraping goals 166/240 | Bodø/Glimt vs HamKam (2024-09-13)
Scraping goals 167/240 | Viking FK vs KFUM Oslo (2024-09-14)
Scraping goals 168/240 | Molde FK vs Fredrikstad FK (2024-09-14)
Scraping goals 169/240 | Odd vs Tromsø IL (2024-09-15)
Scraping goals 170/240 | Sarpsborg 08 vs Kristiansund BK (2024-09-15)
Scraping goals 171/240 | Sandefjord vs SK Brann (2024-09-15)
Scraping goals 172/240 | Haugesund vs Strømsgodset (2024-09-15)
Scraping goals 173/240 | Lillestrøm vs Rosenborg BK (2024-09-15)
Scraping goals 174/240 | Kristiansund BK vs Molde FK (2024-09-18)
Scraping goals 175/240 | SK Brann vs KFUM Oslo (2024-09-18)
Scraping goals 176/240 | Strømsgodset vs Sarpsborg 08 (2024-09-21)
Scraping goals 177/240 | HamKam vs Lillestrøm (2024-09-21)
Scraping goals 178/240 | SK Brann vs Bodø/Glimt (2024-09-22)
Scraping goals 179/240 | Rosenborg BK vs Haugesund (2024-09-22)
Scraping goals 180/240 | Tromsø IL vs Sandefjord (2024-09-22)
Scraping goals 181/240 | Kristiansund BK vs Odd (2024-09-22)
Scraping goals 182/240 | Fredrikstad FK vs Viking FK (2024-09-22)
Scraping goals 183/240 | KFUM Oslo vs Molde FK (2024-09-23)
Scraping goals 184/240 | Molde FK vs Tromsø IL (2024-09-28)
Scraping goals 185/240 | Haugesund vs SK Brann (2024-09-28)
Scraping goals 186/240 | Sarpsborg 08 vs Fredrikstad FK (2024-09-28)
Scraping goals 187/240 | Strømsgodset vs HamKam (2024-09-29)
Scraping goals 188/240 | Bodø/Glimt vs Kristiansund BK (2024-09-29)
Scraping goals 189/240 | Lillestrøm vs Viking FK (2024-09-29)
Scraping goals 190/240 | Odd vs KFUM Oslo (2024-09-29)
Scraping goals 191/240 | Sandefjord vs Rosenborg BK (2024-09-29)
Scraping goals 192/240 | Kristiansund BK vs Sandefjord (2024-10-05)
Scraping goals 193/240 | Molde FK vs Sandefjord (2024-10-19)
Scraping goals 194/240 | Tromsø IL vs Bodø/Glimt (2024-10-19)
Scraping goals 195/240 | Rosenborg BK vs SK Brann (2024-10-20)
Scraping goals 196/240 | HamKam vs Sarpsborg 08 (2024-10-20)
Scraping goals 197/240 | KFUM Oslo vs Haugesund (2024-10-20)
Scraping goals 198/240 | Kristiansund BK vs Strømsgodset (2024-10-20)
Scraping goals 199/240 | Viking FK vs Odd (2024-10-20)
Scraping goals 200/240 | Fredrikstad FK vs Lillestrøm (2024-10-20)
Scraping goals 201/240 | Strømsgodset vs Fredrikstad FK (2024-10-26)
Scraping goals 202/240 | HamKam vs Kristiansund BK (2024-10-27)
Scraping goals 203/240 | Lillestrøm vs Odd (2024-10-27)
Scraping goals 204/240 | Sandefjord vs KFUM Oslo (2024-10-27)
Scraping goals 205/240 | Sarpsborg 08 vs Viking FK (2024-10-27)
Scraping goals 206/240 | Haugesund vs Molde FK (2024-10-27)
Scraping goals 207/240 | SK Brann vs Tromsø IL (2024-10-27)
Scraping goals 208/240 | Bodø/Glimt vs Rosenborg BK (2024-10-28)
Scraping goals 209/240 | Viking FK vs Sandefjord (2024-11-02)
Scraping goals 210/240 | KFUM Oslo vs Sarpsborg 08 (2024-11-03)
Scraping goals 211/240 | Tromsø IL vs HamKam (2024-11-03)
Scraping goals 212/240 | Lillestrøm vs Haugesund (2024-11-03)
Scraping goals 213/240 | Molde FK vs Bodø/Glimt (2024-11-03)
Scraping goals 214/240 | Odd vs SK Brann (2024-11-03)
Scraping goals 215/240 | Fredrikstad FK vs Kristiansund BK (2024-11-03)
Scraping goals 216/240 | Rosenborg BK vs Strømsgodset (2024-11-03)
Scraping goals 217/240 | SK Brann vs Lillestrøm (2024-11-09)
Scraping goals 218/240 | Kristiansund BK vs Viking FK (2024-11-10)
Scraping goals 219/240 | Sandefjord vs Odd (2024-11-10)
Scraping goals 220/240 | Strømsgodset vs KFUM Oslo (2024-11-10)
Scraping goals 221/240 | Haugesund vs Tromsø IL (2024-11-10)
Scraping goals 222/240 | HamKam vs Rosenborg BK (2024-11-10)
Scraping goals 223/240 | Sarpsborg 08 vs Molde FK (2024-11-10)
Scraping goals 224/240 | Bodø/Glimt vs Fredrikstad FK (2024-11-10)
Scraping goals 225/240 | Fredrikstad FK vs HamKam (2024-11-23)
Scraping goals 226/240 | Molde FK vs SK Brann (2024-11-23)
Scraping goals 227/240 | Odd vs Bodø/Glimt (2024-11-23)
Scraping goals 228/240 | Rosenborg BK vs Sarpsborg 08 (2024-11-23)
Scraping goals 229/240 | KFUM Oslo vs Kristiansund BK (2024-11-23)
Scraping goals 230/240 | Lillestrøm vs Sandefjord (2024-11-23)
Scraping goals 231/240 | Tromsø IL vs Strømsgodset (2024-11-23)
Scraping goals 232/240 | Viking FK vs Haugesund (2024-11-23)
Scraping goals 233/240 | HamKam vs KFUM Oslo (2024-12-01)
Scraping goals 234/240 | SK Brann vs Viking FK (2024-12-01)
Scraping goals 235/240 | Kristiansund BK vs Rosenborg BK (2024-12-01)
Scraping goals 236/240 | Strømsgodset vs Molde FK (2024-12-01)
Scraping goals 237/240 | Sandefjord vs Fredrikstad FK (2024-12-01)
Scraping goals 238/240 | Haugesund vs Odd (2024-12-01)
Scraping goals 239/240 | Sarpsborg 08 vs Tromsø IL (2024-12-01)
Scraping goals 240/240 | Bodø/Glimt vs Lillestrøm (2024-12-01)
Saved 681 goal-contribution rows to raw_eliterserien_goal_contributions_2024

# Ingest lineups

In [5]:
def save_eliteserien_lineups_for_season(
    season: tuple[int, int],
    db_path: Path,
    delay_seconds: float = 2.0,
    timeout_seconds: int = 30,
) -> None:
    """Scrape one Eliteserien season and save lineups to DuckDB."""
    year = season[1] or season[0]
    table_name = f"raw_eliterserien_lineups_{year}"

    print(f"Starting lineup scraping for season {season}...", flush=True)
    data = scrape_eliteserien_lineups_for_season(
        season=season,
        delay_seconds=delay_seconds,
        timeout_seconds=timeout_seconds,
    )

    if not data:
        print(f"No lineup records returned for season {season}; skipping.")
        return

    df = pl.DataFrame(data).with_columns(pl.lit(datetime.now()).alias("ingested_at"))

    with duckdb.connect(str(db_path)) as connection:
        connection.register("new_data", df)
        connection.execute(
            f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM new_data"
        )

    print(f"Saved {len(data)} lineup rows to {table_name}")


season_goal_contributions = [
    #(2020, 2021),
    #(2021, 2022),
    #(2022, 2023),
    #(2023, 2024),
    (2024, 2025),
    #(2025, 2026),
]

for index, season in enumerate(season_goal_contributions):
    if index:
        sleep(10)
    try:
        save_eliteserien_lineups_for_season(
            season=season,
            db_path=db_path,
            delay_seconds=1.0,
            timeout_seconds=30,
        )
    except Exception as error:
        print(f"Skipping season {season}: {error}", flush=True)

Starting lineup scraping for season (2024, 2025)...
Scraping lineups 1/240 | Strømsgodset vs Rosenborg BK (2025-03-29)
Done 1/240 | players=40
Scraping lineups 2/240 | Fredrikstad FK vs SK Brann (2025-03-29)
Done 2/240 | players=40
Scraping lineups 3/240 | Vålerenga vs Viking FK (2025-03-30)
Done 3/240 | players=40
Scraping lineups 4/240 | HamKam vs Kristiansund BK (2025-03-30)
Done 4/240 | players=39
Scraping lineups 5/240 | KFUM Oslo vs Sandefjord (2025-03-30)
Done 5/240 | players=37
Scraping lineups 6/240 | Molde FK vs Sarpsborg 08 (2025-03-30)
Done 6/240 | players=40
Scraping lineups 7/240 | Tromsø IL vs Haugesund (2025-03-30)
Done 7/240 | players=39
Scraping lineups 8/240 | Bryne vs Bodø/Glimt (2025-03-30)
Done 8/240 | players=39
Scraping lineups 9/240 | Bodø/Glimt vs HamKam (2025-04-05)
Done 9/240 | players=40
Scraping lineups 10/240 | Rosenborg BK vs Fredrikstad FK (2025-04-05)
Done 10/240 | players=40
Scraping lineups 11/240 | SK Brann vs Tromsø IL (2025-04-06)
Done 11/240 | players=40
Scraping lineups 12/240 | Haugesund vs Strømsgodset (2025-04-06)
Done 12/240 | players=38
Scraping lineups 13/240 | Kristiansund BK vs Bryne (2025-04-06)
Done 13/240 | players=39
Scraping lineups 14/240 | Sandefjord vs Molde FK (2025-04-06)
Done 14/240 | players=40
Scraping lineups 15/240 | Sarpsborg 08 vs Vålerenga (2025-04-06)
Done 15/240 | players=40
Scraping lineups 16/240 | Viking FK vs KFUM Oslo (2025-04-06)
Done 16/240 | players=38
Scraping lineups 17/240 | Fredrikstad FK vs Vålerenga (2025-04-09)
Done 17/240 | players=40
Scraping lineups 18/240 | Viking FK vs Kristiansund BK (2025-04-10)
Done 18/240 | players=39
Scraping lineups 19/240 | SK Brann vs Strømsgodset (2025-04-10)
Done 19/240 | players=38
Scraping lineups 20/240 | Tromsø IL vs Kristiansund BK (2025-04-20)
Done 20/240 | players=39
Scraping lineups 21/240 | Vålerenga vs Rosenborg BK (2025-04-21)
Done 21/240 | players=40
Scraping lineups 22/240 | KFUM Oslo vs Sarpsborg 08 (2025-04-21)
Done 22/240 | players=39
Scraping lineups 23/240 | Bryne vs Haugesund (2025-04-21)
Done 23/240 | players=40
Scraping lineups 24/240 | Fredrikstad FK vs Sandefjord (2025-04-21)
Done 24/240 | players=40
Scraping lineups 25/240 | HamKam vs Viking FK (2025-04-21)
Done 25/240 | players=40
Scraping lineups 26/240 | Strømsgodset vs SK Brann (2025-04-21)
Done 26/240 | players=40
Scraping lineups 27/240 | Molde FK vs Bodø/Glimt (2025-04-21)
Done 27/240 | players=40
Scraping lineups 28/240 | Rosenborg BK vs Molde FK (2025-04-27)
Done 28/240 | players=40
Scraping lineups 29/240 | Bodø/Glimt vs KFUM Oslo (2025-04-27)
Done 29/240 | players=37
Scraping lineups 30/240 | SK Brann vs Bryne (2025-04-27)
Done 30/240 | players=40
Scraping lineups 31/240 | Haugesund vs Fredrikstad FK (2025-04-27)
Done 31/240 | players=40
Scraping lineups 32/240 | Kristiansund BK vs Vålerenga (2025-04-27)
Done 32/240 | players=40
Scraping lineups 33/240 | Sandefjord vs HamKam (2025-04-27)
Done 33/240 | players=40
Scraping lineups 34/240 | Sarpsborg 08 vs Strømsgodset (2025-04-27)
Done 34/240 | players=38
Scraping lineups 35/240 | Viking FK vs Tromsø IL (2025-04-27)
Done 35/240 | players=40
Scraping lineups 36/240 | Viking FK vs Haugesund (2025-04-30)
Done 36/240 | players=40
Scraping lineups 37/240 | Rosenborg BK vs Kristiansund BK (2025-05-01)
Done 37/240 | players=40
Scraping lineups 38/240 | HamKam vs KFUM Oslo (2025-05-02)
Done 38/240 | players=38
Scraping lineups 39/240 | Vålerenga vs SK Brann (2025-05-03)
Done 39/240 | players=38
Scraping lineups 40/240 | Molde FK vs Haugesund (2025-05-04)
Done 40/240 | players=40
Scraping lineups 41/240 | Strømsgodset vs Kristiansund BK (2025-05-04)
Done 41/240 | players=37
Scraping lineups 42/240 | Tromsø IL vs Sandefjord (2025-05-04)
Done 42/240 | players=38
Scraping lineups 43/240 | Viking FK vs Sarpsborg 08 (2025-05-04)
Done 43/240 | players=40
Scraping lineups 44/240 | Rosenborg BK vs Bryne (2025-05-04)
Done 44/240 | players=40
Scraping lineups 45/240 | SK Brann vs Rosenborg BK (2025-05-11)
Done 45/240 | players=40
Scraping lineups 46/240 | Bryne vs Molde FK (2025-05-11)
Done 46/240 | players=38
Scraping lineups 47/240 | KFUM Oslo vs Tromsø IL (2025-05-11)
Done 47/240 | players=40
Scraping lineups 48/240 | Kristiansund BK vs Fredrikstad FK (2025-05-11)
Done 48/240 | players=40
Scraping lineups 49/240 | Sandefjord vs Vålerenga (2025-05-11)
Done 49/240 | players=40
Scraping lineups 50/240 | Sarpsborg 08 vs HamKam (2025-05-11)
Done 50/240 | players=40
Scraping lineups 51/240 | Haugesund vs Viking FK (2025-05-11)
Done 51/240 | players=40
Scraping lineups 52/240 | SK Brann vs Sarpsborg 08 (2025-05-16)
Done 52/240 | players=40
Scraping lineups 53/240 | Fredrikstad FK vs KFUM Oslo (2025-05-16)
Done 53/240 | players=40
Scraping lineups 54/240 | Molde FK vs Kristiansund BK (2025-05-16)
Done 54/240 | players=40
Scraping lineups 55/240 | Rosenborg BK vs Haugesund (2025-05-16)
Done 55/240 | players=40
Scraping lineups 56/240 | Strømsgodset vs Bryne (2025-05-16)
Done 56/240 | players=39
Scraping lineups 57/240 | Tromsø IL vs Bodø/Glimt (2025-05-16)
Done 57/240 | players=40
Scraping lineups 58/240 | Viking FK vs Sandefjord (2025-05-16)
Done 58/240 | players=39
Scraping lineups 59/240 | Vålerenga vs HamKam (2025-05-16)
Done 59/240 | players=40
Scraping lineups 60/240 | Bryne vs Fredrikstad FK (2025-05-24)
Done 60/240 | players=37
Scraping lineups 61/240 | Bodø/Glimt vs Rosenborg BK (2025-05-24)
Done 61/240 | players=40
Scraping lineups 62/240 | HamKam vs Molde FK (2025-05-25)
Done 62/240 | players=38
Scraping lineups 63/240 | Kristiansund BK vs Viking FK (2025-05-25)
Done 63/240 | players=40
Scraping lineups 64/240 | Sandefjord vs Strømsgodset (2025-05-25)
Done 64/240 | players=39
Scraping lineups 65/240 | Sarpsborg 08 vs Tromsø IL (2025-05-25)
Done 65/240 | players=40
Scraping lineups 66/240 | Haugesund vs SK Brann (2025-05-25)
Done 66/240 | players=39
Scraping lineups 67/240 | KFUM Oslo vs Vålerenga (2025-05-26)
Done 67/240 | players=39
Scraping lineups 68/240 | Fredrikstad FK vs Rosenborg BK (2025-05-28)
Done 68/240 | players=40
Scraping lineups 69/240 | Bodø/Glimt vs Viking FK (2025-05-28)
Done 69/240 | players=40
Scraping lineups 70/240 | SK Brann vs Molde FK (2025-05-29)
Done 70/240 | players=38
Scraping lineups 71/240 | Strømsgodset vs HamKam (2025-05-31)
Done 71/240 | players=39
Scraping lineups 72/240 | Tromsø IL vs Vålerenga (2025-05-31)
Done 72/240 | players=36
Scraping lineups 73/240 | Fredrikstad FK vs Sarpsborg 08 (2025-06-01)
Done 73/240 | players=40
Scraping lineups 74/240 | SK Brann vs Kristiansund BK (2025-06-01)
Done 74/240 | players=38
Scraping lineups 75/240 | Bryne vs Sandefjord (2025-06-01)
Done 75/240 | players=39
Scraping lineups 76/240 | Haugesund vs Bodø/Glimt (2025-06-01)
Done 76/240 | players=40
Scraping lineups 77/240 | Rosenborg BK vs KFUM Oslo (2025-06-01)
Done 77/240 | players=40
Scraping lineups 78/240 | Molde FK vs Viking FK (2025-06-01)
Done 78/240 | players=40
Scraping lineups 79/240 | Bodø/Glimt vs SK Brann (2025-06-21)
Done 79/240 | players=38
Scraping lineups 80/240 | Vålerenga vs Molde FK (2025-06-22)
Done 80/240 | players=40
Scraping lineups 81/240 | HamKam vs Tromsø IL (2025-06-22)
Done 81/240 | players=39
Scraping lineups 82/240 | KFUM Oslo vs Strømsgodset (2025-06-22)
Done 82/240 | players=38
Scraping lineups 83/240 | Kristiansund BK vs Rosenborg BK (2025-06-22)
Done 83/240 | players=40
Scraping lineups 84/240 | Sandefjord vs Haugesund (2025-06-22)
Done 84/240 | players=37
Scraping lineups 85/240 | Sarpsborg 08 vs Bryne (2025-06-22)
Done 85/240 | players=39
Scraping lineups 86/240 | Viking FK vs Fredrikstad FK (2025-06-22)
Done 86/240 | players=40
Scraping lineups 87/240 | Rosenborg BK vs Viking FK (2025-06-28)
Done 87/240 | players=40
Scraping lineups 88/240 | Haugesund vs Kristiansund BK (2025-06-29)
Done 88/240 | players=40
Scraping lineups 89/240 | Bodø/Glimt vs Sarpsborg 08 (2025-06-29)
Done 89/240 | players=40
Scraping lineups 90/240 | Bryne vs HamKam (2025-06-29)
Done 90/240 | players=39
Scraping lineups 91/240 | Fredrikstad FK vs Tromsø IL (2025-06-29)
Done 91/240 | players=38
Scraping lineups 92/240 | Molde FK vs KFUM Oslo (2025-06-29)
Done 92/240 | players=40
Scraping lineups 93/240 | Strømsgodset vs Vålerenga (2025-06-29)
Done 93/240 | players=38
Scraping lineups 94/240 | SK Brann vs Sandefjord (2025-06-30)
Done 94/240 | players=38
Scraping lineups 95/240 | HamKam vs SK Brann (2025-07-05)
Done 95/240 | players=38
Scraping lineups 96/240 | Viking FK vs Strømsgodset (2025-07-05)
Done 96/240 | players=37
Scraping lineups 97/240 | Vålerenga vs Fredrikstad FK (2025-07-05)
Done 97/240 | players=40
Scraping lineups 98/240 | Kristiansund BK vs Bodø/Glimt (2025-07-05)
Done 98/240 | players=40
Scraping lineups 99/240 | Tromsø IL vs Molde FK (2025-07-05)
Done 99/240 | players=38
Scraping lineups 100/240 | KFUM Oslo vs Bryne (2025-07-06)
Done 100/240 | players=38
Scraping lineups 101/240 | Sandefjord vs Rosenborg BK (2025-07-06)
Done 101/240 | players=40
Scraping lineups 102/240 | Sarpsborg 08 vs Haugesund (2025-07-06)
Done 102/240 | players=39
Scraping lineups 103/240 | Bodø/Glimt vs Sandefjord (2025-07-12)
Done 103/240 | players=39
Scraping lineups 104/240 | Fredrikstad FK vs Molde FK (2025-07-12)
Done 104/240 | players=40
Scraping lineups 105/240 | Bryne vs Vålerenga (2025-07-13)
Done 105/240 | players=38
Scraping lineups 106/240 | Haugesund vs KFUM Oslo (2025-07-13)
Done 106/240 | players=39
Scraping lineups 107/240 | Kristiansund BK vs Sarpsborg 08 (2025-07-13)
Done 107/240 | players=40
Scraping lineups 108/240 | Rosenborg BK vs HamKam (2025-07-13)
Done 108/240 | players=38
Scraping lineups 109/240 | Strømsgodset vs Tromsø IL (2025-07-13)
Done 109/240 | players=36
Scraping lineups 110/240 | SK Brann vs Viking FK (2025-07-13)
Done 110/240 | players=39
Scraping lineups 111/240 | Fredrikstad FK vs Bodø/Glimt (2025-07-16)
Done 111/240 | players=40
Scraping lineups 112/240 | Sarpsborg 08 vs Rosenborg BK (2025-07-18)
Done 112/240 | players=40
Scraping lineups 113/240 | KFUM Oslo vs SK Brann (2025-07-19)
Done 113/240 | players=38
Scraping lineups 114/240 | Molde FK vs Strømsgodset (2025-07-19)
Done 114/240 | players=39
Scraping lineups 115/240 | Viking FK vs Bodø/Glimt (2025-07-19)
Done 115/240 | players=40
Scraping lineups 116/240 | Vålerenga vs Haugesund (2025-07-20)
Done 116/240 | players=38
Scraping lineups 117/240 | Sandefjord vs Kristiansund BK (2025-07-20)
Done 117/240 | players=38
Scraping lineups 118/240 | Tromsø IL vs Bryne (2025-07-20)
Done 118/240 | players=38
Scraping lineups 119/240 | HamKam vs Fredrikstad FK (2025-07-20)
Done 119/240 | players=40
Scraping lineups 120/240 | Fredrikstad FK vs Strømsgodset (2025-07-25)
Done 120/240 | players=40
Scraping lineups 121/240 | Haugesund vs HamKam (2025-07-26)
Done 121/240 | players=39
Scraping lineups 122/240 | Kristiansund BK vs KFUM Oslo (2025-07-26)
Done 122/240 | players=39
Scraping lineups 123/240 | Sandefjord vs Sarpsborg 08 (2025-07-26)
Done 123/240 | players=40
Scraping lineups 124/240 | Bodø/Glimt vs Vålerenga (2025-07-26)
Done 124/240 | players=38
Scraping lineups 125/240 | Bryne vs Viking FK (2025-07-27)
Done 125/240 | players=39
Scraping lineups 126/240 | Rosenborg BK vs Tromsø IL (2025-07-27)
Done 126/240 | players=40
Scraping lineups 127/240 | Bodø/Glimt vs Strømsgodset (2025-07-30)
Done 127/240 | players=39
Scraping lineups 128/240 | Tromsø IL vs Fredrikstad FK (2025-08-02)
Done 128/240 | players=38
Scraping lineups 129/240 | Sarpsborg 08 vs SK Brann (2025-08-02)
Done 129/240 | players=39
Scraping lineups 130/240 | HamKam vs Bodø/Glimt (2025-08-03)
Done 130/240 | players=39
Scraping lineups 131/240 | KFUM Oslo vs Rosenborg BK (2025-08-03)
Done 131/240 | players=39
Scraping lineups 132/240 | Molde FK vs Bryne (2025-08-03)
Done 132/240 | players=38
Scraping lineups 133/240 | Strømsgodset vs Haugesund (2025-08-03)
Done 133/240 | players=37
Scraping lineups 134/240 | Vålerenga vs Sandefjord (2025-08-03)
Done 134/240 | players=38
Scraping lineups 135/240 | Molde FK vs HamKam (2025-08-09)
Done 135/240 | players=38
Scraping lineups 136/240 | Bodø/Glimt vs Tromsø IL (2025-08-09)
Done 136/240 | players=39
Scraping lineups 137/240 | Bryne vs KFUM Oslo (2025-08-10)
Done 137/240 | players=40
Scraping lineups 138/240 | Haugesund vs Sarpsborg 08 (2025-08-10)
Done 138/240 | players=40
Scraping lineups 139/240 | Sandefjord vs Viking FK (2025-08-10)
Done 139/240 | players=40
Scraping lineups 140/240 | Strømsgodset vs Bodø/Glimt (2025-08-15)
Done 140/240 | players=40
Scraping lineups 141/240 | Tromsø IL vs SK Brann (2025-08-17)
Done 141/240 | players=40
Scraping lineups 142/240 | HamKam vs Bryne (2025-08-17)
Done 142/240 | players=38
Scraping lineups 143/240 | KFUM Oslo vs Molde FK (2025-08-17)
Done 143/240 | players=38
Scraping lineups 144/240 | Kristiansund BK vs Sandefjord (2025-08-17)
Done 144/240 | players=39
Scraping lineups 145/240 | Vålerenga vs Sarpsborg 08 (2025-08-17)
Done 145/240 | players=40
Scraping lineups 146/240 | KFUM Oslo vs HamKam (2025-08-22)
Done 146/240 | players=39
Scraping lineups 147/240 | Haugesund vs Vålerenga (2025-08-24)
Done 147/240 | players=38
Scraping lineups 148/240 | Bryne vs Strømsgodset (2025-08-24)
Done 148/240 | players=38
Scraping lineups 149/240 | Molde FK vs Tromsø IL (2025-08-24)
Done 149/240 | players=39
Scraping lineups 150/240 | Sarpsborg 08 vs Kristiansund BK (2025-08-25)
Done 150/240 | players=39
Scraping lineups 151/240 | Vålerenga vs Bryne (2025-08-30)
Done 151/240 | players=38
Scraping lineups 152/240 | Kristiansund BK vs SK Brann (2025-08-31)
Done 152/240 | players=39
Scraping lineups 153/240 | Fredrikstad FK vs Haugesund (2025-08-31)
Done 153/240 | players=39
Scraping lineups 154/240 | HamKam vs Sarpsborg 08 (2025-08-31)
Done 154/240 | players=40
Scraping lineups 155/240 | Sandefjord vs Bodø/Glimt (2025-08-31)
Done 155/240 | players=38
Scraping lineups 156/240 | Tromsø IL vs KFUM Oslo (2025-08-31)
Done 156/240 | players=39
Scraping lineups 157/240 | Viking FK vs Rosenborg BK (2025-08-31)
Done 157/240 | players=40
Scraping lineups 158/240 | Strømsgodset vs Molde FK (2025-08-31)
Done 158/240 | players=39
Scraping lineups 159/240 | Bodø/Glimt vs Kristiansund BK (2025-09-12)
Done 159/240 | players=39
Scraping lineups 160/240 | Molde FK vs Fredrikstad FK (2025-09-13)
Done 160/240 | players=40
Scraping lineups 161/240 | SK Brann vs Vålerenga (2025-09-13)
Done 161/240 | players=38
Scraping lineups 162/240 | Bryne vs Tromsø IL (2025-09-14)
Done 162/240 | players=39
Scraping lineups 163/240 | HamKam vs Strømsgodset (2025-09-14)
Done 163/240 | players=40
Scraping lineups 164/240 | KFUM Oslo vs Viking FK (2025-09-14)
Done 164/240 | players=39
Scraping lineups 165/240 | Sarpsborg 08 vs Sandefjord (2025-09-14)
Done 165/240 | players=40
Scraping lineups 166/240 | Haugesund vs Rosenborg BK (2025-09-14)
Done 166/240 | players=40
Scraping lineups 167/240 | Fredrikstad FK vs Bryne (2025-09-20)
Done 167/240 | players=38
Scraping lineups 168/240 | Sandefjord vs SK Brann (2025-09-20)
Done 168/240 | players=39
Scraping lineups 169/240 | Vålerenga vs KFUM Oslo (2025-09-20)
Done 169/240 | players=40
Scraping lineups 170/240 | Rosenborg BK vs Bodø/Glimt (2025-09-21)
Done 170/240 | players=37
Scraping lineups 171/240 | Kristiansund BK vs Haugesund (2025-09-21)
Done 171/240 | players=38
Scraping lineups 172/240 | Strømsgodset vs Sarpsborg 08 (2025-09-21)
Done 172/240 | players=39
Scraping lineups 173/240 | Tromsø IL vs HamKam (2025-09-21)
Done 173/240 | players=37
Scraping lineups 174/240 | Viking FK vs Molde FK (2025-09-21)
Done 174/240 | players=40
Scraping lineups 175/240 | Sarpsborg 08 vs Viking FK (2025-09-27)
Done 175/240 | players=40
Scraping lineups 176/240 | SK Brann vs Fredrikstad FK (2025-09-28)
Done 176/240 | players=40
Scraping lineups 177/240 | Bryne vs Kristiansund BK (2025-09-28)
Done 177/240 | players=39
Scraping lineups 178/240 | HamKam vs Rosenborg BK (2025-09-28)
Done 178/240 | players=40
Scraping lineups 179/240 | Tromsø IL vs Strømsgodset (2025-09-28)
Done 179/240 | players=38
Scraping lineups 180/240 | Molde FK vs Vålerenga (2025-09-28)
Done 180/240 | players=38
Scraping lineups 181/240 | Haugesund vs Sandefjord (2025-09-29)
Done 181/240 | players=39
Scraping lineups 182/240 | KFUM Oslo vs Fredrikstad FK (2025-10-01)
Done 182/240 | players=40
Scraping lineups 183/240 | Vålerenga vs Tromsø IL (2025-10-04)
Done 183/240 | players=40
Scraping lineups 184/240 | Sandefjord vs Bryne (2025-10-04)
Done 184/240 | players=39
Scraping lineups 185/240 | Kristiansund BK vs Molde FK (2025-10-04)
Done 185/240 | players=40
Scraping lineups 186/240 | Viking FK vs SK Brann (2025-10-05)
Done 186/240 | players=40
Scraping lineups 187/240 | Bodø/Glimt vs Haugesund (2025-10-05)
Done 187/240 | players=38
Scraping lineups 188/240 | Fredrikstad FK vs HamKam (2025-10-05)
Done 188/240 | players=40
Scraping lineups 189/240 | Strømsgodset vs KFUM Oslo (2025-10-05)
Done 189/240 | players=39
Scraping lineups 190/240 | Rosenborg BK vs Sarpsborg 08 (2025-10-05)
Done 190/240 | players=40
Scraping lineups 191/240 | Sarpsborg 08 vs Bodø/Glimt (2025-10-18)
Done 191/240 | players=40
Scraping lineups 192/240 | Bryne vs Rosenborg BK (2025-10-18)
Done 192/240 | players=40
Scraping lineups 193/240 | SK Brann vs Haugesund (2025-10-18)
Done 193/240 | players=40
Scraping lineups 194/240 | Tromsø IL vs Viking FK (2025-10-19)
Done 194/240 | players=40
Scraping lineups 195/240 | HamKam vs Vålerenga (2025-10-19)
Done 195/240 | players=40
Scraping lineups 196/240 | KFUM Oslo vs Kristiansund BK (2025-10-19)
Done 196/240 | players=39
Scraping lineups 197/240 | Molde FK vs Sandefjord (2025-10-19)
Done 197/240 | players=39
Scraping lineups 198/240 | Strømsgodset vs Fredrikstad FK (2025-10-19)
Done 198/240 | players=40
Scraping lineups 199/240 | Viking FK vs Bryne (2025-10-25)
Done 199/240 | players=40
Scraping lineups 200/240 | Sarpsborg 08 vs KFUM Oslo (2025-10-25)
Done 200/240 | players=39
Scraping lineups 201/240 | Rosenborg BK vs SK Brann (2025-10-26)
Done 201/240 | players=38
Scraping lineups 202/240 | Bodø/Glimt vs Molde FK (2025-10-26)
Done 202/240 | players=40
Scraping lineups 203/240 | Haugesund vs Tromsø IL (2025-10-26)
Done 203/240 | players=37
Scraping lineups 204/240 | Kristiansund BK vs HamKam (2025-10-26)
Done 204/240 | players=38
Scraping lineups 205/240 | Sandefjord vs Fredrikstad FK (2025-10-26)
Done 205/240 | players=40
Scraping lineups 206/240 | Vålerenga vs Strømsgodset (2025-10-26)
Done 206/240 | players=38
Scraping lineups 207/240 | Rosenborg BK vs Sandefjord (2025-10-29)
Done 207/240 | players=39
Scraping lineups 208/240 | SK Brann vs Bodø/Glimt (2025-10-29)
Done 208/240 | players=40
Scraping lineups 209/240 | Vålerenga vs Bodø/Glimt (2025-11-01)
Done 209/240 | players=40
Scraping lineups 210/240 | Molde FK vs Rosenborg BK (2025-11-01)
Done 210/240 | players=40
Scraping lineups 211/240 | Strømsgodset vs Viking FK (2025-11-02)
Done 211/240 | players=40
Scraping lineups 212/240 | Bryne vs SK Brann (2025-11-02)
Done 212/240 | players=40
Scraping lineups 213/240 | Fredrikstad FK vs Kristiansund BK (2025-11-02)
Done 213/240 | players=40
Scraping lineups 214/240 | HamKam vs Sandefjord (2025-11-02)
Done 214/240 | players=39
Scraping lineups 215/240 | KFUM Oslo vs Haugesund (2025-11-02)
Done 215/240 | players=36
Scraping lineups 216/240 | Tromsø IL vs Sarpsborg 08 (2025-11-02)
Done 216/240 | players=40
Scraping lineups 217/240 | Sarpsborg 08 vs Fredrikstad FK (2025-11-08)
Done 217/240 | players=39
Scraping lineups 218/240 | Viking FK vs HamKam (2025-11-08)
Done 218/240 | players=39
Scraping lineups 219/240 | Rosenborg BK vs Vålerenga (2025-11-09)
Done 219/240 | players=40
Scraping lineups 220/240 | Bodø/Glimt vs Bryne (2025-11-09)
Done 220/240 | players=37
Scraping lineups 221/240 | SK Brann vs KFUM Oslo (2025-11-09)
Done 221/240 | players=39
Scraping lineups 222/240 | Kristiansund BK vs Strømsgodset (2025-11-09)
Done 222/240 | players=39

In [6]:
# List all table names
db_path = Path("data/brann.duckdb")
con = duckdb.connect(str(db_path))
table_names = con.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'main'").fetchall()
print("Available tables:")
for table in table_names:
    print(f"  - {table[0]}")
con.close()

Available tables:
  - dim_teams
  - fct_league_standings
  - fct_matches
  - raw_eliterserien_goal_contributions_2024
  - raw_eliterserien_goal_contributions_2025
  - raw_eliterserien_goal_contributions_2026
  - raw_eliterserien_lineups_2025
  - raw_eliterserien_lineups_2026
  - raw_eliteserien_results_2021
  - raw_eliteserien_results_2022
  - raw_eliteserien_results_2023
  - raw_eliteserien_results_2024
  - raw_eliteserien_results_2025
  - raw_eliteserien_results_2026
  - raw_match_statistics_2021
  - raw_match_statistics_2022
  - raw_match_statistics_2023
  - raw_match_statistics_2024
  - raw_match_statistics_2025
  - raw_match_statistics_2026

In [7]:
con = duckdb.connect(str(Path(db_path)))
pl.from_arrow(con.execute("select * FROM raw_eliterserien_goal_contributions_2025").arrow())

shape: (765, 16)
┌────────┬────────────┬────────────┬────────────┬───┬───────┬────────────┬────────────┬────────────┐
│ season ┆ date       ┆ home_team  ┆ away_team  ┆ … ┆ score ┆ report_url ┆ snapshot_a ┆ ingested_a │
│ ---    ┆ ---        ┆ ---        ┆ ---        ┆   ┆ ---   ┆ ---        ┆ t          ┆ t          │
│ i64    ┆ date       ┆ str        ┆ str        ┆   ┆ str   ┆ str        ┆ ---        ┆ ---        │
│        ┆            ┆            ┆            ┆   ┆       ┆            ┆ datetime[μ ┆ datetime[μ │
│        ┆            ┆            ┆            ┆   ┆       ┆            ┆ s, Europe/ ┆ s]         │
│        ┆            ┆            ┆            ┆   ┆       ┆            ┆ Oslo]      ┆            │
╞════════╪════════════╪════════════╪════════════╪═══╪═══════╪════════════╪════════════╪════════════╡
│ 2025   ┆ 2025-03-29 ┆ Strømsgods ┆ Rosenborg  ┆ … ┆ 0:1   ┆ https://ww ┆ 2026-09-28 ┆ 2026-09-28 │
│        ┆            ┆ et         ┆ BK         ┆   ┆       ┆ w.transfer ┆ 14:28:34.3 ┆ 14:30:44.6 │
│        ┆            ┆            ┆            ┆   ┆       ┆ markt.com/ ┆ 40409 CES… ┆ 22521      │
│        ┆            ┆            ┆            ┆   ┆       ┆ …          ┆            ┆            │
│ 2025   ┆ 2025-03-29 ┆ Strømsgods ┆ Rosenborg  ┆ … ┆ 0:2   ┆ https://ww ┆ 2026-09-28 ┆ 2026-09-28 │
│        ┆            ┆ et         ┆ BK         ┆   ┆       ┆ w.transfer ┆ 14:28:34.3 ┆ 14:30:44.6 │
│        ┆            ┆            ┆            ┆   ┆       ┆ markt.com/ ┆ 40409 CES… ┆ 22521      │
│        ┆            ┆            ┆            ┆   ┆       ┆ …          ┆            ┆            │
│ 2025   ┆ 2025-03-29 ┆ Strømsgods ┆ Rosenborg  ┆ … ┆ 1:2   ┆ https://ww ┆ 2026-09-28 ┆ 2026-09-28 │
│        ┆            ┆ et         ┆ BK         ┆   ┆       ┆ w.transfer ┆ 14:28:34.3 ┆ 14:30:44.6 │
│        ┆            ┆            ┆            ┆   ┆       ┆ markt.com/ ┆ 40409 CES… ┆ 22521      │
│        ┆            ┆            ┆            ┆   ┆       ┆ …          ┆            ┆            │
│ 2025   ┆ 2025-03-29 ┆ Fredriksta ┆ SK Brann   ┆ … ┆ 1:0   ┆ https://ww ┆ 2026-09-28 ┆ 2026-09-28 │
│        ┆            ┆ d FK       ┆            ┆   ┆       ┆ w.transfer ┆ 14:28:34.3 ┆ 14:30:44.6 │
│        ┆            ┆            ┆            ┆   ┆       ┆ markt.com/ ┆ 40409 CES… ┆ 22521      │
│        ┆            ┆            ┆            ┆   ┆       ┆ …          ┆            ┆            │
│ 2025   ┆ 2025-03-29 ┆ Fredriksta ┆ SK Brann   ┆ … ┆ 2:0   ┆ https://ww ┆ 2026-09-28 ┆ 2026-09-28 │
│        ┆            ┆ d FK       ┆            ┆   ┆       ┆ w.transfer ┆ 14:28:34.3 ┆ 14:30:44.6 │
│        ┆            ┆            ┆            ┆   ┆       ┆ markt.com/ ┆ 40409 CES… ┆ 22521      │
│        ┆            ┆            ┆            ┆   ┆       ┆ …          ┆            ┆            │
│ …      ┆ …          ┆ …          ┆ …          ┆ … ┆ …     ┆ …          ┆ …          ┆ …          │
│ 2025   ┆ 2025-11-30 ┆ Viking FK  ┆ Vålerenga  ┆ … ┆ 2:0   ┆ https://ww ┆ 2026-09-28 ┆ 2026-09-28 │
│        ┆            ┆            ┆            ┆   ┆       ┆ w.transfer ┆ 14:28:34.3 ┆ 14:30:44.6 │
│        ┆            ┆            ┆            ┆   ┆       ┆ markt.com/ ┆ 40409 CES… ┆ 22521      │
│        ┆            ┆            ┆            ┆   ┆       ┆ …          ┆            ┆            │
│ 2025   ┆ 2025-11-30 ┆ Viking FK  ┆ Vålerenga  ┆ … ┆ 3:0   ┆ https://ww ┆ 2026-09-28 ┆ 2026-09-28 │
│        ┆            ┆            ┆            ┆   ┆       ┆ w.transfer ┆ 14:28:34.3 ┆ 14:30:44.6 │
│        ┆            ┆            ┆            ┆   ┆       ┆ markt.com/ ┆ 40409 CES… ┆ 22521      │
│        ┆            ┆            ┆            ┆   ┆       ┆ …          ┆            ┆            │
│ 2025   ┆ 2025-11-30 ┆ Viking FK  ┆ Vålerenga  ┆ … ┆ 3:1   ┆ https://ww ┆ 2026-09-28 ┆ 2026-09-28 │
│        ┆            ┆            ┆            ┆   ┆       ┆ w.transfer ┆ 14:28:34.3 ┆ 14:30:44.6 │
│        ┆            ┆            ┆            ┆   ┆       ┆ markt.com/ ┆ 40409 CES… ┆ 22521      │
│        ┆            ┆            ┆            ┆   ┆       ┆ …          ┆            ┆            │
│ 2025   ┆ 2025-11-30 ┆ Viking FK  ┆ Vålerenga  ┆ … ┆ 4:1   ┆ https://ww ┆ 2026-09-28 ┆ 2026-09-28 │
│        ┆            ┆            ┆            ┆   ┆       ┆ w.transfer ┆ 14:28:34.3 ┆ 14:30:44.6 │
│        ┆            ┆            ┆            ┆   ┆       ┆ markt.com/ ┆ 40409 CES… ┆ 22521      │
│        ┆            ┆            ┆            ┆   ┆       ┆ …          ┆            ┆            │
│ 2025   ┆ 2025-11-30 ┆ Viking FK  ┆ Vålerenga  ┆ … ┆ 5:1   ┆ https://ww ┆ 2026-09-28 ┆ 2026-09-28 │
│        ┆            ┆            ┆            ┆   ┆       ┆ w.transfer ┆ 14:28:34.3 ┆ 14:30:44.6 │
│        ┆            ┆            ┆            ┆   ┆       ┆ markt.com/ ┆ 40409 CES… ┆ 22521      │
│        ┆            ┆            ┆            ┆   ┆       ┆ …          ┆            ┆            │
└────────┴────────────┴────────────┴────────────┴───┴───────┴────────────┴────────────┴────────────┘

In [3]:
def hent_tabell_som_polars(table_name: str, db_path: str | Path = "data/brann.duckdb") -> pl.DataFrame:
    """
    Henter en tabell fra en DuckDB-database og returnerer den som en Polars DataFrame.

    Args:
        table_name: Navnet på tabellen som skal hentes.
        db_path: Sti til DuckDB-databasen (default: "data/brann.duckdb").

    Returns:
        Polars DataFrame med innholdet fra tabellen.
    """
    con = duckdb.connect(str(Path(db_path)))
    try:
        arrow_table = con.execute(f"SELECT * FROM {table_name}").arrow()
        df = pl.from_arrow(arrow_table)
    finally:
        con.close()
    return df

In [12]:
col_2023 = hent_tabell_som_polars("raw_match_statistics_2024").columns
col_2024 = hent_tabell_som_polars("raw_match_statistics_2025").columns

In [8]:
con = duckdb.connect(str(Path(db_path)))
con.execute("SELECT * FROM raw_match_statistics_2024 union all by name select * FROM raw_match_statistics_2025")