In [1]:
import polars as pl 
import polars_ds as pds 
import requests 
import json 
import duckdb
from pathlib import Path
from src.utils import scrape_ticket_sections, get_available_events, scrape_match_results, scrape_eliteserien_results,create_table_after_round

In [2]:
from importlib import reload
import src.utils as u
reload(u)

rows = u.scrape_eliteserien_all_xg_for_season(
season_id=2025,
year=2026,
delay_seconds=0
)

In [3]:
import polars as pl 
pl.DataFrame(rows).filter(pl.col('home_team') == 'SK Brann').tail(1)

shape: (1, 89)
┌────────┬────────────┬──────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ season ┆ date       ┆ matchday ┆ home_team ┆ … ┆ home_freek ┆ away_freek ┆ home_yell ┆ away_yell │
│ ---    ┆ ---        ┆ ---      ┆ ---       ┆   ┆ icks_2nd   ┆ icks_2nd   ┆ owcards_2 ┆ owcards_2 │
│ i64    ┆ date       ┆ i64      ┆ str       ┆   ┆ ---        ┆ ---        ┆ nd        ┆ nd        │
│        ┆            ┆          ┆           ┆   ┆ i64        ┆ i64        ┆ ---       ┆ ---       │
│        ┆            ┆          ┆           ┆   ┆            ┆            ┆ i64       ┆ i64       │
╞════════╪════════════╪══════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 2026   ┆ 2026-09-05 ┆ 20       ┆ SK Brann  ┆ … ┆ 1          ┆ 5          ┆ 0         ┆ 1         │
└────────┴────────────┴──────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [2]:
# List all table names
db_path = Path("data/brann.duckdb")
con = duckdb.connect(str(db_path))
table_names = con.execute("SELECT table_name FROM information_schema.tables WHERE table_schema = 'main'").fetchall()
print("Available tables:")
for table in table_names:
    print(f"  - {table[0]}")
con.close()

Available tables:
  - dim_teams
  - fct_goal_scorers
  - fct_league_standings
  - fct_matches
  - raw_eliteserien_goal_scorers
  - raw_eliteserien_results

In [25]:
con = duckdb.connect('data/brann.duckdb')
goal_scorers = pl.from_arrow(con.execute(
    """
    SELECT *
FROM fct_goal_scorers
""").arrow())
con.close()
goal_scorers

shape: (8_158, 9)
┌────────┬────────────┬──────────┬─────────────┬───┬────────┬────────────┬────────────┬────────────┐
│ season ┆ date       ┆ matchday ┆ home_team   ┆ … ┆ result ┆ scorer_tea ┆ scorer_nam ┆ ingested_a │
│ ---    ┆ ---        ┆ ---      ┆ ---         ┆   ┆ ---    ┆ m          ┆ e          ┆ t          │
│ i64    ┆ date       ┆ i64      ┆ str         ┆   ┆ str    ┆ ---        ┆ ---        ┆ ---        │
│        ┆            ┆          ┆             ┆   ┆        ┆ str        ┆ str        ┆ datetime[μ │
│        ┆            ┆          ┆             ┆   ┆        ┆            ┆            ┆ s]         │
╞════════╪════════════╪══════════╪═════════════╪═══╪════════╪════════════╪════════════╪════════════╡
│ 2015   ┆ 2015-04-06 ┆ 1        ┆ Sandefjord  ┆ … ┆ 3:1    ┆ FK         ┆ H.         ┆ 2026-09-04 │
│        ┆            ┆          ┆             ┆   ┆        ┆ Bodø/Glimt ┆ Furebotn   ┆ 14:29:08.5 │
│        ┆            ┆          ┆             ┆   ┆        ┆            ┆            ┆ 23745      │
│ 2015   ┆ 2015-04-06 ┆ 1        ┆ Mjøndalen   ┆ … ┆ 1:0    ┆ Mjøndalen  ┆ S.         ┆ 2026-09-04 │
│        ┆            ┆          ┆             ┆   ┆        ┆ IF         ┆ Kapidzic   ┆ 14:29:08.5 │
│        ┆            ┆          ┆             ┆   ┆        ┆            ┆            ┆ 23745      │
│ 2015   ┆ 2015-04-06 ┆ 1        ┆ Sandefjord  ┆ … ┆ 3:1    ┆ Sandefjord ┆ A.         ┆ 2026-09-04 │
│        ┆            ┆          ┆             ┆   ┆        ┆ Fotball    ┆ Gabrielsen ┆ 14:29:08.5 │
│        ┆            ┆          ┆             ┆   ┆        ┆            ┆            ┆ 23745      │
│ 2015   ┆ 2015-04-06 ┆ 1        ┆ Sandefjord  ┆ … ┆ 3:1    ┆ Sandefjord ┆ J. Mendy   ┆ 2026-09-04 │
│        ┆            ┆          ┆             ┆   ┆        ┆ Fotball    ┆            ┆ 14:29:08.5 │
│        ┆            ┆          ┆             ┆   ┆        ┆            ┆            ┆ 23745      │
│ 2015   ┆ 2015-04-06 ┆ 1        ┆ Sandefjord  ┆ … ┆ 3:1    ┆ Sandefjord ┆ J. Mendy   ┆ 2026-09-04 │
│        ┆            ┆          ┆             ┆   ┆        ┆ Fotball    ┆            ┆ 14:29:08.5 │
│        ┆            ┆          ┆             ┆   ┆        ┆            ┆            ┆ 23745      │
│ …      ┆ …          ┆ …        ┆ …           ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ 2026   ┆ 2026-09-06 ┆ 20       ┆ Molde FK    ┆ … ┆ 2:0    ┆ Molde FK   ┆ T. Koné-Do ┆ 2026-09-08 │
│        ┆            ┆          ┆             ┆   ┆        ┆            ┆ herty      ┆ 09:13:42.5 │
│        ┆            ┆          ┆             ┆   ┆        ┆            ┆            ┆ 36941      │
│ 2026   ┆ 2026-09-06 ┆ 20       ┆ Sarpsborg   ┆ … ┆ 2:2    ┆ Sarpsborg  ┆ C.         ┆ 2026-09-08 │
│        ┆            ┆          ┆ 08          ┆   ┆        ┆ 08 FF      ┆ Niyukuri   ┆ 09:13:42.5 │
│        ┆            ┆          ┆             ┆   ┆        ┆            ┆            ┆ 36941      │
│ 2026   ┆ 2026-09-06 ┆ 20       ┆ Sarpsborg   ┆ … ┆ 2:2    ┆ Sarpsborg  ┆ S. Sørli   ┆ 2026-09-08 │
│        ┆            ┆          ┆ 08          ┆   ┆        ┆ 08 FF      ┆            ┆ 09:13:42.5 │
│        ┆            ┆          ┆             ┆   ┆        ┆            ┆            ┆ 36941      │
│ 2026   ┆ 2026-09-06 ┆ 20       ┆ Sarpsborg   ┆ … ┆ 2:2    ┆ Vålerenga  ┆ G.         ┆ 2026-09-08 │
│        ┆            ┆          ┆ 08          ┆   ┆        ┆ Fotball    ┆ Rajković   ┆ 09:13:42.5 │
│        ┆            ┆          ┆             ┆   ┆        ┆ Elite      ┆            ┆ 36941      │
│ 2026   ┆ 2026-09-06 ┆ 20       ┆ Sarpsborg   ┆ … ┆ 2:2    ┆ Vålerenga  ┆ P. Strand  ┆ 2026-09-08 │
│        ┆            ┆          ┆ 08          ┆   ┆        ┆ Fotball    ┆            ┆ 09:13:42.5 │
│        ┆            ┆          ┆             ┆   ┆        ┆ Elite      ┆            ┆ 36941      │
└────────┴────────────┴──────────┴─────────────┴───┴────────┴────────────┴────────────┴────────────┘

In [2]:
con = duckdb.connect('data/brann.duckdb')
latest = pl.from_arrow(con.execute("""
    SELECT * FROM fct_league_standings 
""").arrow())
con.close()

latest

shape: (5_568, 8)
┌────────┬──────────┬─────────────┬─────────────┬─────────────┬────────────┬────────────┬──────────┐
│ season ┆ matchday ┆ team        ┆ total_point ┆ total_goals ┆ total_goal ┆ goal_diffe ┆ position │
│ ---    ┆ ---      ┆ ---         ┆ s           ┆ _for        ┆ s_against  ┆ rence      ┆ ---      │
│ i64    ┆ i64      ┆ str         ┆ ---         ┆ ---         ┆ ---        ┆ ---        ┆ i64      │
│        ┆          ┆             ┆ decimal[38, ┆ decimal[38, ┆ decimal[38 ┆ decimal[38 ┆          │
│        ┆          ┆             ┆ 0]          ┆ 0]          ┆ ,0]        ┆ ,0]        ┆          │
╞════════╪══════════╪═════════════╪═════════════╪═════════════╪════════════╪════════════╪══════════╡
│ 2026   ┆ 19       ┆ Bodø/Glimt  ┆ 44          ┆ 47          ┆ 14         ┆ 33         ┆ 1        │
│ 2026   ┆ 19       ┆ Viking FK   ┆ 43          ┆ 42          ┆ 18         ┆ 24         ┆ 2        │
│ 2026   ┆ 19       ┆ Tromsø IL   ┆ 35          ┆ 34          ┆ 20         ┆ 14         ┆ 3        │
│ 2026   ┆ 19       ┆ Molde FK    ┆ 30          ┆ 36          ┆ 29         ┆ 7          ┆ 4        │
│ 2026   ┆ 19       ┆ SK Brann    ┆ 26          ┆ 36          ┆ 27         ┆ 9          ┆ 5        │
│ …      ┆ …        ┆ …           ┆ …           ┆ …           ┆ …          ┆ …          ┆ …        │
│ 2015   ┆ 1        ┆ Viking FK   ┆ 0           ┆ 0           ┆ 1          ┆ -1         ┆ 12       │
│ 2015   ┆ 1        ┆ Tromsø IL   ┆ 0           ┆ 0           ┆ 1          ┆ -1         ┆ 13       │
│ 2015   ┆ 1        ┆ Bodø/Glimt  ┆ 0           ┆ 1           ┆ 3          ┆ -2         ┆ 14       │
│ 2015   ┆ 1        ┆ Strømsgodse ┆ 0           ┆ 1           ┆ 3          ┆ -2         ┆ 15       │
│        ┆          ┆ t           ┆             ┆             ┆            ┆            ┆          │
│ 2015   ┆ 1        ┆ Aalesunds   ┆ 0           ┆ 0           ┆ 5          ┆ -5         ┆ 16       │
│        ┆          ┆ FK          ┆             ┆             ┆            ┆            ┆          │
└────────┴──────────┴─────────────┴─────────────┴─────────────┴────────────┴────────────┴──────────┘

In [3]:


# Connect to DuckDB and read raw_eliteserien_results
db_path = Path("data/brann.duckdb")
con = duckdb.connect(str(db_path))
eliteserien_db = pl.from_arrow(con.execute("SELECT * FROM dim_teams").arrow())
con.close()

print(f"Loaded {len(eliteserien_db)} records from DuckDB")
eliteserien_db

Loaded 192 records from DuckDB

shape: (192, 2)
┌────────┬───────────────┐
│ season ┆ team_name     │
│ ---    ┆ ---           │
│ i64    ┆ str           │
╞════════╪═══════════════╡
│ 2015   ┆ Aalesunds FK  │
│ 2015   ┆ Bodø/Glimt    │
│ 2015   ┆ Haugesund     │
│ 2015   ┆ IK Start      │
│ 2015   ┆ Lillestrøm SK │
│ …      ┆ …             │
│ 2026   ┆ Sandefjord    │
│ 2026   ┆ Sarpsborg 08  │
│ 2026   ┆ Tromsø IL     │
│ 2026   ┆ Viking FK     │
│ 2026   ┆ Vålerenga     │
└────────┴───────────────┘

In [ ]:
from src.config import ELITESERIEN_SEASONS, SCRAPE_DELAY_SECONDS
from src.utils import scrape_eliteserien_goal_scorers_for_seasons

goal_scorers = scrape_eliteserien_goal_scorers_for_seasons(
    seasons=[(2014,2015)],
    delay_seconds=1,
)

processing match 1 of 240
processing match 2 of 240
processing match 3 of 240
processing match 4 of 240
processing match 5 of 240
processing match 6 of 240
processing match 7 of 240
processing match 8 of 240
processing match 9 of 240

In [3]:
import polars as pl
pl.DataFrame(goal_scorers)

shape: (8_136, 8)
┌────────┬────────────┬──────────┬──────────────┬─────────────┬────────┬─────────────┬─────────────┐
│ season ┆ date       ┆ matchday ┆ home_team    ┆ away_team   ┆ result ┆ scorer_team ┆ scorer_name │
│ ---    ┆ ---        ┆ ---      ┆ ---          ┆ ---         ┆ ---    ┆ ---         ┆ ---         │
│ i64    ┆ date       ┆ i64      ┆ str          ┆ str         ┆ str    ┆ str         ┆ str         │
╞════════╪════════════╪══════════╪══════════════╪═════════════╪════════╪═════════════╪═════════════╡
│ 2015   ┆ 2015-04-06 ┆ 1        ┆ Mjøndalen    ┆ Viking FK   ┆ 1:0    ┆ Mjøndalen   ┆ S. Kapidzic │
│        ┆            ┆          ┆              ┆             ┆        ┆ IF          ┆             │
│ 2015   ┆ 2015-04-06 ┆ 1        ┆ Rosenborg BK ┆ Aalesunds   ┆ 5:0    ┆             ┆ P. Helland  │
│        ┆            ┆          ┆              ┆ FK          ┆        ┆             ┆             │
│ 2015   ┆ 2015-04-06 ┆ 1        ┆ Rosenborg BK ┆ Aalesunds   ┆ 5:0    ┆             ┆ P. Helland  │
│        ┆            ┆          ┆              ┆ FK          ┆        ┆             ┆             │
│ 2015   ┆ 2015-04-06 ┆ 1        ┆ Rosenborg BK ┆ Aalesunds   ┆ 5:0    ┆             ┆ A.          │
│        ┆            ┆          ┆              ┆ FK          ┆        ┆             ┆ Søderlund   │
│ 2015   ┆ 2015-04-06 ┆ 1        ┆ Rosenborg BK ┆ Aalesunds   ┆ 5:0    ┆             ┆ A.          │
│        ┆            ┆          ┆              ┆ FK          ┆        ┆             ┆ Søderlund   │
│ …      ┆ …          ┆ …        ┆ …            ┆ …           ┆ …      ┆ …           ┆ …           │
│ 2026   ┆ 2026-08-30 ┆ 19       ┆ Lillestrøm   ┆ Fredrikstad ┆ 1:4    ┆ Lillestrøm  ┆ F.          │
│        ┆            ┆          ┆ SK           ┆ FK          ┆        ┆ SK          ┆ Gulbrandsen │
│ 2026   ┆ 2026-08-30 ┆ 19       ┆ Lillestrøm   ┆ Fredrikstad ┆ 1:4    ┆ Fredrikstad ┆ S. Owusu    │
│        ┆            ┆          ┆ SK           ┆ FK          ┆        ┆ FK          ┆             │
│ 2026   ┆ 2026-08-30 ┆ 19       ┆ Lillestrøm   ┆ Fredrikstad ┆ 1:4    ┆ Fredrikstad ┆ M. Nilsson  │
│        ┆            ┆          ┆ SK           ┆ FK          ┆        ┆ FK          ┆             │
│ 2026   ┆ 2026-08-30 ┆ 19       ┆ Lillestrøm   ┆ Fredrikstad ┆ 1:4    ┆ Fredrikstad ┆ B. Faraas   │
│        ┆            ┆          ┆ SK           ┆ FK          ┆        ┆ FK          ┆             │
│ 2026   ┆ 2026-08-30 ┆ 19       ┆ Lillestrøm   ┆ Fredrikstad ┆ 1:4    ┆ Fredrikstad ┆ B. Faraas   │
│        ┆            ┆          ┆ SK           ┆ FK          ┆        ┆ FK          ┆             │
└────────┴────────────┴──────────┴──────────────┴─────────────┴────────┴─────────────┴─────────────┘

In [2]:
available_events = get_available_events()

In [3]:
for event in available_events:
    print(event['event_id'])

1085523
1187151
1188514

In [18]:
eliteserien_results = scrape_eliteserien_results(season_id = 2025,year = 2026)

In [19]:
pl.DataFrame(eliteserien_results)

shape: (144, 6)
┌────────────┬──────────┬─────────────────┬────────────────┬────────┬──────────────────────────────┐
│ date       ┆ matchday ┆ home_team       ┆ away_team      ┆ result ┆ snapshot_at                  │
│ ---        ┆ ---      ┆ ---             ┆ ---            ┆ ---    ┆ ---                          │
│ date       ┆ i64      ┆ str             ┆ str            ┆ str    ┆ datetime[μs, UTC]            │
╞════════════╪══════════╪═════════════════╪════════════════╪════════╪══════════════════════════════╡
│ 2026-03-14 ┆ 1        ┆ HamKam          ┆ Viking FK      ┆ 2:1    ┆ 2026-09-01 09:53:45.721672   │
│            ┆          ┆                 ┆                ┆        ┆ UTC                          │
│ 2026-03-14 ┆ 1        ┆ Molde FK        ┆ Rosenborg BK   ┆ 2:0    ┆ 2026-09-01 09:53:45.721672   │
│            ┆          ┆                 ┆                ┆        ┆ UTC                          │
│ 2026-03-15 ┆ 1        ┆ Kristiansund BK ┆ SK Brann       ┆ 3:2    ┆ 2026-09-01 09:53:45.721672   │
│            ┆          ┆                 ┆                ┆        ┆ UTC                          │
│ 2026-03-15 ┆ 1        ┆ KFUM Oslo       ┆ IK Start       ┆ 2:0    ┆ 2026-09-01 09:53:45.721672   │
│            ┆          ┆                 ┆                ┆        ┆ UTC                          │
│ 2026-03-15 ┆ 1        ┆ Vålerenga       ┆ Sandefjord     ┆ 1:0    ┆ 2026-09-01 09:53:45.721672   │
│            ┆          ┆                 ┆                ┆        ┆ UTC                          │
│ …          ┆ …        ┆ …               ┆ …              ┆ …      ┆ …                            │
│ 2026-08-30 ┆ 19       ┆ IK Start        ┆ KFUM Oslo      ┆ 4:1    ┆ 2026-09-01 09:53:45.721672   │
│            ┆          ┆                 ┆                ┆        ┆ UTC                          │
│ 2026-08-30 ┆ 19       ┆ Tromsø IL       ┆ Sarpsborg 08   ┆ 0:0    ┆ 2026-09-01 09:53:45.721672   │
│            ┆          ┆                 ┆                ┆        ┆ UTC                          │
│ 2026-08-30 ┆ 19       ┆ Viking FK       ┆ Aalesunds FK   ┆ 2:1    ┆ 2026-09-01 09:53:45.721672   │
│            ┆          ┆                 ┆                ┆        ┆ UTC                          │
│ 2026-08-30 ┆ 19       ┆ Vålerenga       ┆ Molde FK       ┆ 3:4    ┆ 2026-09-01 09:53:45.721672   │
│            ┆          ┆                 ┆                ┆        ┆ UTC                          │
│ 2026-08-30 ┆ 19       ┆ Lillestrøm SK   ┆ Fredrikstad FK ┆ 1:4    ┆ 2026-09-01 09:53:45.721672   │
│            ┆          ┆                 ┆                ┆        ┆ UTC                          │
└────────────┴──────────┴─────────────────┴────────────────┴────────┴──────────────────────────────┘

In [3]:
create_table_after_round(eliteserien_results)

shape: (272, 11)
┌──────────┬────────────┬────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ matchday ┆ team       ┆ points ┆ goals_for ┆ … ┆ total_goal ┆ total_goal ┆ total_goa ┆ table_pos │
│ ---      ┆ ---        ┆ ---    ┆ ---       ┆   ┆ s_for      ┆ s_against  ┆ l_differe ┆ ition     │
│ i64      ┆ str        ┆ i32    ┆ i64       ┆   ┆ ---        ┆ ---        ┆ nce       ┆ ---       │
│          ┆            ┆        ┆           ┆   ┆ i64        ┆ i64        ┆ ---       ┆ u32       │
│          ┆            ┆        ┆           ┆   ┆            ┆            ┆ i64       ┆           │
╞══════════╪════════════╪════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 1        ┆ HamKam     ┆ 3      ┆ 2         ┆ … ┆ 2          ┆ 1          ┆ 1         ┆ 1         │
│ 1        ┆ KFUM Oslo  ┆ 3      ┆ 2         ┆ … ┆ 2          ┆ 0          ┆ 2         ┆ 1         │
│ 1        ┆ Kristiansu ┆ 3      ┆ 3         ┆ … ┆ 3          ┆ 2          ┆ 1         ┆ 1         │
│          ┆ nd BK      ┆        ┆           ┆   ┆            ┆            ┆           ┆           │
│ 1        ┆ Lillestrøm ┆ 3      ┆ 3         ┆ … ┆ 3          ┆ 1          ┆ 2         ┆ 1         │
│          ┆ SK         ┆        ┆           ┆   ┆            ┆            ┆           ┆           │
│ 1        ┆ Molde FK   ┆ 3      ┆ 2         ┆ … ┆ 2          ┆ 0          ┆ 2         ┆ 1         │
│ …        ┆ …          ┆ …      ┆ …         ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 18       ┆ KFUM Oslo  ┆ 1      ┆ 1         ┆ … ┆ 19         ┆ 27         ┆ -8        ┆ 12        │
│ 18       ┆ Sandefjord ┆ 3      ┆ 2         ┆ … ┆ 15         ┆ 23         ┆ -8        ┆ 13        │
│ 18       ┆ Aalesunds  ┆ 1      ┆ 5         ┆ … ┆ 27         ┆ 41         ┆ -14       ┆ 14        │
│          ┆ FK         ┆        ┆           ┆   ┆            ┆            ┆           ┆           │
│ 18       ┆ Kristiansu ┆ 0      ┆ 0         ┆ … ┆ 15         ┆ 27         ┆ -12       ┆ 14        │
│          ┆ nd BK      ┆        ┆           ┆   ┆            ┆            ┆           ┆           │
│ 18       ┆ IK Start   ┆ 0      ┆ 0         ┆ … ┆ 16         ┆ 38         ┆ -22       ┆ 16        │
└──────────┴────────────┴────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [4]:
paok = scrape_ticket_sections(1187151)

In [8]:
from src.utils import scrape_eliteserien_results_for_seasons

results = scrape_eliteserien_results_for_seasons(
    seasons=[
        (2025, 2026),
        (2024, 2025),
        (2023, 2024),
    ],
    delay_seconds=5.0,
)

In [10]:
pl.DataFrame(results).filter(pl.col('date').dt.year()==2025).filter(pl.col('home_team').str.contains('Brann'))

shape: (15, 6)
┌────────────┬──────────┬───────────┬────────────────┬────────┬────────────────────────────────┐
│ date       ┆ matchday ┆ home_team ┆ away_team      ┆ result ┆ snapshot_at                    │
│ ---        ┆ ---      ┆ ---       ┆ ---            ┆ ---    ┆ ---                            │
│ date       ┆ i64      ┆ str       ┆ str            ┆ str    ┆ datetime[μs, UTC]              │
╞════════════╪══════════╪═══════════╪════════════════╪════════╪════════════════════════════════╡
│ 2025-04-06 ┆ 2        ┆ SK Brann  ┆ Tromsø IL      ┆ 3:1    ┆ 2026-09-02 11:00:27.335750 UTC │
│ 2025-04-10 ┆ 17       ┆ SK Brann  ┆ Strømsgodset   ┆ 2:1    ┆ 2026-09-02 11:00:27.335750 UTC │
│ 2025-04-27 ┆ 4        ┆ SK Brann  ┆ Bryne          ┆ 3:2    ┆ 2026-09-02 11:00:27.335750 UTC │
│ 2025-05-11 ┆ 6        ┆ SK Brann  ┆ Rosenborg BK   ┆ 0:0    ┆ 2026-09-02 11:00:27.335750 UTC │
│ 2025-05-16 ┆ 7        ┆ SK Brann  ┆ Sarpsborg 08   ┆ 2:2    ┆ 2026-09-02 11:00:27.335750 UTC │
│ …          ┆ …        ┆ …         ┆ …              ┆ …      ┆ …                              │
│ 2025-09-28 ┆ 19       ┆ SK Brann  ┆ Fredrikstad FK ┆ 1:0    ┆ 2026-09-02 11:00:27.335750 UTC │
│ 2025-10-18 ┆ 25       ┆ SK Brann  ┆ Haugesund      ┆ 4:1    ┆ 2026-09-02 11:00:27.335750 UTC │
│ 2025-10-29 ┆ 23       ┆ SK Brann  ┆ Bodø/Glimt     ┆ 1:2    ┆ 2026-09-02 11:00:27.335750 UTC │
│ 2025-11-09 ┆ 28       ┆ SK Brann  ┆ KFUM Oslo      ┆ 1:1    ┆ 2026-09-02 11:00:27.335750 UTC │
│ 2025-11-30 ┆ 30       ┆ SK Brann  ┆ HamKam         ┆ 3:1    ┆ 2026-09-02 11:00:27.335750 UTC │
└────────────┴──────────┴───────────┴────────────────┴────────┴────────────────────────────────┘

In [2]:
from src.agent import run_question

run_question("Hva er den lengste seiersstreaken som Brann har hatt i 2026?")

SQL:
WITH brann_matches AS (
    SELECT
        date,
        matchday,
        season,
        home_team,
        away_team,
        winner
    FROM fct_matches
    WHERE season = 2026
      AND (home_team = 'SK Brann' OR away_team = 'SK Brann')
    ORDER BY date
),
streaks AS (
    SELECT
        date,
        matchday,
        CASE
            WHEN (home_team = 'SK Brann' AND winner = 'home_team')
              OR (away_team = 'SK Brann' AND winner = 'away_team')
            THEN 1 ELSE 0 END AS is_win
    FROM brann_matches
    ORDER BY date
),
grouped AS (
    SELECT
        *,
        SUM(CASE WHEN is_win = 0 THEN 1 ELSE 0 END) OVER (ORDER BY date ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) AS grp
    FROM streaks
),
win_streaks AS (
    SELECT
        grp,
        COUNT(*) AS streak_length
    FROM grouped
    WHERE is_win = 1
    GROUP BY grp
)
SELECT
    COALESCE(MAX(streak_length), 0) AS longest_win_streak
FROM win_streaks

Sammendrag:
Den lengste seiersrekken Brann har hatt i 2026 er tre kamper på rad.

In [ ]:

import src.agent
for event in src.agent.agent.stream(
    {"question": ""},
    stream_mode="updates",
):
    print(event)

{'plan_tasks': {'tasks': ['Finn Branns form de siste kampene før møtet med Start i 2026.', 'Finn Starts form de siste kampene før møtet med Brann i 2026.', 'Beregn og presenter målforskjellen for Brann i de siste kampene før møtet.', 'Beregn og presenter målforskjellen for Start i de siste kampene før møtet.'], 'task_index': 0, 'generated_sqls': [], 'collected_results': [], 'current_task': 'Finn Branns form de siste kampene før møtet med Start i 2026.', 'sql_error': '', 'attempts': 0}}
{'generate_sql': {'current_task': 'Finn Branns form de siste kampene før møtet med Start i 2026.', 'sql': "WITH start_team AS (\n    SELECT team_name\n    FROM dim_teams\n    WHERE season = 2026\n      AND team_name ILIKE '%Start%'\n    LIMIT 1\n), start_match AS (\n    SELECT date\n    FROM fct_matches\n    WHERE season = 2026\n      AND ((home_team = 'SK Brann' AND away_team = (SELECT team_name FROM start_team))\n        OR (away_team = 'SK Brann' AND home_team = (SELECT team_name FROM start_team)))\n    ORDER BY date\n    LIMIT 1\n)\nSELECT \n    season,\n    date,\n    matchday,\n    home_team,\n    away_team,\n    result,\n    winner\nFROM fct_matches\nWHERE season = 2026\n  AND (home_team = 'SK Brann' OR away_team = 'SK Brann')\n  AND date < (SELECT date FROM start_match)\nORDER BY date DESC\nLIMIT 5", 'attempts': 1}}
{'execute_sql': {'columns': ['season', 'date', 'matchday', 'home_team', 'away_team', 'result', 'winner'], 'rows': [(2026, datetime.date(2026, 5, 29), 11, 'SK Brann', 'Sarpsborg 08', '1:2', 'away_team'), (2026, datetime.date(2026, 5, 24), 10, 'Bodø/Glimt', 'SK Brann', '3:1', 'home_team'), (2026, datetime.date(2026, 5, 20), 8, 'Aalesunds FK', 'SK Brann', '2:1', 'home_team'), (2026, datetime.date(2026, 5, 16), 9, 'SK Brann', 'KFUM Oslo', '2:1', 'home_team'), (2026, datetime.date(2026, 5, 2), 7, 'SK Brann', 'Fredrikstad FK', '3:1', 'home_team')], 'sql_error': ''}}
{'collect_result': {'collected_results': [{'task': 'Finn Branns form de siste kampene før møtet med Start i 2026.', 'sql': "WITH start_team AS (\n    SELECT team_name\n    FROM dim_teams\n    WHERE season = 2026\n      AND team_name ILIKE '%Start%'\n    LIMIT 1\n), start_match AS (\n    SELECT date\n    FROM fct_matches\n    WHERE season = 2026\n      AND ((home_team = 'SK Brann' AND away_team = (SELECT team_name FROM start_team))\n        OR (away_team = 'SK Brann' AND home_team = (SELECT team_name FROM start_team)))\n    ORDER BY date\n    LIMIT 1\n)\nSELECT \n    season,\n    date,\n    matchday,\n    home_team,\n    away_team,\n    result,\n    winner\nFROM fct_matches\nWHERE season = 2026\n  AND (home_team = 'SK Brann' OR away_team = 'SK Brann')\n  AND date < (SELECT date FROM start_match)\nORDER BY date DESC\nLIMIT 5", 'columns': ['season', 'date', 'matchday', 'home_team', 'away_team', 'result', 'winner'], 'rows': [(2026, datetime.date(2026, 5, 29), 11, 'SK Brann', 'Sarpsborg 08', '1:2', 'away_team'), (2026, datetime.date(2026, 5, 24), 10, 'Bodø/Glimt', 'SK Brann', '3:1', 'home_team'), (2026, datetime.date(2026, 5, 20), 8, 'Aalesunds FK', 'SK Brann', '2:1', 'home_team'), (2026, datetime.date(2026, 5, 16), 9, 'SK Brann', 'KFUM Oslo', '2:1', 'home_team'), (2026, datetime.date(2026, 5, 2), 7, 'SK Brann', 'Fredrikstad FK', '3:1', 'home_team')], 'truncated': False}], 'generated_sqls': ["WITH start_team AS (\n    SELECT team_name\n    FROM dim_teams\n    WHERE season = 2026\n      AND team_name ILIKE '%Start%'\n    LIMIT 1\n), start_match AS (\n    SELECT date\n    FROM fct_matches\n    WHERE season = 2026\n      AND ((home_team = 'SK Brann' AND away_team = (SELECT team_name FROM start_team))\n        OR (away_team = 'SK Brann' AND home_team = (SELECT team_name FROM start_team)))\n    ORDER BY date\n    LIMIT 1\n)\nSELECT \n    season,\n    date,\n    matchday,\n    home_team,\n    away_team,\n    result,\n    winner\nFROM fct_matches\nWHERE season = 2026\n  AND (home_team = 'SK Brann' OR away_team = 'SK Brann')\n  AND date < (SELECT date FROM start_match)\nORDER BY date DESC\nLIMIT 5"], 'task_index': 1, 'current_task': 'Finn Starts form de siste kampene før møtet med Brann i 2026.', 'sql_error': '', 'attempts': 0}}
{'generate_sql': {'current_task': 'Finn Starts form de siste kampene før møtet med Brann i 2026.', 'sql': "WITH starts_team AS (\n    SELECT team_name\n    FROM dim_teams\n    WHERE season = 2026\n      AND team_name ILIKE '%Starts%'\n),\nmatches_before_brann AS (\n    SELECT \n        m.season,\n        m.date,\n        m.matchday,\n        m.home_team,\n        m.away_team,\n        m.result,\n        m.winner\n    FROM fct_matches m\n    JOIN starts_team s ON (m.home_team = s.team_name OR m.away_team = s.team_name)\n    WHERE m.season = 2026\n      AND m.date < (\n            SELECT MIN(m2.date)\n            FROM fct_matches m2\n            JOIN starts_team s2 ON (m2.home_team = s2.team_name OR m2.away_team = s2.team_name)\n            WHERE m2.season = 2026\n              AND (m2.home_team = 'SK Brann' OR m2.away_team = 'SK Brann')\n      )\n    ORDER BY m.date DESC\n    LIMIT 5\n)\nSELECT *\nFROM matches_before_brann\nORDER BY date DESC", 'attempts': 1}}
{'execute_sql': {'columns': ['season', 'date', 'matchday', 'home_team', 'away_team', 'result', 'winner'], 'rows': [], 'sql_error': ''}}
{'collect_result': {'collected_results': [{'task': 'Finn Branns form de siste kampene før møtet med Start i 2026.', 'sql': "WITH start_team AS (\n    SELECT team_name\n    FROM dim_teams\n    WHERE season = 2026\n      AND team_name ILIKE '%Start%'\n    LIMIT 1\n), start_match AS (\n    SELECT date\n    FROM fct_matches\n    WHERE season = 2026\n      AND ((home_team = 'SK Brann' AND away_team = (SELECT team_name FROM start_team))\n        OR (away_team = 'SK Brann' AND home_team = (SELECT team_name FROM start_team)))\n    ORDER BY date\n    LIMIT 1\n)\nSELECT \n    season,\n    date,\n    matchday,\n    home_team,\n    away_team,\n    result,\n    winner\nFROM fct_matches\nWHERE season = 2026\n  AND (home_team = 'SK Brann' OR away_team = 'SK Brann')\n  AND date < (SELECT date FROM start_match)\nORDER BY date DESC\nLIMIT 5", 'columns': ['season', 'date', 'matchday', 'home_team', 'away_team', 'result', 'winner'], 'rows': [(2026, datetime.date(2026, 5, 29), 11, 'SK Brann', 'Sarpsborg 08', '1:2', 'away_team'), (2026, datetime.date(2026, 5, 24), 10, 'Bodø/Glimt', 'SK Brann', '3:1', 'home_team'), (2026, datetime.date(2026, 5, 20), 8, 'Aalesunds FK', 'SK Brann', '2:1', 'home_team'), (2026, datetime.date(2026, 5, 16), 9, 'SK Brann', 'KFUM Oslo', '2:1', 'home_team'), (2026, datetime.date(2026, 5, 2), 7, 'SK Brann', 'Fredrikstad FK', '3:1', 'home_team')], 'truncated': False}, {'task': 'Finn Starts form de siste kampene før møtet med Brann i 2026.', 'sql': "WITH starts_team AS (\n    SELECT team_name\n    FROM dim_teams\n    WHERE season = 2026\n      AND team_name ILIKE '%Starts%'\n),\nmatches_before_brann AS (\n    SELECT \n        m.season,\n        m.date,\n        m.matchday,\n        m.home_team,\n        m.away_team,\n        m.result,\n        m.winner\n    FROM fct_matches m\n    JOIN starts_team s ON (m.home_team = s.team_name OR m.away_team = s.team_name)\n    WHERE m.season = 2026\n      AND m.date < (\n            SELECT MIN(m2.date)\n            FROM fct_matches m2\n            JOIN starts_team s2 ON (m2.home_team = s2.team_name OR m2.away_team = s2.team_name)\n            WHERE m2.season = 2026\n              AND (m2.home_team = 'SK Brann' OR m2.away_team = 'SK Brann')\n      )\n    ORDER BY m.date DESC\n    LIMIT 5\n)\nSELECT *\nFROM matches_before_brann\nORDER BY date DESC", 'columns': ['season', 'date', 'matchday', 'home_team', 'away_team', 'result', 'winner'], 'rows': [], 'truncated': False}], 'generated_sqls': ["WITH start_team AS (\n    SELECT team_name\n    FROM dim_teams\n    WHERE season = 2026\n      AND team_name ILIKE '%Start%'\n    LIMIT 1\n), start_match AS (\n    SELECT date\n    FROM fct_matches\n    WHERE season = 2026\n      AND ((home_team = 'SK Brann' AND away_team = (SELECT team_name FROM start_team))\n        OR (away_team = 'SK Brann' AND home_team = (SELECT team_name FROM start_team)))\n    ORDER BY date\n    LIMIT 1\n)\nSELECT \n    season,\n    date,\n    matchday,\n    home_team,\n    away_team,\n    result,\n    winner\nFROM fct_matches\nWHERE season = 2026\n  AND (home_team = 'SK Brann' OR away_team = 'SK Brann')\n  AND date < (SELECT date FROM start_match)\nORDER BY date DESC\nLIMIT 5", "WITH starts_team AS (\n    SELECT team_name\n    FROM dim_teams\n    WHERE season = 2026\n      AND team_name ILIKE '%Starts%'\n),\nmatches_before_brann AS (\n    SELECT \n        m.season,\n        m.date,\n        m.matchday,\n        m.home_team,\n        m.away_team,\n        m.result,\n        m.winner\n    FROM fct_matches m\n    JOIN starts_team s ON (m.home_team = s.team_name OR m.away_team = s.team_name)\n    WHERE m.season = 2026\n      AND m.date < (\n            SELECT MIN(m2.date)\n            FROM fct_matches m2\n            JOIN starts_team s2 ON (m2.home_team = s2.team_name OR m2.away_team = s2.team_name)\n            WHERE m2.season = 2026\n              AND (m2.home_team = 'SK Brann' OR m2.away_team = 'SK Brann')\n      )\n    ORDER BY m.date DESC\n    LIMIT 5\n)\nSELECT *\nFROM matches_before_brann\nORDER BY date DESC"], 'task_index': 2, 'current_task': 'Beregn og presenter målforskjellen for Brann i de siste kampene før møtet.', 'sql_error': '', 'attempts': 0}}
{'generate_sql': {'current_task': 'Beregn og presenter målforskjellen for Brann i de siste kampene før møtet.', 'sql': "SELECT \n    date,\n    matchday,\n    home_team,\n    away_team,\n    result,\n    (home_goals - away_goals) * CASE WHEN home_team = 'SK Brann' THEN 1 WHEN away_team = 'SK Brann' THEN -1 ELSE 0 END AS brann_goal_difference\nFROM fct_matches\nWHERE (home_team = 'SK Brann' OR away_team = 'SK Brann')\nORDER BY date DESC\nLIMIT 5", 'attempts': 1}}
{'execute_sql': {'columns': ['date', 'matchday', 'home_team', 'away_team', 'result', 'brann_goal_difference'], 'rows': [(datetime.date(2026, 9, 5), 20, 'SK Brann', 'Lillestrøm SK', '1:2', -1), (datetime.date(2026, 8, 30), 19, 'Sandefjord', 'SK Brann', '0:0', 0), (datetime.date(2026, 8, 16), 18, 'SK Brann', 'HamKam', '3:0', 3), (datetime.date(2026, 8, 2), 16, 'SK Brann', 'Rosenborg BK', '3:2', 1), (datetime.date(2026, 7, 26), 15, 'SK Brann', 'Vålerenga', '2:3', -1)], 'sql_error': ''}}
{'collect_result': {'collected_results': [{'task': 'Finn Branns form de siste kampene før møtet med Start i 2026.', 'sql': "WITH start_team AS (\n    SELECT team_name\n    FROM dim_teams\n    WHERE season = 2026\n      AND team_name ILIKE '%Start%'\n    LIMIT 1\n), start_match AS (\n    SELECT date\n    FROM fct_matches\n    WHERE season = 2026\n      AND ((home_team = 'SK Brann' AND away_team = (SELECT team_name FROM start_team))\n        OR (away_team = 'SK Brann' AND home_team = (SELECT team_name FROM start_team)))\n    ORDER BY date\n    LIMIT 1\n)\nSELECT \n    season,\n    date,\n    matchday,\n    home_team,\n    away_team,\n    result,\n    winner\nFROM fct_matches\nWHERE season = 2026\n  AND (home_team = 'SK Brann' OR away_team = 'SK Brann')\n  AND date < (SELECT date FROM start_match)\nORDER BY date DESC\nLIMIT 5", 'columns': ['season', 'date', 'matchday', 'home_team', 'away_team', 'result', 'winner'], 'rows': [(2026, datetime.date(2026, 5, 29), 11, 'SK Brann', 'Sarpsborg 08', '1:2', 'away_team'), (2026, datetime.date(2026, 5, 24), 10, 'Bodø/Glimt', 'SK Brann', '3:1', 'home_team'), (2026, datetime.date(2026, 5, 20), 8, 'Aalesunds FK', 'SK Brann', '2:1', 'home_team'), (2026, datetime.date(2026, 5, 16), 9, 'SK Brann', 'KFUM Oslo', '2:1', 'home_team'), (2026, datetime.date(2026, 5, 2), 7, 'SK Brann', 'Fredrikstad FK', '3:1', 'home_team')], 'truncated': False}, {'task': 'Finn Starts form de siste kampene før møtet med Brann i 2026.', 'sql': "WITH starts_team AS (\n    SELECT team_name\n    FROM dim_teams\n    WHERE season = 2026\n      AND team_name ILIKE '%Starts%'\n),\nmatches_before_brann AS (\n    SELECT \n        m.season,\n        m.date,\n        m.matchday,\n        m.home_team,\n        m.away_team,\n        m.result,\n        m.winner\n    FROM fct_matches m\n    JOIN starts_team s ON (m.home_team = s.team_name OR m.away_team = s.team_name)\n    WHERE m.season = 2026\n      AND m.date < (\n            SELECT MIN(m2.date)\n            FROM fct_matches m2\n            JOIN starts_team s2 ON (m2.home_team = s2.team_name OR m2.away_team = s2.team_name)\n            WHERE m2.season = 2026\n              AND (m2.home_team = 'SK Brann' OR m2.away_team = 'SK Brann')\n      )\n    ORDER BY m.date DESC\n    LIMIT 5\n)\nSELECT *\nFROM matches_before_brann\nORDER BY date DESC", 'columns': ['season', 'date', 'matchday', 'home_team', 'away_team', 'result', 'winner'], 'rows': [], 'truncated': False}, {'task': 'Beregn og presenter målforskjellen for Brann i de siste kampene før møtet.', 'sql': "SELECT \n    date,\n    matchday,\n    home_team,\n    away_team,\n    result,\n    (home_goals - away_goals) * CASE WHEN home_team = 'SK Brann' THEN 1 WHEN away_team = 'SK Brann' THEN -1 ELSE 0 END AS brann_goal_difference\nFROM fct_matches\nWHERE (home_team = 'SK Brann' OR away_team = 'SK Brann')\nORDER BY date DESC\nLIMIT 5", 'columns': ['date', 'matchday', 'home_team', 'away_team', 'result', 'brann_goal_difference'], 'rows': [(datetime.date(2026, 9, 5), 20, 'SK Brann', 'Lillestrøm SK', '1:2', -1), (datetime.date(2026, 8, 30), 19, 'Sandefjord', 'SK Brann', '0:0', 0), (datetime.date(2026, 8, 16), 18, 'SK Brann', 'HamKam', '3:0', 3), (datetime.date(2026, 8, 2), 16, 'SK Brann', 'Rosenborg BK', '3:2', 1), (datetime.date(2026, 7, 26), 15, 'SK Brann', 'Vålerenga', '2:3', -1)], 'truncated': False}], 'generated_sqls': ["WITH start_team AS (\n    SELECT team_name\n    FROM dim_teams\n    WHERE season = 2026\n      AND team_name ILIKE '%Start%'\n    LIMIT 1\n), start_match AS (\n    SELECT date\n    FROM fct_matches\n    WHERE season = 2026\n      AND ((home_team = 'SK Brann' AND away_team = (SELECT team_name FROM start_team))\n        OR (away_team = 'SK Brann' AND home_team = (SELECT team_name FROM start_team)))\n    ORDER BY date\n    LIMIT 1\n)\nSELECT \n    season,\n    date,\n    matchday,\n    home_team,\n    away_team,\n    result,\n    winner\nFROM fct_matches\nWHERE season = 2026\n  AND (home_team = 'SK Brann' OR away_team = 'SK Brann')\n  AND date < (SELECT date FROM start_match)\nORDER BY date DESC\nLIMIT 5", "WITH starts_team AS (\n    SELECT team_name\n    FROM dim_teams\n    WHERE season = 2026\n      AND team_name ILIKE '%Starts%'\n),\nmatches_before_brann AS (\n    SELECT \n        m.season,\n        m.date,\n        m.matchday,\n        m.home_team,\n        m.away_team,\n        m.result,\n        m.winner\n    FROM fct_matches m\n    JOIN starts_team s ON (m.home_team = s.team_name OR m.away_team = s.team_name)\n    WHERE m.season = 2026\n      AND m.date < (\n            SELECT MIN(m2.date)\n            FROM fct_matches m2\n            JOIN starts_team s2 ON (m2.home_team = s2.team_name OR m2.away_team = s2.team_name)\n            WHERE m2.season = 2026\n              AND (m2.home_team = 'SK Brann' OR m2.away_team = 'SK Brann')\n      )\n    ORDER BY m.date DESC\n    LIMIT 5\n)\nSELECT *\nFROM matches_before_brann\nORDER BY date DESC", "SELECT \n    date,\n    matchday,\n    home_team,\n    away_team,\n    result,\n    (home_goals - away_goals) * CASE WHEN home_team = 'SK Brann' THEN 1 WHEN away_team = 'SK Brann' THEN -1 ELSE 0 END AS brann_goal_difference\nFROM fct_matches\nWHERE (home_team = 'SK Brann' OR away_team = 'SK Brann')\nORDER BY date DESC\nLIMIT 5"], 'task_index': 3, 'current_task': 'Beregn og presenter målforskjellen for Start i de siste kampene før møtet.', 'sql_error': '', 'attempts': 0}}
{'generate_sql': {'current_task': 'Beregn og presenter målforskjellen for Start i de siste kampene før møtet.', 'sql': "WITH team_name_cte AS (\n    SELECT team_name\n    FROM dim_teams\n    WHERE season = (SELECT MAX(season) FROM fct_matches)\n      AND team_name ILIKE '%Start%'\n    LIMIT 1\n), recent_matches AS (\n    SELECT\n        m.date,\n        m.home_team,\n        m.away_team,\n        m.home_goals,\n        m.away_goals,\n        CASE\n            WHEN m.home_team = t.team_name THEN m.home_goals - m.away_goals\n            WHEN m.away_team = t.team_name THEN m.away_goals - m.home_goals\n        END AS goal_difference\n    FROM fct_matches m\n    CROSS JOIN team_name_cte t\n    WHERE (m.home_team = t.team_name OR m.away_team = t.team_name)\n      AND m.date < (\n          SELECT MIN(date)\n          FROM fct_matches\n          WHERE (home_team = t.team_name OR away_team = t.team_name)\n            AND (home_team = 'SK Brann' OR away_team = 'SK Brann')\n            AND season = (SELECT MAX(season) FROM fct_matches)\n      )\n      AND m.season = (SELECT MAX(season) FROM fct_matches)\n    ORDER BY m.date DESC\n    LIMIT 5\n)\nSELECT\n    date,\n    home_team,\n    away_team,\n    goal_difference\nFROM recent_matches\nORDER BY date DESC", 'attempts': 1}}
{'execute_sql': {'columns': ['date', 'home_team', 'away_team', 'goal_difference'], 'rows': [(datetime.date(2026, 5, 29), 'Fredrikstad FK', 'IK Start', -1), (datetime.date(2026, 5, 25), 'IK Start', 'Vålerenga', 2), (datetime.date(2026, 5, 20), 'IK Start', 'Bodø/Glimt', -3), (datetime.date(2026, 5, 16), 'Viking FK', 'IK Start', -3), (datetime.date(2026, 5, 3), 'IK Start', 'Tromsø IL', 0)], 'sql_error': ''}}

In [6]:
query = """

WITH brann_matches AS (
    SELECT
        date,
        matchday,
        season,
        CASE
            WHEN home_team = 'SK Brann' THEN 'home'
            ELSE 'away'
        END AS venue,
        winner
    FROM fct_matches
    WHERE season = 2026
      AND (home_team = 'SK Brann' OR away_team = 'SK Brann')
    ORDER BY date
),
streaks AS (
    SELECT
        date,
        matchday,
        season,
        winner,
        SUM(
            CASE
                WHEN winner =
                    CASE
                        WHEN venue = 'home' THEN 'home_team'
                        ELSE 'away_team'
                    END
                THEN 0
                ELSE 1
            END
        ) OVER (
            ORDER BY date
            ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
        ) AS grp
    FROM brann_matches
),
win_streaks AS (
    SELECT
        grp,
        COUNT(*) AS streak_length
    FROM (
        SELECT
            *,
            CASE
                WHEN winner =
                    CASE
                        WHEN venue = 'home' THEN 'home_team'
                        ELSE 'away_team'
                    END
                THEN 1
                ELSE 0
            END AS is_win
        FROM brann_matches
    ) AS t
    CROSS JOIN LATERAL (
        SELECT
            SUM(
                CASE WHEN is_win = 0 THEN 1 ELSE 0 END
            ) OVER (
                ORDER BY date
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ) AS grp
    )
    WHERE is_win = 1
    GROUP BY grp
)
SELECT MAX(streak_length) AS longest_win_streak
FROM win_streaks;
"""

con = duckdb.connect('data/brann.duckdb')
goal_scorers = pl.from_arrow(con.execute(query).arrow())
con.close()
goal_scorers

BinderException: Binder Error: LATERAL join cannot contain window functions!

In [2]:
from openai import OpenAI

client = OpenAI()

for model in client.models.list().data:
    print(model.id)

gpt-4-0613
gpt-4
gpt-3.5-turbo
gpt-6-astra
gpt-realtime-2.1
gpt-realtime-2.1-mini
gpt-transcribe
gpt-live-transcribe
davinci-002
babbage-002
gpt-3.5-turbo-instruct
gpt-3.5-turbo-instruct-0914
gpt-3.5-turbo-1106
tts-1-hd
tts-1-1106
tts-1-hd-1106
text-embedding-3-small
text-embedding-3-large
gpt-3.5-turbo-0125
gpt-4-turbo
gpt-4-turbo-2024-04-09
gpt-4o
gpt-4o-2024-05-13
gpt-4o-mini-2024-07-18
gpt-4o-mini
gpt-4o-2024-08-06
omni-moderation-latest
omni-moderation-2024-09-26
o1-2024-12-17
o1
o3-mini
o3-mini-2025-01-31
gpt-4o-2024-11-20
gpt-4o-mini-search-preview-2025-03-11
gpt-4o-mini-search-preview
gpt-4o-transcribe
gpt-4o-mini-transcribe
o1-pro-2025-03-19
o1-pro
gpt-4o-mini-tts
o3-2025-04-16
o4-mini-2025-04-16
o3
o4-mini
gpt-4.1-2025-04-14
gpt-4.1
gpt-4.1-mini-2025-04-14
gpt-4.1-mini
gpt-4.1-nano-2025-04-14
gpt-4.1-nano
gpt-image-1
gpt-4o-transcribe-diarize
gpt-5-chat-latest
gpt-5-2025-08-07
gpt-5
gpt-5-mini-2025-08-07
gpt-5-mini
gpt-5-nano-2025-08-07
gpt-5-nano
gpt-audio-2025-08-28
gpt-realtime
gpt-realtime-2025-08-28
gpt-audio
gpt-5-codex
gpt-image-1-mini
gpt-5-pro-2025-10-06
gpt-5-pro
gpt-audio-mini
gpt-audio-mini-2025-10-06
gpt-5-search-api
gpt-realtime-mini
sora-2
sora-2-pro
gpt-5-search-api-2025-10-14
gpt-5.1-chat-latest
gpt-5.1-2025-11-13
gpt-5.1
gpt-5.1-codex
gpt-5.1-codex-mini
gpt-5.1-codex-max
gpt-image-1.5
gpt-5.2-2025-12-11
gpt-5.2
gpt-5.2-pro-2025-12-11
gpt-5.2-pro
gpt-5.2-chat-latest
gpt-4o-mini-transcribe-2025-12-15
gpt-4o-mini-transcribe-2025-03-20
gpt-4o-mini-tts-2025-03-20
gpt-4o-mini-tts-2025-12-15
gpt-realtime-mini-2025-12-15
gpt-audio-mini-2025-12-15
chatgpt-image-latest
gpt-5.2-codex
gpt-5.3-codex
gpt-realtime-1.5
gpt-audio-1.5
gpt-4o-search-preview
gpt-4o-search-preview-2025-03-11
gpt-5.3-chat-latest
gpt-5.4-2026-03-05
gpt-5.4-pro
gpt-5.4-pro-2026-03-05
gpt-5.4
gpt-5.4-nano-2026-03-17
gpt-5.4-nano
gpt-5.4-mini-2026-03-17
gpt-5.4-mini
gpt-image-2
gpt-image-2-2026-04-21
gpt-5.5
gpt-5.5-2026-04-23
gpt-5.5-pro
gpt-5.5-pro-2026-04-23
chat-latest
gpt-realtime-translate
gpt-realtime-2
gpt-realtime-whisper
gpt-5.6-sol
gpt-5.6-terra
gpt-5.6-luna
gpt-3.5-turbo-16k
tts-1
whisper-1
text-embedding-ada-002

In [4]:
client.models.list().data

[Model(id='gpt-4-0613', created=1686588896, object='model', owned_by='openai', shutdown_date='2026-10-23'),
 Model(id='gpt-4', created=1687882411, object='model', owned_by='openai', shutdown_date='2026-10-23'),
 Model(id='gpt-3.5-turbo', created=1677610602, object='model', owned_by='openai', shutdown_date='2026-10-23'),
 Model(id='gpt-6-astra', created=1787853604, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-2.1', created=1782254687, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-2.1-mini', created=1782254706, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-transcribe', created=1785168027, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-live-transcribe', created=1785168034, object='model', owned_by='system', shutdown_date=None),
 Model(id='davinci-002', created=1692634301, object='model', owned_by='system', shutdown_date='2026-09-28'),
 Model(id='babbage-002', created=1692634615, object='model', owned_by='system', shutdown_date='2026-09-28'),
 Model(id='gpt-3.5-turbo-instruct', created=1692901427, object='model', owned_by='system', shutdown_date='2026-09-28'),
 Model(id='gpt-3.5-turbo-instruct-0914', created=1694122472, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-3.5-turbo-1106', created=1698959748, object='model', owned_by='system', shutdown_date='2026-09-28'),
 Model(id='tts-1-hd', created=1699046015, object='model', owned_by='system', shutdown_date=None),
 Model(id='tts-1-1106', created=1699053241, object='model', owned_by='system', shutdown_date=None),
 Model(id='tts-1-hd-1106', created=1699053533, object='model', owned_by='system', shutdown_date=None),
 Model(id='text-embedding-3-small', created=1705948997, object='model', owned_by='system', shutdown_date=None),
 Model(id='text-embedding-3-large', created=1705953180, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-3.5-turbo-0125', created=1706048358, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4-turbo', created=1712361441, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4-turbo-2024-04-09', created=1712601677, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4o', created=1715367049, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-2024-05-13', created=1715368132, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4o-mini-2024-07-18', created=1721172717, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-mini', created=1721172741, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-2024-08-06', created=1722814719, object='model', owned_by='system', shutdown_date=None),
 Model(id='omni-moderation-latest', created=1731689265, object='model', owned_by='system', shutdown_date=None),
 Model(id='omni-moderation-2024-09-26', created=1732734466, object='model', owned_by='system', shutdown_date=None),
 Model(id='o1-2024-12-17', created=1734326976, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='o1', created=1734375816, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='o3-mini', created=1737146383, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='o3-mini-2025-01-31', created=1738010200, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4o-2024-11-20', created=1739331543, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-mini-search-preview-2025-03-11', created=1741390858, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-4o-mini-search-preview', created=1741391161, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-transcribe', created=1742068463, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-mini-transcribe', created=1742068596, object='model', owned_by='system', shutdown_date=None),
 Model(id='o1-pro-2025-03-19', created=1742251504, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='o1-pro', created=1742251791, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4o-mini-tts', created=1742403959, object='model', owned_by='system', shutdown_date=None),
 Model(id='o3-2025-04-16', created=1744133301, object='model', owned_by='system', shutdown_date='2026-12-11'),
 Model(id='o4-mini-2025-04-16', created=1744133506, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='o3', created=1744225308, object='model', owned_by='system', shutdown_date=None),
 Model(id='o4-mini', created=1744225351, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4.1-2025-04-14', created=1744315746, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4.1', created=1744316542, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4.1-mini-2025-04-14', created=1744317547, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4.1-mini', created=1744318173, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4.1-nano-2025-04-14', created=1744321025, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4.1-nano', created=1744321707, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-image-1', created=1745517030, object='model', owned_by='system', shutdown_date='2026-10-23'),
 Model(id='gpt-4o-transcribe-diarize', created=1750798887, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5-chat-latest', created=1754073306, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-5-2025-08-07', created=1754075360, object='model', owned_by='system', shutdown_date='2026-12-11'),
 Model(id='gpt-5', created=1754425777, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5-mini-2025-08-07', created=1754425867, object='model', owned_by='system', shutdown_date='2026-12-11'),
 Model(id='gpt-5-mini', created=1754425928, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5-nano-2025-08-07', created=1754426303, object='model', owned_by='system', shutdown_date='2026-12-11'),
 Model(id='gpt-5-nano', created=1754426384, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-audio-2025-08-28', created=1756256146, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime', created=1756271701, object='model', owned_by='system', shutdown_date='2027-01-20'),
 Model(id='gpt-realtime-2025-08-28', created=1756271773, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-audio', created=1756339249, object='model', owned_by='system', shutdown_date='2027-01-20'),
 Model(id='gpt-5-codex', created=1757527818, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-image-1-mini', created=1758845821, object='model', owned_by='system', shutdown_date='2026-12-01'),
 Model(id='gpt-5-pro-2025-10-06', created=1759469707, object='model', owned_by='system', shutdown_date='2026-12-11'),
 Model(id='gpt-5-pro', created=1759469822, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-audio-mini', created=1759512027, object='model', owned_by='system', shutdown_date='2027-01-20'),
 Model(id='gpt-audio-mini-2025-10-06', created=1759512137, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-5-search-api', created=1759514629, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-mini', created=1759517133, object='model', owned_by='system', shutdown_date='2027-01-20'),
 Model(id='sora-2', created=1759708615, object='model', owned_by='system', shutdown_date='2026-09-24'),
 Model(id='sora-2-pro', created=1759708663, object='model', owned_by='system', shutdown_date='2026-09-24'),
 Model(id='gpt-5-search-api-2025-10-14', created=1760043960, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.1-chat-latest', created=1762547951, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-5.1-2025-11-13', created=1762800353, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.1', created=1762800673, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.1-codex', created=1762988221, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-5.1-codex-mini', created=1763007109, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-5.1-codex-max', created=1763671532, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-image-1.5', created=1764030620, object='model', owned_by='system', shutdown_date='2026-12-01'),
 Model(id='gpt-5.2-2025-12-11', created=1765313028, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.2', created=1765313051, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.2-pro-2025-12-11', created=1765343959, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.2-pro', created=1765343983, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.2-chat-latest', created=1765344352, object='model', owned_by='system', shutdown_date='2026-08-10'),
 Model(id='gpt-4o-mini-transcribe-2025-12-15', created=1765610407, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-mini-transcribe-2025-03-20', created=1765610545, object='model', owned_by='system', shutdown_date='2027-01-20'),
 Model(id='gpt-4o-mini-tts-2025-03-20', created=1765610731, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-4o-mini-tts-2025-12-15', created=1765610837, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-mini-2025-12-15', created=1765612007, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-audio-mini-2025-12-15', created=1765760008, object='model', owned_by='system', shutdown_date=None),
 Model(id='chatgpt-image-latest', created=1765925279, object='model', owned_by='system', shutdown_date='2026-12-01'),
 Model(id='gpt-5.2-codex', created=1766164985, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-5.3-codex', created=1770537915, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-1.5', created=1771461469, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-audio-1.5', created=1771550885, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-search-preview', created=1771905534, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-4o-search-preview-2025-03-11', created=1771905621, object='model', owned_by='system', shutdown_date='2026-07-23'),
 Model(id='gpt-5.3-chat-latest', created=1772236571, object='model', owned_by='system', shutdown_date='2026-08-10'),
 Model(id='gpt-5.4-2026-03-05', created=1772654062, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.4-pro', created=1772659601, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.4-pro-2026-03-05', created=1772659657, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.4', created=1772691852, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.4-nano-2026-03-17', created=1773450837, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.4-nano', created=1773450870, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.4-mini-2026-03-17', created=1773451076, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.4-mini', created=1773451123, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-image-2', created=1776399795, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-image-2-2026-04-21', created=1776399994, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.5', created=1776824847, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.5-2026-04-23', created=1776839241, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.5-pro', created=1776894349, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.5-pro-2026-04-23', created=1776894470, object='model', owned_by='system', shutdown_date=None),
 Model(id='chat-latest', created=1777704602, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-translate', created=1777950216, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-2', created=1778006032, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-realtime-whisper', created=1778012060, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.6-sol', created=1782228018, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.6-terra', created=1782228459, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-5.6-luna', created=1782228658, object='model', owned_by='system', shutdown_date=None),
 Model(id='gpt-3.5-turbo-16k', created=1683758102, object='model', owned_by='openai-internal', shutdown_date=None),
 Model(id='tts-1', created=1681940951, object='model', owned_by='openai-internal', shutdown_date=None),
 Model(id='whisper-1', created=1677532384, object='model', owned_by='openai-internal', shutdown_date=None),
 Model(id='text-embedding-ada-002', created=1671217299, object='model', owned_by='openai-internal', shutdown_date=None)]